### ISSUE TITLE
DEV: Preference Window now spawning

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1033]
Probably a bad merge or something along those lines. Not sure exactly when this broke

```
Traceback (most recent call last):
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 444, in showPreferenceDialog
    dlg = PreferenceDialog(self)
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\preferenceDialog.py", line 64, in __init__
    prefView.populatePanel(page)
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\builtinPreferenceViews\pyfaStatViewPreferences.py", line 84, in populatePanel
    self.rbMisc.SetSelection(self.settings.get('targetingmisc'))
  File "C:\Users\Ryan\Sync\WinPython-32bit-2.7.10.1\python-2.7.10\lib\site-packages\wx-3.0-msw\wx\_controls.py", line 2605, in SetSelection
    return _controls_.RadioBox_SetSelection(*args, **kwargs)
TypeError: in method 'RadioBox_SetSelection', expected argument 2 of type 'int'
```

@Ebag333 maybe it'll be quicker for you to delve into this since you're more familiar with the changes you made. Otherwise I'll take a look asap

**Comment by Ebag333** [comment]
I mispelled it somewhere along the way.  Thought I fixed this before, but it might have gotten reverted while I was fiddling with the patch.
