### ISSUE TITLE
Shuttles (and likely all ships with 0 slots) stacktrace

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#1041]
```
Traceback (most recent call last):
  File ".\gui\builtinViews\fittingView.py", line 483, in fitChanged
    self.refresh(self.mods)
  File ".\gui\builtinViews\fittingView.py", line 637, in refresh
    self.itemRect = self.GetItemRect(0)
  File "C:\Python27\lib\site-packages\wx-3.0-msw\wx\_controls.py", line 4569, in GetItemRect
    return _controls_.ListCtrl_GetItemRect(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "item >= 0 && item < GetItemCount()" failed at ..\..\src\msw\listctrl.cpp(1082) in wxListCtrl::GetSubItemRect(): invalid item in GetSubItemRect
```

Get this when opening a shuttle.  Most like simply because there are no slots but haven't looked into it.

**Comment by blitzmann** [comment]
Thanks, it's been fixed. We don't even use the line that was failing, so I removed it.

Also force pushed to master by mistake - thought I was in dev branch. x_x just fyi :)
