### ISSUE TITLE
Error when deleting damage pattern in damage pattern editor.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1416]
This is for version 2.0.0b3

Have a custom damage pattern in editor.
Press export to clipboard
Press import from clipboard
Select and try delete a custom damage pattern

Result in this error. And other errors when opening the editor again.

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.11.1
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\entityEditor.py", line 149, in OnDelete
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\patternEditor.py", line 85, in DoDelete
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\damagePattern.py", line 62, in deletePattern
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 538, in remove
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1746, in delete
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1754, in _delete_impl
sqlalchemy.exc.InvalidRequestError: Instance '<DamagePattern at 0x52507e50>' is not persisted

Bonus issue, Custom damage pattern named [Missiles][Structure) Standup Missile should probably read [Missiles][Structure] Standup Missile

**Comment by blitzmann** [comment]
This is a bug within 1.35 as well. Checking it out now

**Comment by blitzmann** [comment]
So this was interesting, and has been broken for potentially years.

https://github.com/pyfa-org/Pyfa/blob/master/service/damagePattern.py#L84

The way damage profile imports works is as follows: while parsing each one, if it's new, it creates a new one. This is fine and doesn't cause problems. However, if the import included a profile that exists, it is intended to overwrite it (to keep fit references in check). It seems this was done with a shortcut: `match.__dict__.update(pattern.__dict__)`. The problem with this is that `__dict__` also includes internal SQLAlchemy stuff, so now you're updating the model with incorrect database states and all sorts of mess.

The fix was to move processing to the DamagePattern class itself and provide and `update()` method, which only takes the needed values to update.

I strongly suspect this is the same problem with the Target Resists (I did copy and paste the code after all ;))

**Comment by blitzmann** [comment]
Both issues have been fixed in both master and 2.x :D
