### ISSUE TITLE
Error when deleting target pattern.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1417]
This is for version 2.0.0b3

Have a custom target pattern in editor.
Press export to clipboard
Press import from clipboard
Select and try delete a custom target pattern

Result in this error. And other errors when opening the target editor again.

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.11.1
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\entityEditor.py", line 149, in OnDelete
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\resistsEditor.py", line 83, in DoDelete
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\targetResists.py", line 62, in deletePattern
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 538, in remove
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1746, in delete
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1754, in _delete_impl
sqlalchemy.exc.InvalidRequestError: Instance '<TargetResists at 0x52507e50>' is not persisted

**Comment by blitzmann** [comment]
> Instance '<TargetResists at 0x52507e50>' is not persisted

oh lordy, this is gonna be a fun one
