### ISSUE TITLE
Animate gauges and Show tab tooltips preferences have no effect?

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1434]
### Expected behavior:
Turning off Animate gauges in preferences stops animation of gauges.
Show tab tooltips preference has a observable effect.

### Actual behavior:
Gauges still animate irrespective of Animate gauges option in preferences.
Show tab tooltips preference has no observable effect.

### Detailed steps to reproduce:
Edit a fit for cpu/pg/resistances etc and note gauges animate irrespective of preference option.

### Release or development git branch? Please note the release version or commit hash:
py3

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

**Comment by blitzmann** [comment]
hrm, so the reason for this is because chrome tabs and gauges were migrates a *long* time ago to python 3 / wxpython, just because. Like, years ago. since that time, things have been added (like these options), and when porting over to the py-3 branch, I just took what we already had and didn't check for changes.

Additionally, the tab tooltip isn't even enabled on 1.x, and hasn't been since moving over to wxPython 3.0 I believe. IIRC, it was due to a bunch of issue revolving around that.

Will take a peak and including both these things. :)

**Comment by blitzmann** [comment]
I was a bit hesitant re-enabling the tab preview, since there are a few issues with it. Specifically, it doesn't update correctly if, for example, you edit a fit that is modifying the one in the preview - the preview doesn't know about it.

That being said, for the most part, it seems to still work well. I want to take a deeper dive into it at some point. For example, instead of generating the bitmap when the tab loses focus, generate when requesting the preview. Also want to handle calc flagging so that we can recalc if needed, to address the example above.

but for now, should work, and this issue is solve I believe

**Comment by Neugeniko** [comment]
Getting this error on quit.

[2018-02-25 12:13:07.677674] CRITICAL: gui.errorDialog:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\builtinViews\fittingView.py", line 698, in OnShow
    if not self.IsShown():
RuntimeError: wrapped C/C++ object of type FittingView has been deleted

[2018-02-25 12:13:07.679177] CRITICAL: config: Error in sys.excepthook:
[2018-02-25 12:13:07.683692] CRITICAL: config: Traceback (most recent call last):
[2018-02-25 12:13:07.684189] CRITICAL: config:   File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\errorDialog.py", line 52, in HandleException
[2018-02-25 12:13:07.702742] CRITICAL: config: cls.__frame = ErrorFrame(cls.__parent)
[2018-02-25 12:13:07.704739] CRITICAL: config:   File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\errorDialog.py", line 64, in __init__
[2018-02-25 12:13:07.709755] CRITICAL: config: style=wx.DEFAULT_FRAME_STYLE ^ wx.RESIZE_BORDER | wx.STAY_ON_TOP)
[2018-02-25 12:13:07.710266] CRITICAL: config: RuntimeError
[2018-02-25 12:13:07.711758] CRITICAL: config: :
[2018-02-25 12:13:07.712263] CRITICAL: config: wrapped C/C++ object of type MainFrame has been deleted
[2018-02-25 12:13:07.715806] CRITICAL: config: Original exception was:
[2018-02-25 12:13:07.720283] CRITICAL: config: Traceback (most recent call last):
[2018-02-25 12:13:07.720792] CRITICAL: config:   File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\builtinViews\fittingView.py", line 698, in OnShow
[2018-02-25 12:13:07.722806] CRITICAL: config: if not self.IsShown():
[2018-02-25 12:13:07.723293] CRITICAL: config: RuntimeError
[2018-02-25 12:13:07.723800] CRITICAL: config: :
[2018-02-25 12:13:07.726801] CRITICAL: config: wrapped C/C++ object of type FittingView has been deleted

**Comment by blitzmann** [comment]
Nice catch! Added a fix for it, simply checking is `self` is truthy before continuing
