### ISSUE TITLE
exception of projection edge cases

### ISSUE THREAD

**Issue by Seavert** [pyfa-org/Pyfa#1451]
Dragging some wrong items to Projected pane crushes Pyfa.
Market groups:
Ammunition & Charges - should be ignored.
Deployable Structures - should be ignored.
Implants & Boosters - should be either ignored or applied to related pane.

**Comment by Neugeniko** [comment]
Can reproduce with the following error in py3 branch.

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.4
Logbook version: 1.2.1
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\builtinAdditionPanes\projectedView.py", line 62, in OnData
    self.dropFn(x, y, data)
  File "C:\Program Files (x86)\Newark\prog\Pyfa\gui\builtinAdditionPanes\projectedView.py", line 109, in handleListDrag
    sFit.project(fitID, int(data[1]))
  File "C:\Program Files (x86)\Newark\prog\Pyfa\service\fit.py", line 411, in project
    module = es_Module(thing)
  File "<string>", line 4, in __init__
  File "C:\Python36-32\lib\site-packages\sqlalchemy\orm\state.py", line 417, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Python36-32\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Python36-32\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "C:\Python36-32\lib\site-packages\sqlalchemy\orm\state.py", line 414, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\Program Files (x86)\Newark\prog\Pyfa\eos\saveddata\module.py", line 81, in __init__
    raise ValueError("Passed item is not a Module")
ValueError: Passed item is not a Module

**Comment by blitzmann** [comment]
Fix seems to work well, I'll include it in a point release scheduled for this weekend :D

**Comment by Neugeniko** [comment]
Just looking at this a bit more and is there a reason for launchers..bomb, missile, probe,survey, interdiction to be valid projected items.

**Comment by blitzmann** [comment]
@Neugeniko It's probably because they all use the `useMissiles` effect, which is defined as a projected effect. It's defined as projected because we have custom code in there that runs for Void bombs - void bombs don't have any other effect that can be utilized other than this one (last I checked), but having it on this effect has the side-effect of allowing all launchers to be projectable. :/

**Comment by Neugeniko** [comment]
Thx for the info.
