### ISSUE TITLE
Seg fault: No handlers could be found for logger "sqlalchemy.pool.NullPool"

### ISSUE THREAD

**Issue by pseudonom** [pyfa-org/Pyfa#146]
Pyfa occasionally crashes with the following error on Debian:

```
(python:18443): Gtk-CRITICAL **: IA__gtk_window_set_modal: assertion 'GTK_IS_WINDOW (window)' failed

(python:18443): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem

(python:18443): Gtk-WARNING **: gtk_menu_attach_to_widget(): menu already attached to GtkMenuItem
No handlers could be found for logger "sqlalchemy.pool.NullPool"
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/intrados/Pyfa-1.3.0/gui/utils/exportHtml.py", line 152, in run
    dnaFit = sFit.exportDna(fit[0])
  File "/home/intrados/Pyfa-1.3.0/service/fit.py", line 730, in exportDna
    return Port.exportDna(fit)
  File "/home/intrados/Pyfa-1.3.0/service/port.py", line 621, in exportDna
    for mod in fit.modules:
  File "/home/intrados/Pyfa-1.3.0/eos/saveddata/fit.py", line 137, in modules
    return self.__modules
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 233, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 579, in get
    value = self.callable_(state, passive)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 520, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/strategies.py", line 587, in _emit_lazyload
    result = q.all()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2293, in all
    return list(self)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 65, in instances
    fetch = cursor.fetchall()
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 788, in fetchall
    self.cursor, self.context)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 782, in fetchall
    l = self.process_rows(self._fetchall_impl())
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/engine/result.py", line 749, in _fetchall_impl
    return self.cursor.fetchall()
ProgrammingError: (ProgrammingError) Cannot operate on a closed database. None None

/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py:1907: SAWarning: Attribute history events accumulated on 12 previously clean instances within inner-flush event handlers have been reset, and will not result in database updates. Consider using set_committed_value() within inner-flush event handlers to avoid this warning.
  self._flush(objects)
/usr/lib/python2.7/dist-packages/sqlalchemy/orm/session.py:1907: SAWarning: Attribute history events accumulated on 15 previously clean instances within inner-flush event handlers have been reset, and will not result in database updates. Consider using set_committed_value() within inner-flush event handlers to avoid this warning.
  self._flush(objects)
[1]    18443 segmentation fault  Pyfa-1.3.0/pyfa.py
```

**Comment by blitzmann** [comment]
I am closing this due to inactivity. I haven't sent his issue pop up recently. If problem persists, please open a new issue.
