### ISSUE TITLE
Pyfa cannot run from source on Windows 10 64-bit off the py3 branch

### ISSUE THREAD

**Issue by fsufitch** [pyfa-org/Pyfa#1509]
## Bug Report

Displaying any wxPython list or list-based controls should work. Instead, they result in a bizarre C++ error and don't render correctly. This includes market search results, drone/cargo lists, item attribute lists, etc.

### Expected behavior:

Viewing market search results, drone/cargo lists, item attribute lists, etc. works with no error.

### Actual behavior:

Viewing any of the above results in an error similar to this:

```
[2018-03-30 21:33:08.398519] CRITICAL: gui.errorDialog:

Traceback (most recent call last):
  File "C:\dev\code\Pyfa\gui\builtinAdditionPanes\commandView.py", line 170, in fitChanged
    self.update(stuff)
  File "C:\dev\code\Pyfa\gui\display.py", line 255, in update
    self.populate(stuff)
  File "C:\dev\code\Pyfa\gui\display.py", line 185, in populate
    self.InsertItem(sys.maxsize, "")
wx._core.wxAssertionError: C++ assertion "rv != -1" failed at ..\..\src\msw\listctrl.cpp(1730) in wxListCtrl::InsertItem(): failed to insert an item in wxListCtrl
```
This even happens upon launch.

### Detailed steps to reproduce:

Check out the `py3` branch, install dependencies using a virtualenv and Pip (with requirements.txt), run `pyfa.py`. The error happens on launch. 

### Release or development git branch? Please note the release version or commit hash:

083af3ebc73fef0fd7cfb19bef3962a50f5fe1ec (py3 branch)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10 64-bit

**Comment by fsufitch** [comment]
https://github.com/pyfa-org/Pyfa/pull/1510

**Comment by fsufitch** [comment]
PR was merged, closing this issue out.
