### ISSUE TITLE
Character editor deep copy error

### ISSUE THREAD

**Issue by wardhowe** [pyfa-org/Pyfa#1547]
### Expected behavior:

Copy character

### Actual behavior:

Error per below. Character is not created or copied.

    OS version: Windows-10-10.0.16299-SP0
    Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
    wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
    SQLAlchemy version: 1.1.10
    Logbook version: 1.0.0
    Requests version: 2.18.4
    Dateutil version: 2.6.0
    
    ####################
    
    Traceback (most recent call last):
      File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\entityEditor.py", line 123, in OnCopy
      File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 141, in DoCopy
      File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\character.py", line 331, in copy
      File "C:\Python36\lib\copy.py", line 161, in deepcopy
      File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\saveddata\character.py", line 277, in __deepcopy__
    AttributeError: 'Character' object has no attribute 'apiKey'

### Detailed steps to reproduce:

Pretty basic -
1. Open a fit
2. Dropdown "Character: All 5" ->
3. Open Character Editor
4. Click copy icon (tooltip "Copy Character") at upper right
5. Type a name and press enter

### Release or development git branch? Please note the release version or commit hash:

Release (beta) v2.0.0b6

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by blitzmann** [comment]
Excellent find! Will fix when I get home :)
