### ISSUE TITLE
"StaticText has been deleted" error adding character

### ISSUE THREAD

**Issue by davewiley** [pyfa-org/Pyfa#1552]
## Bug Report
The character shows up in the list so maybe the add worked anyway? 

### Detailed steps to reproduce:
Login to character on CCP website
SSO Character Management
"Add Character"
Authorize character in browser
error message appears in pyfa

**Comment by blitzmann** [comment]
When you get an error message, please copy and paste the text that comes back. It makes it much easier to track down what exactly is going on. :)

I can't reproduce myself... there's a few funky things that need to be cleaned up when it comes to login/logout events, this is probably one of them.

**Comment by trubedour** [comment]
I am getting the same message. It adds the character to the list, but none of the skills are present (unless I'm missing something I need to do to pull the skills).

**Comment by bobbyroberts99** [comment]
#### Same for me.

#### I added 5 characters using EVESSO -> Manage Characters -> Add Character and was able to fetch fits. But when I then tried to add a toon using the Character Editor it throws the following error.

```OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 799, in ssoListChanged
RuntimeError: wrapped C/C++ object of type StaticText has been deleted
```

#### So then I thought I'd revoke the characters  and try to just add them thru the Character Editor which threw the following error

```OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 799, in ssoListChanged
RuntimeError: wrapped C/C++ object of type StaticText has been deleted
```

#### The first Character worked with no errors but after that I had to go thru the following process to add a character

1. Open Character Editor
2. Click the Add Character button
3. Type in the toon's name and click OK
4. Click OK for the Character Editor window
5. Reopen the Character Editor window
6. Try to click Character pulldown to select my new toon but it doesn't appear in the list
7. Click Log in with EVE SSO button anyway
8. Authorize which throws the same error above.
9. Click OK to close the Character Editor window
10. OP SUCCESS: My new toon is syncable, shows up in the EVE SSO menu and the Character Editor pulldown. Rinse and repeat.

**Comment by blitzmann** [comment]
Thanks for the info guys! I think I have it narrowed down.

I'm probably going to be doing some fixes throughout the week to try to address some of the problems associated with this release.

Just note, I believe these errors are simply GUI errors. Essentially, once you add a character, it sends a signal to other windows telling it that a new character is available. The code that handles this signal is not properly deregistering when the window closes, so there's like a ghost window floating around that it doesn't know what to do with, hence the error. There's a quick fix I can do until I can really sit down and re-work the events surrounding the SSO management :)

**Comment by davewiley** [comment]
I agree. And what bobbyroberts99 said worked for me too.
My problem was a cancelled out of the character editor when I got the error.
Had I pressed "OK" it would have worked.

**Comment by dupreesdiamond** [comment]
>Click Refresh API button in main window to update skills

Where are you finding this button?

**Comment by blitzmann** [comment]
The "StaticText" issue has bene fixed as of 51e610830f7a777c46fc197853d38d80e799e8d7, expect a point release soon. :) thanks guys!
