### ISSUE TITLE
Crash on startup after version update

### ISSUE THREAD

**Issue by Eydorian** [pyfa-org/Pyfa#1553]
## Bug Report

I've updated from the last update version to version 2.0: copy/pasted all the files in the zip folder to my current pyfa folder, overriding existing files. Then I start the program and I get the error below. I tried to restart windows, same behavior.

### Expected behavior:
Start program

### Actual behavior:
Crash with pyfa error window opening

### Detailed steps to reproduce:
Copy/pasted all the files in the zip folder to my current pyfa folder, overriding existing files
Start the program -> crash

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
pyfa-2.0.0-yc120.3-1.8-win.zip

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 7

### Other relevant information:

OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 135, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 166, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 65, in getBitmap
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 87, in getImage
TypeError: initial_value must be str or None, not bytes

**Comment by Vatierville** [comment]
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 135, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 166, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 65, in getBitmap
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 87, in getImage
TypeError: initial_value must be str or None, not bytes

R6034
An application has made an attempt to load the C runtime library correctly

**Comment by blitzmann** [comment]
> copy/pasted all the files in the zip folder to my current pyfa folder

This might be where you went wrong. 2.0 uses a different build process, you probably can't just copy/paste over 1.x and expect it to work. I would recommend removing the pyfa directory completely, or extracting the 2.0 version to it's own pristine directory somewhere.

Try this and please let me know if it works. :)

**Comment by Eydorian** [comment]
Renaming the old pyfa directory "pyfa_old" and copying the new 2.0 directory at the previous location works well. Thanks!

**Comment by blitzmann** [comment]
No problem! Also, heads up, will be releasing a point release tonight hopefully that includes an installer that should take care of this issue automatically!

**Comment by blitzmann** [comment]
The new point release is out with the new installer :)

**Comment by mayumi7** [comment]
I had a previous installation from pyfa-1.36.0-yc120.3-1.8-win.exe and let the current pyfa-2.0.2-yc120.3-1.8-win.exe installer do it's job and I'm now getting this error.

OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 135, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 167, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 65, in getBitmap
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 87, in getImage
TypeError: initial_value must be str or None, not bytes

**Comment by blitzmann** [comment]
> It did run the uninstaller automatically, just noticed that there were still files left over in the folder. 

Yeah, that's weird. ¯\_(ツ)_/¯ Any major version bump is bound to have small issues like this though, thankfully it's only a small subset of users
