### ISSUE TITLE
EVE SSO: UnicodeDecodeError on server start up

### ISSUE THREAD

**Issue by RootFather** [pyfa-org/Pyfa#1560]
After clicking the "add character" button in the EVE SSO > Manage Characters tab, an error message appears.

OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 329, in addChar
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 210, in login
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 244, in startServer
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 110, in server_bind
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 329, in addChar
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 210, in login
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 244, in startServer
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 110, in server_bind
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 329, in addChar
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 210, in login
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 244, in startServer
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 110, in server_bind
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 329, in addChar
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 210, in login
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 244, in startServer
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 110, in server_bind
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 329, in addChar
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 210, in login
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 244, in startServer
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 110, in server_bind
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

[1.txt](https://github.com/pyfa-org/Pyfa/files/1991425/1.txt)

**Comment by blitzmann** [comment]
Thanks for the error report!

I'm not exactly sure what is going on here, but I've reworked a lot of the ESI functionality and will be releasing a new point release tonight, I'm hoping that will solve the issue. Please watch for this release and let me know if you are still having issues after installing it. :)

**Comment by blitzmann** [comment]
@sincomil I'm getting a few errors on the server regarding missing data every now and then. Can you try again and see if the issue is still present? 

The pyfa.io site also requires the use of session data. I am not immediately sure if that means it requires the use of cookies, but if you have cookies disabled, that might be the cause?

**Comment by sincomil** [comment]
I have tried this to do with many browsers: Firefox / Chromium / Falkon none of them get the expected result, and cookies are not disabled

**Comment by RootFather** [comment]
Unfortunately the problem remains.

### ####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 784, in addCharacter
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 111, in login
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 129, in startServer
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 110, in server_bind
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

**Comment by blitzmann** [comment]
@RootFather I'm not sure, I'll have to dig deeper. I can't personally reproduce the issue >.<

Is your OS in English, or some other language? This is a unicode decode error for... serverbind? there's no text there, and the error is happening inside python's package... so IDFK. The way it's supposed to work is that pyfa starts a small local server on `localhost:<randomport>` to listen for the callback that SSO does (or, rather, pyfa). That server startup is what's dying.

Would it be okay if I give you a sample application that's basically a button that starts a server? If that fails, then that's a very simple application that I can then take and ask some folks on why it's not working. 

**As a workaround: ** Preferences > EVE SSO > Login Method > Manual. Instead of having a server spin up to accept a request for sso information, this will prompt you for some text that pyfa.io will give you, which will at least allow you to add a character. From there it should work normally. Let me know!

@sincomil Can you open a separate issue for your issue please? I may also want to get with you personally if you don't mind - send me an email at sable.blitzmann@gmail.com and we can take it from there. The server seems to be dying on your requests, so I'll probably have you do some troubleshooting. What is your TZ?

**Comment by RootFather** [comment]
No, it's Russian version of Windows. I did as you wrote, but again there was an error. My default browser (google chrome) faild to open pyfa.io Browser Thor opened, but still cant add my char. Anyway,thanks for your help!

OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 331, in addChar
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 111, in login
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 129, in startServer
  File "C:\Python36\lib\socketserver.py", line 453, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 110, in server_bind
  File "C:\Python36\lib\http\server.py", line 138, in server_bind
  File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connection.py", line 326, in connect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
  File "C:\Python36\lib\ssl.py", line 401, in wrap_socket
  File "C:\Python36\lib\ssl.py", line 808, in __init__
  File "C:\Python36\lib\ssl.py", line 1061, in do_handshake
  File "C:\Python36\lib\ssl.py", line 683, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\adapters.py", line 440, in send
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\retry.py", line 357, in increment
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connection.py", line 326, in connect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
  File "C:\Python36\lib\ssl.py", line 401, in wrap_socket
  File "C:\Python36\lib\ssl.py", line 808, in __init__
  File "C:\Python36\lib\ssl.py", line 1061, in do_handshake
  File "C:\Python36\lib\ssl.py", line 683, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 250, in ShowSsoLogin
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 150, in handleLogin
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\sessions.py", line 521, in get
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\sessions.py", line 508, in request
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\sessions.py", line 618, in send
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\adapters.py", line 490, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

**Comment by blitzmann** [comment]
@RootFather thanks for the additional information, I'll have to dig deeper. Will update as soon as I know more

**Comment by blitzmann** [comment]
Listing this as high priority as it effectively make character skills stuff useless... :/

I've got another high priority bug that takes precedence over this one, but that's hopefully fixed and just awaiting verification.

**Comment by sincomil** [comment]
I have created new issue for my case: https://github.com/pyfa-org/Pyfa/issues/1587

**Comment by blitzmann** [comment]
Thanks @sincomil

**Comment by blitzmann** [comment]
@RootFather I have a feeling that this is a bug with Python itself. Can you please post the hostname of your machine here. You can find this by going to Right click This PC > Properties > Computer Name [...] heading > Change Settings > Computer Name tab > "Change" > And there should be a box with the computer name in it... please post it here. I've tried some Russian characters myself with no success at reproducing, but maybe it takes certain characters to kill it?

I think I'll also get a test application for you to run to see if even the simplest server, without pyfa's fluff, also fails

**Comment by RootFather** [comment]
If I understood you correctly then that's the name: WIN-RQIHHG1T12Q

I tried your new build with autologin. I could go to the authorization page, but then a message appeared: Something went wrong :-(
This website is hosted by PythonAnywhere, an online hosting environment. Something went wrong while trying to load it; please try again later.

**Comment by blitzmann** [comment]
@RootFather I implemented a fix for #1587 that apparently broke the login procedure for some folks :/ I've reverted back... The fact that you got through to the login is good information though.

Can you try to log in again?

(also, that machine name doesn't seem odd at all, so I'm not sure why it's breaking on `socket.getfqdn()`...)

**Comment by RootFather** [comment]
I was able to add a character. But my skills were not added. 

If you see this message then it means you should be logged into EVE SSO. You may close this window and return to the application.

**Comment by blitzmann** [comment]
> I was able to add a character. But my skills were not added.

\o/

Skills don't get automatically added (yet). You have to fetch them manually. Select the SSO character for your pyfa character, then open up a fit with that pyfa character, and hit the little refresh icon

![image](https://user-images.githubusercontent.com/3904767/40247470-7af388ac-5a9a-11e8-8802-3b93769302a3.png)

I'll be working on a way to automatically fetch the skills on login, or at least have a button in the character editor to fetch skills, as the current implementation is confusing.

**Comment by RootFather** [comment]
I'm glad that you managed to fix the application. I hope that my participation was useful in solving this problem. Thank you!

**Comment by blitzmann** [comment]
@RootFather I assume that you got the skills up and running now?

I'm still concerned about the other issue that you had when switching to manual mode... Can you try again and see if that still happens?

**Comment by RootFather** [comment]
Yes. In manual mode problem appears again. When I got back to the automatic mode, it worked.

**Comment by blitzmann** [comment]
Hrm, doesn't really make sense. It's breaking on this bit: 

https://github.com/pyfa-org/Pyfa/blob/master/service/esi.py#L148

But that happens regardless if it's manual or auto... @_@

Think I'm gonna mark this one as solved and open up another ticket with that specific problem.

**Comment by WatchMeCalculate** [comment]
@rootFather could you please open up a python interpreter and print the output of the following command?
```
>>> import ssl
>>> ssl.OPENSSL_VERSION
```

**Comment by feyyd** [comment]
Not sure if this is helpful, but I see its failing on retrieving access_token from session, as pointed out by blitz.  https://github.com/pyfa-org/Pyfa/blob/master/service/esi.py#L148  

When I was doing work with manual logins the access_token was stored in fragment data (which isn't retrievable from session).  The workaround I did was to send them to a page that had javascript that extracted fragment data, then redirected them with the access_token in the query string.

heres the page i landed my user on, after it redirects, access_token is accessible from session, hope this helps.
`

                string rs = "<!DOCTYPE html>\n";
                rs += "<html>\n";
                rs += "<body>\n";
                rs += "<h2>Redirecting</h2>\n";
                rs += "<script>\n";
                rs += "function getHash() {\n";//extract fragment data
                rs += "if (window.location.hash) {\n";
                rs += "var hash = window.location.hash.substring(1);\n";//fragment containing access_token
                rs += "if (hash.length === 0) {\n";
                rs += "return false;\n";
                rs += "} else {\n";
                rs += "return hash;}\n";
                rs += "} else {\n";
                rs += "return false;}}\n";
                rs += "var hash = getHash();\n";
                rs += "var parts = hash.split('=');\n";
                rs += "window.location.replace( \"http://localhost:9524/undercutcheck/?access_token=\" + parts[1] );\n";//redirect with access_token in query string
                rs += "</script>\n";
                rs += "</body>\n";
                rs += "</html>\n";
`
