### ISSUE TITLE
2.0 start up Error

### ISSUE THREAD

**Issue by demonwolf1994** [pyfa-org/Pyfa#1568]
### Detailed steps to reproduce:
starting pyfa

### Other relevant information:
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 135, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 166, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 65, in getBitmap
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 87, in getImage
TypeError: initial_value must be str or None, not bytes

**Comment by Fundaris** [comment]
look at #1553

**Comment by blitzmann** [comment]
Indeed, duplicate. Please check that issue for a workaround (or wait until the next point release, which will have an installer to deal with this)
