### ISSUE TITLE
Cannot drag fit from list to tab

### ISSUE THREAD

**Issue by jasconius** [pyfa-org/Pyfa#1569]
## Bug Report

You cannot drag a fit from the fit list to the tab area to create a new tab

### Expected behavior:

Drag fit to tab area, get new tab, just like in 1.x

### Actual behavior:

A runtime exception is generated and error window is shown, no tab created.

### Detailed steps to reproduce:

Go to a hull, drag a fit not already open to the tab area

### Release or development git branch? Please note the release version or commit hash:

2.0 Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

### Other relevant information:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 339, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 400, in MouseLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 91, in handleDrag
AttributeError: 'MultiSwitch' object has no attribute 'pages'

**Comment by blitzmann** [comment]
Thanks for the bug report! Taking a look into this now :)

**Comment by blitzmann** [comment]
Fixed!
