### ISSUE TITLE
Error EVE SSO

### ISSUE THREAD

**Issue by desmosedici** [pyfa-org/Pyfa#1572]
I try Character editor -> EVE SSO -> Log in with EVE SSO but show this message:

OS version: Darwin-15.6.0-x86_64-i386-64bit
Python version: 3.6.3 (default, Oct 22 2017, 22:24:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/esiFittings.py", line 329, in addChar
  File "/Users/ryan/pyfa/service/esi.py", line 209, in login
AttributeError: 'Esi' object has no attribute 'settings'

**Comment by seraphx2** [comment]
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 329, in addChar
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 209, in login
AttributeError: 'Esi' object has no attribute 'settings'

**Comment by RovSpada** [comment]
I believe that is a hardcoded user directory where it should be writing to our own. That is most likely the username profile on his PC where he did the compilation. I'm also having this, and can't import character info. Or can't get it to work. Same error

**Comment by seraphx2** [comment]
yes. that's what it is. it was sarcasm since there is a good chance it shouldn't be there
