### ISSUE TITLE
Pyfa not starting

### ISSUE THREAD

**Issue by NielsBattle** [pyfa-org/Pyfa#1582]
## Bug Report
Everytime I update my pyfa and start it up it keeps giving C library errors.
https://i.imgur.com/f4YSbmt.png

I also get this pop-up 4 times in a row when I press OK.

### Expected behavior:
Just starting pyfa.

### Actual behavior:
Giving errors about not able to load the C library

### Detailed steps to reproduce:
Not sure. I just started pyfa using pyfa after I updated it.
(Note: I even uninstalled the old pyfa's and then reinstalled the new version using the .exe installer.)

### Fits involved in EFT format (Edit > To Clipboard > EFT):
None

### Release or development git branch? Please note the release version or commit hash:
pyfa v2.0.1 
Source: https://github.com/pyfa-org/Pyfa/releases/tag/v2.0.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 8.1

### Other relevant information:
OS version: Windows-8.1-6.3.9600-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 135, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 167, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 65, in getBitmap
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 87, in getImage
TypeError: initial_value must be str or None, not bytes

(Note: this was the second error I got after I closed the four pop-up windows mentioned before.)

**Comment by NielsBattle** [comment]
Yep that totally fixed it thank you so much. Maybe I should start reading patchnotes xd.
