### ISSUE TITLE
pyfa 2.x Exception during "Browse EVE Fittings" (patch)

### ISSUE THREAD

**Issue by minlexx** [pyfa-org/Pyfa#1583]
I've found a funny error:
```
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.7
Logbook version: 1.3.3
Requests version: 2.18.4
Dateutil version: 2.7.2
```

```
Traceback (most recent call last):
  File "V:\dev\python\Pyfa\gui\esiFittings.py", line 126, in fetchFittings
    raise ex
  File "V:\dev\python\Pyfa\gui\esiFittings.py", line 114, in fetchFittings
    self.fitTree.populateSkillTree(self.fittings)
  File "V:\dev\python\Pyfa\gui\esiFittings.py", line 372, in populateSkillTree
    if ship.name not in dict:
AttributeError: 'NoneType' object has no attribute 'name'
```

It happens with only one character of all my four, the oldest one.
What is so funny here, you ask. I actually found the cause of it: ship returned by `ship = getItem(fit['ship_type_id'])` is actually a `None`, so I added some debug code and found out this: 

![Screenshot](https://i.imgur.com/LaUIKhJ.png)

Somehow I have a fit for non-existent ship in the game, Jove Battleship called Eidolon:
![Eidolon](https://i.imgur.com/xsZk7xI.jpg)

This fit is not even shown ingame, but apparently somehow is returned by ESI API.
P.S. ![InGame](https://i.imgur.com/esBB2Z3.png)

**Comment by minlexx** [comment]
Aand a patch:

```diff
$ git diff
diff --git a/gui/esiFittings.py b/gui/esiFittings.py
index c044ad54..ca04387e 100644
--- a/gui/esiFittings.py
+++ b/gui/esiFittings.py
@@ -366,6 +366,9 @@ class FittingsTreeView(wx.Panel):
             if (fit['fitting_id'] in sEsi.fittings_deleted):
                 continue
             ship = getItem(fit['ship_type_id'])
+            if ship is None:
+                pyfalog.debug('Cannot find ship type id: {}'.format(fit['ship_type_id']))
+                continue
             if ship.name not in dict:
                 dict[ship.name] = []
             dict[ship.name].append(fit)
```

With this fits for unknown types will be skipped.
