### ISSUE TITLE
SSO Manual Login Method: connection reset error

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1592]
See #1560 for more discussion on this. I can't reproduce myself.

```
Traceback (most recent call last):
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 850, in validate_conn
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connection.py", line 326, in connect
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\ssl.py", line 329, in ssl_wrap_socket
File "C:\Python36\lib\ssl.py", line 401, in wrap_socket
File "C:\Python36\lib\ssl.py", line 808, in init
File "C:\Python36\lib\ssl.py", line 1061, in do_handshake
File "C:\Python36\lib\ssl.py", line 683, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\adapters.py", line 440, in send
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\retry.py", line 357, in increment
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 850, in validate_conn
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connection.py", line 326, in connect
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\ssl.py", line 329, in ssl_wrap_socket
File "C:\Python36\lib\ssl.py", line 401, in wrap_socket
File "C:\Python36\lib\ssl.py", line 808, in init
File "C:\Python36\lib\ssl.py", line 1061, in do_handshake
File "C:\Python36\lib\ssl.py", line 683, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 250, in ShowSsoLogin
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 150, in handleLogin
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\sessions.py", line 521, in get
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\sessions.py", line 508, in request
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\sessions.py", line 618, in send
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\adapters.py", line 490, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))
```

**Comment by WatchMeCalculate** [comment]
So i'm fairly certain the issue here is that the user environment probably caused this issue. `Connection Reset Win Error(10054) "Connection forcibly closed by remote host"`  Usually means that there was an incompatibility in protocol being spoken between client/server...  Searching around I found a [Python3.3 bug](https://bugs.python.org/issue16361) which seems to support this hypothesis (that something funky was up with the user environment) Asking original poster in #1560 to confirm openssl lib version. 

In requests documentation
> The Requests team has made a specific choice to use whatever SSL version is default in the underlying library (urllib3)

It's hard to test this one but one workaround suggested in the python bug was to force a ssl protocol version. [Requests has a way to do this](http://docs.python-requests.org/en/master/user/advanced/#example-specific-ssl-version), modifying their example, we could do something like the following. Might be better in general as we wouldn't rely on the default as libraries change underneath us.
```
import ssl
from urllib3.poolmanager import PoolManager

from requests.adapters import HTTPAdapter


class TLSv1_2HttpAdapter(HTTPAdapter):
    """"Transport adapter" that allows us to use TLSv1_2."""

    def init_poolmanager(self, connections, maxsize, block=False):
        self.poolmanager = PoolManager(
            num_pools=connections, maxsize=maxsize,
            block=block, ssl_version=ssl.PROTOCOL_TLSv1_2)
```
Then in [esiAcces](https://github.com/pyfa-org/Pyfa/blob/master/service/esiAccess.py#L81) we explicitly force it to use the same protocol as esi on https requests
```
  # session request stuff
  self._session = Session()
  self._session.mount('https://',TLSv1_2HttpAdapter())
  self._session.headers.update({
...
```
I already tested it with all the various operations in Pyfa and as expected nothing was different.

**Comment by blitzmann** [comment]
If that was the case wouldn't all requests break? It's kind of weird how it only happens on the manual mode token verification step... (which happens with the automatic mode too IIRC, but it was reported to work with that).

We can always get a test build working with this and ask @RootFather to test to see if it works for them. :)

**Comment by WatchMeCalculate** [comment]
Yeah i was thinking about that, that would be the case. I was looking into #1560 more and what's interesting is
```
Traceback (most recent call last):
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 331, in addChar
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 111, in login
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 129, in startServer
File "C:\Python36\lib\socketserver.py", line 453, in init
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\server.py", line 110, in server_bind
File "C:\Python36\lib\http\server.py", line 138, in server_bind
File "C:\Python36\lib\socket.py", line 673, in getfqdn
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 6: invalid continuation byte

####################

Traceback (most recent call last):
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 850, in validate_conn
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connection.py", line 326, in connect
File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\ssl.py", line 329, in ssl_wrap_socket
File "C:\Python36\lib\ssl.py", line 401, in wrap_socket
File "C:\Python36\lib\ssl.py", line 808, in init
File "C:\Python36\lib\ssl.py", line 1061, in do_handshake
File "C:\Python36\lib\ssl.py", line 683, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение```

For the failure in #1560 is there a point between server_bind and getfqdn where it could accept connections? Might be the case that WinError 10054 was just a consequence of the #1560 and now we won't see WinError 10054 now... @RootFather have you seen any esi errors in a recent release?

**Comment by blitzmann** [comment]
The original issue (unicode decode error) was fixed, and @RootFather confirmed that it was fixed, but was still having the issue with manual mode (although maybe something was left to interpretation?) So I don't immediately think they are related. Would be good to have clarification from @rootfather if this is still happening with v2.1.1
