### ISSUE TITLE
Migration scripts broken for old databases in 2.x

### ISSUE THREAD

**Issue by half-apple** [pyfa-org/Pyfa#1595]
```OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlite3.OperationalError: no such table: crest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\migrations\upgrade22.py", line 37, in upgrade
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2064, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 939, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1097, in _execute_text
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: crest [SQL: 'SELECT created FROM crest LIMIT 1;']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlite3.OperationalError: no such table: crest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 120, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\prefetch.py", line 40, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\migration.py", line 41, in update
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\migrations\upgrade22.py", line 39, in upgrade
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2064, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 939, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1097, in _execute_text
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: crest [SQL: 'ALTER TABLE crest ADD COLUMN created DATETIME;']
```

**Comment by blitzmann** [comment]
Hrm, interesting.

Can you please zip up your `%userprofile%/.pyfa` directory and send it directly to me at sable.blitzmann@gmail.com? It looks like ma database issue. Have you been keeping up with the versions, or are you coming back after some time off?

**Comment by blitzmann** [comment]
I assume that was you that emailed me, thanks! 

Indeed, it looks like this is an extremely old database - back before we started tracking database versions from what I can tell. The problem lies in the fact that we have a migration revolving around the CREST table, which no longer exists in the latest version, but it's still expecting it in the migration. For users that kept up with the versions, this is not really a problem, but for people with older (very old) databases, this is a problem. This is something I will have to fix. In the meantime, there are 3 options, please choose which one best fits your needs:

* Recommended: It looks like your original database only contains one fit, where you used the beta builds and have 10 fits. If you don't care about that one fit (which is probably very very old), and want to use the fits that you were working on in the beta version, simply rename `saveddata-py3-dev.db` to `saveddata.db` (and remove the current one).
* Delete `saveddata.db` - this will allow pyfa to generate a new database file from scratch
* (not sure if this will work) Download and run the latest 1.x version (https://github.com/pyfa-org/Pyfa/releases/tag/v1.37.0). This should update the database properly, and then you should be able to run 2.x...

**Comment by blitzmann** [comment]
I've also fixed this in f9e60a0 for future people having this problem

**Comment by half-apple** [comment]
I've fixed this problem by your help,thanks!

**Comment by blitzmann** [comment]
No problem, sorry you had a bit of trouble, but glad it's worked out!
