### ISSUE TITLE
v2.0.2 Windows no start "sqlite3.OperationalError: no such table: crest"

### ISSUE THREAD

**Issue by dennisnliao** [pyfa-org/Pyfa#1600]
## Bug Report
Application crashes when I try to start it. Reports a traceback with error "sqlite3.OperationalError: no such table: crest"

### Expected behavior:
Application starts.

### Actual behavior:
Application crashes with traceback.

### Detailed steps to reproduce:
Install version 2.0.2 to windows using either MSI installer or zip method. Double click pyfa.exe.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlite3.OperationalError: no such table: crest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\migrations\upgrade22.py", line 37, in upgrade
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2064, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 939, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1097, in _execute_text
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: crest [SQL: 'SELECT created FROM crest LIMIT 1;']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlite3.OperationalError: no such table: crest

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 120, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\prefetch.py", line 40, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\migration.py", line 41, in update
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\migrations\upgrade22.py", line 39, in upgrade
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2064, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 939, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1097, in _execute_text
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: crest [SQL: 'ALTER TABLE crest ADD COLUMN created DATETIME;']

**Comment by blitzmann** [comment]
Duplicate of #1595, but just to continue here...

Can you please zip up your %userprofile%/.pyfa directory and send it directly to me at sable.blitzmann@gmail.com? It looks like a database issue. Have you been keeping up with the versions, or are you coming back after some time off?

**Comment by blitzmann** [comment]
@dennisnliao any update? Want to make sure I get your database back up and running soon!

**Comment by blitzmann** [comment]
So you have the same options as the other thread:

* download 1.37 and run it once to get it up to date
* remove the database file (all those fits are probably trash by now, TBH, lots of changes in those 3 years :P)

**Comment by blitzmann** [comment]
I've also fixed this in f9e60a00f2f528e6f7839613f72dfc9714a64f61 for future people having this problem
