### ISSUE TITLE
Crash when attempting a char import on OSX version

### ISSUE THREAD

**Issue by cliveflint** [pyfa-org/Pyfa#1627]
## Bug Report
Character import on OSX version fails when pressing the Add Character button

### Expected behavior:
Not done it before but I expect it should allow me to import a character

### Actual behavior:
OS version: Darwin-17.5.0-x86_64-i386-64bit
Python version: 3.6.3 (default, Oct 22 2017, 22:24:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/characterEditor.py", line 800, in addCharacter
  File "/Users/ryan/pyfa/service/esi.py", line 111, in login
  File "/Users/ryan/pyfa/service/esi.py", line 129, in startServer
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 453, in __init__
  File "/Users/ryan/pyfa/service/server.py", line 113, in server_bind
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 467, in server_bind
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/esiFittings.py", line 331, in addChar
  File "/Users/ryan/pyfa/service/esi.py", line 111, in login
  File "/Users/ryan/pyfa/service/esi.py", line 129, in startServer
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 453, in __init__
  File "/Users/ryan/pyfa/service/server.py", line 113, in server_bind
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 467, in server_bind
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/esiFittings.py", line 331, in addChar
  File "/Users/ryan/pyfa/service/esi.py", line 111, in login
  File "/Users/ryan/pyfa/service/esi.py", line 129, in startServer
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 453, in __init__
  File "/Users/ryan/pyfa/service/server.py", line 113, in server_bind
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 467, in server_bind
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/esiFittings.py", line 331, in addChar
  File "/Users/ryan/pyfa/service/esi.py", line 111, in login
  File "/Users/ryan/pyfa/service/esi.py", line 129, in startServer
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 453, in __init__
  File "/Users/ryan/pyfa/service/server.py", line 113, in server_bind
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socketserver.py", line 467, in server_bind
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

### Detailed steps to reproduce:
Click button

### Fits involved in EFT format (Edit > To Clipboard > EFT):
na

### Release or development git branch? Please note the release version or commit hash:
release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
OSX 10.13.4

**Comment by blitzmann** [comment]
Yeah, also not able to reproduce.

Someone else was getting an error in `server_bind`, and I think it had something to do with their locality. Are you on an English mac, Russian mac, etc?

As a workaround, you can use the "Manual" method - got to preferences > EVE SSO > Login Authentication Method = "Manual"

Instead of pyfa starting up a server, which is what's breaking, it will prompt you to copy and paste text that you will receive when you log into the EVE SSO.

**Comment by cliveflint** [comment]
My hosts only has entries for OpenVPN Client Sites

**Comment by cliveflint** [comment]
The workaround worked. Cheers.

I have UK English mac if that helps.

**Comment by blitzmann** [comment]
Should really throw a user-friendly message if the server fails letting user know they can use the manual version. And log the real error to a log. hrm...

**Comment by WatchMeCalculate** [comment]
Something like this? 
![server_error](https://user-images.githubusercontent.com/1071826/40880528-8bf746c4-6667-11e8-938f-9c83a64e9fd5.PNG)

**Comment by blitzmann** [comment]
@WatchMeCalculate yes, that would be amazing. Would you be able to send in a pull request for that? The only thing that might actually be problematic is the fact that the server is started in another thread, so I'm not sure we could catch this exception (well, we could catch it in the separate thread and then send it through a callback or something).

**Comment by WatchMeCalculate** [comment]
Yeah I’ll try some different failure points to ensure it catches them and submit one later tonight.
