### ISSUE TITLE
Hard crash when abyssal attributes are changed and window is closed before FitChanged event is posted

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1650]
It has to do with this line:

` self.timer = wx.CallLater(1000, self.callLater)`

What this does is call the `callLater()` method on the mutator panel, which is supposed to send an event to MainFrame to recalc the fit. I assume that when the time comes, and the callback is called, it doesn't know how to handle it since the window was closed.

I'll have to post a support ticket to Phoenix to log the bug, and figure out a better way to do this.

**Comment by blitzmann** [comment]
Turns our we were Destroying the item stats, which doesn't necessarily clean up any events that it's attached to. However, there are still a few problems with using the shortcuts to open stats in same window vs separate, still need to work out the kinks.

```
Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 150, in closeEvent
    self.parentWnd.UnregisterStatsWindow(self)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 333, in UnregisterStatsWindow
    self.statsWnds.remove(wnd)
ValueError: list.remove(x): x not in list
```
