### ISSUE TITLE
'FittingView' object has no attribute 'FVsnapshot'

### ISSUE THREAD

**Issue by fsufitch** [pyfa-org/Pyfa#1653]
## Bug Report

A recurring error happens when looking at a couple fits in Pyfa. There is no clear specific action in the UI that causes it, but general interaction (clicking around, switching tabs, etc) seems to cause it

### Expected behavior:

No errors.

### Actual behavior:

```
Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\chrome_tabs.py", line 1292, in OnTimer
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 724, in Snapshot
AttributeError: 'FittingView' object has no attribute 'FVsnapshot'
```

### Detailed steps to reproduce:

Open the fits and click around the UI, especially involving the tabs.

### Fits involved in EFT format (Edit > To Clipboard > EFT):

```
[Naga, Snek]

Magnetic Field Stabilizer II
Magnetic Field Stabilizer II
Magnetic Field Stabilizer II

50MN Y-T8 Compact Microwarpdrive
Medium Micro Jump Drive
Tracking Computer II
Tracking Computer II
Sensor Booster II
Sensor Booster II

425mm Railgun II, Federation Navy Antimatter Charge L
425mm Railgun II, Federation Navy Antimatter Charge L
425mm Railgun II, Federation Navy Antimatter Charge L
425mm Railgun II, Federation Navy Antimatter Charge L
425mm Railgun II, Federation Navy Antimatter Charge L
425mm Railgun II, Federation Navy Antimatter Charge L
425mm Railgun II, Federation Navy Antimatter Charge L
425mm Railgun II, Federation Navy Antimatter Charge L

Medium Ancillary Current Router I
Medium Polycarbon Engine Housing I
Medium Polycarbon Engine Housing I


Javelin L x600
Spike L x600
Caldari Navy Antimatter Charge L x600
Caldari Navy Uranium Charge L x500
Caldari Navy Iron Charge L x600
Optimal Range Script x2
Tracking Speed Script x2
Targeting Range Script x2
Scan Resolution Script x2
```

```
[Oracle, S-TN Mk.II 'Phoenix']

Fourier Compact Tracking Enhancer
Nanofiber Internal Structure II
Heat Sink II
Heat Sink II
Heat Sink II
Tracking Enhancer II

50MN Cold-Gas Enduring Microwarpdrive
Tracking Computer II, Tracking Speed Script
Tracking Computer II, Tracking Speed Script

Tachyon Beam Laser II, Imperial Navy Xray L
Tachyon Beam Laser II, Imperial Navy Xray L
Tachyon Beam Laser II, Imperial Navy Xray L
Tachyon Beam Laser II, Imperial Navy Xray L
Tachyon Beam Laser II, Imperial Navy Xray L
Tachyon Beam Laser II, Imperial Navy Xray L
Tachyon Beam Laser II, Imperial Navy Xray L
Tachyon Beam Laser II, Imperial Navy Xray L

Medium Energy Locus Coordinator I
Medium Ionic Field Projector I
Medium Polycarbon Engine Housing I


Gleam L x8
Imperial Navy Multifrequency L x8
Imperial Navy Xray L x8
Imperial Navy Standard L x8
Optimal Range Script x2
Tracking Speed Script x2
```

### Release or development git branch? Please note the release version or commit hash:

Release version 2.1.1, EVE Data Version 1321734 (2018-05-30 19:28:25)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

```
OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0
```

### Other relevant information:

N/A

**Comment by fsufitch** [comment]
Never mind, seems like a duplicate of https://github.com/pyfa-org/Pyfa/issues/1633
