### ISSUE TITLE
Unable to open assault damage control stats window

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1659]
1. Search for assault damage control II in market (in current pyfa git)
2. Open stats window

No window is opened, error is generated instead:
```
OS version: Linux-4.16.0-1-amd64-x86_64-with-debian-buster-sid
Python version: 3.6.6rc1 (default, Jun 13 2018, 06:59:48) 
[GCC 8.1.0]
wxPython version: 4.0.1 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.8
Logbook version: 1.3.3
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "/home/dfx/src/eve/pyfa/gui/contextMenu.py", line 138, in handler
    menuHandler.activate(context, selection, i)
  File "/home/dfx/src/eve/pyfa/gui/builtinContextMenus/itemStats.py", line 69, in activate
    ItemStatsDialog(stuff, fullContext)
  File "/home/dfx/src/eve/pyfa/gui/itemStats.py", line 99, in __init__
    self.container = ItemStatsContainer(self, victim, item, itmContext)
  File "/home/dfx/src/eve/pyfa/gui/itemStats.py", line 174, in __init__
    self.params = ItemParams(self.nbContainer, stuff, item, context)
  File "/home/dfx/src/eve/pyfa/gui/builtinItemStatsViews/itemAttributes.py", line 52, in __init__
    self.PopulateList()
  File "/home/dfx/src/eve/pyfa/gui/builtinItemStatsViews/itemAttributes.py", line 217, in PopulateList
    valueUnit = self.FormatValue(*info.unit.TranslateValue(value))
  File "/home/dfx/src/eve/pyfa/eos/gamedata.py", line 638, in TranslateValue
    return override[0](value), override[2](self.displayName)
TypeError: <lambda>() missing 1 required positional argument: 'u'
```

**Comment by MaruMaruOO** [comment]
#1664 should fix this.
In practice this mostly impacts items with the "Cannot Auto Repeat" attribute.
