### ISSUE TITLE
sql integrity error when importing a fit from EVE

### ISSUE THREAD

**Issue by adrian17** [pyfa-org/Pyfa#1674]
Trying to import any fit for my character causes an exception.

Steps:
- made a clean 2.3.0 reinstall (uninstalled and removed all pyfa-related files skipped by the uninstaller, then installed)
- added my account with SSO
- tried to import a fit with "Browse EVE Fittings" menu

```
OS version: Windows-7-6.1.7601-SP1
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlite3.IntegrityError: NOT NULL constraint failed: fits.implantLocation

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 544, in commit
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 906, in commit
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 461, in commit
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 441, in _prepare_impl
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2171, in flush
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2291, in _flush
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2255, in _flush
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 389, in execute
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 548, in execute
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 835, in _emit_insert_statements
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: fits.implantLocation [SQL: 'INSERT INTO fits ("ownerID", "shipID", name, timestamp, "characterID", "damagePatternID", booster, "targetResistsID", "modeID", "implantLocation", notes, "ignoreRestrictions", created, modified) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'] [parameters: (None, 17843, '*VNI', 1531729525.0795536, 1, 1, 0, None, None, None, '', 0, '2018-07-16 10:25:26.235803', '2018-07-16 10:25:26.235803')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 134, in importFitting
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\service\port.py", line 340, in importFitFromBuffer
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 531, in save
  File "C:\Users\USER\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 549, in commit
TypeError: __init__() missing 2 required positional arguments: 'params' and 'orig'
```

**Comment by AleksandrZhurba** [comment]
and also fit's doesn't import from Clipboard without any reactions or erros

**Comment by MaruMaruOO** [comment]
This bug is on me. I didn't think service.port would duplicate bits of fit initialization code and should've checked to be sure.
Either way this should be fixed with #1675.

**Comment by blitzmann** [comment]
Eh, shit happens. I approved it and didn't think to check importing either. There's always something that is unintentionally affected lol

Thanks for the quick fix @MaruMaruOO ! Will be making a point release in the next day or so that includes the fix

**Comment by AleksandrZhurba** [comment]
Import from clipboard don't work correctly. Don't grab implants
