### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Errious** [pyfa-org/Pyfa#1680]
Hi guys,

today i got this ERROR when trying to use an abyssal large capacitor battery from an thurifier large cap battery:

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\contextMenu.py", line 138, in handler
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\itemStats.py", line 69, in activate
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 99, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 168, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemMutator.py", line 73, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 52, in getStaticBitmap
TypeError: StaticBitmap.SetBitmap(): argument 1 has unexpected type 'NoneType'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\contextMenu.py", line 138, in handler
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\itemStats.py", line 69, in activate
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 99, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 168, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemMutator.py", line 73, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 52, in getStaticBitmap
TypeError: StaticBitmap.SetBitmap(): argument 1 has unexpected type 'NoneType'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\contextMenu.py", line 138, in handler
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\itemStats.py", line 69, in activate
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 99, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 168, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemMutator.py", line 73, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\bitmap_loader.py", line 52, in getStaticBitmap
TypeError: StaticBitmap.SetBitmap(): argument 1 has unexpected type 'NoneType'

**Comment by blitzmann** [comment]
Duplicate #1673
