### ISSUE TITLE
2.3.1 is missing all the boosters like standard exile and blue pill from the implants & boosters section.

### ISSUE THREAD

**Issue by taltracyn** [pyfa-org/Pyfa#1683]

**Comment by blitzmann** [comment]
Huh... 

You can search these boosters directly, but attempting to right-click> show market group produces this error:

```OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\contextMenu.py", line 138, in handler
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\marketJump.py", line 51, in activate
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\marketBrowser.py", line 100, in jump
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinMarketBrowser\marketTree.py", line 92, in jump
wx._core.wxAssertionError: C++ assertion "item.IsOk()" failed at ..\..\src\msw\treectrl.cpp(1032) in wxTreeCtrl::GetItemParam(): invalid tree item
```

Seems like it could be an issue with the underlying data, almost like these were removed from the market tree somehow. Will check when I get home :)

**Comment by taltracyn** [comment]
no its just 2.3.1

**Comment by blitzmann** [comment]
Eh, it's also an issue in 2.3.0. I'll have to back through and look at what data changed between the Abyss expansion and the july patch ;/

**Comment by MaruMaruOO** [comment]
The bug is caused by the unneeded "# Implants & Boosters > Booster" entries in service.market.ITEMS_FORCEDMARKETGROUP.
Fixing it causes boosters to correctly have multiple market groups but also exposes a bug in the way item variations are obtained.

This is primarily a note to say I'm working on this and should have a patch up in the next day.
I think I've got a working solution but it needs proper testing and cleaning up.
As a nice bonus it also looks like we should be able to remove ~60 lines of dead code.

**Comment by Sadario** [comment]
https://hoboleaks.space/Tranquility_1343837-1346598.html

Relevant? A lot of the boosters had their marketGroupID changed (see under 'Attribute Changes per Type').

**Comment by blitzmann** [comment]
It's been a while since I took a look at the logic of `ITEMS_FORCEDMARKETGROUP` and what it's used for. But I would think that would affect only the items listed there, not others like standard blue pill? I assume the PR will include information related to the exact reason why it's happening.

Also still want to look myself at what changed in the data between 2.2 and 2.3 releases - I'm sure CCP moved some stuff around to where this now breaks x_x

Thanks for looking into it!

**Comment by Sadario** [comment]
https://hoboleaks.space/Tranquility_1343837-1346598.html

Relevant? A lot of the boosters changed marketGroupID. See under 'Attribute Changes per Type'

**Comment by blitzmann** [comment]
I'll take a closer look tonight as tot he cause, but it seems like @MaruMaruOO might also have a beat on it. Gonna avoid duplication of efforts and wait for him to report back :D

**Comment by Sadario** [comment]
It's not just the line I pointed out that's causing the issue. It's all lines, in that dict, that are mapped to market group 977.

**Comment by MaruMaruOO** [comment]
Should be fixed with #1689 
Hopefully the explanation with the PR makes sense, the last one sure didn't.
I can go into a lot more detail on anything in the PR but I was trying to avoid using 200 lines to explain a 20 line patch.

Also disregard my comment about removing code. I wasn't looking at the item compare panel and though I might be able to get rid of the string manipulation in getVariationsByItems.
After testing and looking at the database I concluded there's really no other practical way to handle implant variations.
