### ISSUE TITLE
Proxy issues makes some feature crash

### ISSUE THREAD

**Issue by Slivo-fr** [pyfa-org/Pyfa#1708]
## Bug Report

I'm using pyfa on a corporation computer with proxy.
When I try to open the SSO -> manage character I got the following error

```
OS version: Windows-10-10.0.16299-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 641, in ssoHandler
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 297, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 328, in popCharList
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 36, in getInstance
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 43, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esiAccess.py", line 88, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 289, in getProxySettingsInRequestsFormat
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 263, in getProxySettings
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 251, in autodetect
ValueError: too many values to unpack (expected 2)

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 403, in showCharacterEditor
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 175, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 781, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 810, in ssoListChanged
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 814, in charChanged
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 36, in getInstance
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 43, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esiAccess.py", line 88, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 289, in getProxySettingsInRequestsFormat
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 263, in getProxySettings
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 251, in autodetect
ValueError: too many values to unpack (expected 2)

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 459, in showPreferenceDialog
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\preferenceDialog.py", line 65, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinPreferenceViews\pyfaNetworkPreferences.py", line 150, in populatePanel
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 251, in autodetect
ValueError: too many values to unpack (expected 2)

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterSelection.py", line 177, in charChanged
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 403, in showCharacterEditor
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 175, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 781, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 810, in ssoListChanged
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 814, in charChanged
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 36, in getInstance
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 43, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esiAccess.py", line 88, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 289, in getProxySettingsInRequestsFormat
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 263, in getProxySettings
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 251, in autodetect
ValueError: too many values to unpack (expected 2)

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 403, in showCharacterEditor
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 175, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 781, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 810, in ssoListChanged
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\characterEditor.py", line 814, in charChanged
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 36, in getInstance
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 43, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esiAccess.py", line 88, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 289, in getProxySettingsInRequestsFormat
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 263, in getProxySettings
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 251, in autodetect
ValueError: too many values to unpack (expected 2)

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 641, in ssoHandler
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 297, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 328, in popCharList
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 36, in getInstance
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 43, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esiAccess.py", line 88, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 289, in getProxySettingsInRequestsFormat
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 263, in getProxySettings
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 251, in autodetect
ValueError: too many values to unpack (expected 2)
```

It also happens with multiple other menu choices (windows/preference, window/character editor).
It seems to be related to the system proxy detection as it crash the same if I disable local network interface and share my phone network over USB

### Expected behavior:

Not being able to pull anything remotely is fine if proxy isn't working, I should however be able to access local feature, shouldn't I ?

### Actual behavior:

A crash window pop when trying to use listed features

![image](https://user-images.githubusercontent.com/10325988/44448665-2a93e300-a5ec-11e8-85ba-0b54a8f74c91.png)

### Detailed steps to reproduce:

You may try pyfa behind a proxied windows 10, if that's not enough I can try to get as much information as I can

### Release or development git branch? Please note the release version or commit hash:
Release 2.3.1 (Same issue on 2.4.0)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 behind a corporate proxy

**Comment by feyyd** [comment]
I think I see the problem, in `def getProxySettingsInRequestsFormat(self) -> dict:` line 287 we set a variable proxies that will be returned.  It is declared `proxies = {}` and then we fill it with getProxySettings().  If proxySettings is None, we skip the next part and then return this empty dictionary.  

This function is being used to fill a python requests Session which is expecting 2 values to be in the dictionary.  Proposed changes, return {"":""} instead of None from getProxySettingsInRequestsFormat().

I might take a stab at this one later.

**Comment by feyyd** [comment]
So @ line 251 we have `proxAddr, proxPort = proxyline.split(":")` which is failing because when it splits there are too many values resulting in value error.  The proxies are in the form `'http':'http://10.112.5.173:49908'` or `'http':'10.112.5.173:49908'` presumably by how the code is written.  We first put the dictionary value into proxyLine, then attempt to remove `{prefix}://` so we end up with a string that looks like `10.112.5.173:49908`.  If the string is formatted like this, everything is peachy, but if not we get the ValueErrors that are occuring. I suspect these ValueErrors are being caused by:

a) a proxy address has extra : in the address, which doing some research this is possible.
b) mismatch of prefix and address string eg `'https':'http://10.112.5.173:49908'`.  This would result in the failed stripping of {prefix}:// from the proxy address/port string due to mismatch.

@Slivo-fr Is there any chance you have your proxy addresses?  another great thing to have would be a readout of `proxydict = urllib.request.ProxyHandler().proxies` in settings.py autodetect() so we could see exactly what values are being parsed.

**Comment by feyyd** [comment]
Might have thought of a quick hack to fix this, just slice the split @ 251
`proxAddr, proxPort = proxyline.split(":")[:2]`

**Comment by minlexx** [comment]
@Slivo-fr how exactly do you configure you proxy settings? Does it look like this?
![Pyfa proxy settings screenshot](https://i.imgur.com/RbrngbU.png)

**Comment by Slivo-fr** [comment]
Didn't expect this much activity overnight :O

The corporate proxy is set by a proxy script. I'm not sure how to get the final values.
Any idea how to proceed ? Could a python (or cmd/powershell) snippet help me to get this information ?

**Comment by minlexx** [comment]
@Slivo-fr so, Pyfa is set to autodetect?

**Comment by Slivo-fr** [comment]
I cannot access pyfa Window/Preferences, it crash the same :(

**Comment by minlexx** [comment]
According to crash logs, proxy mode is set to autodetect (I think this is the default?) and something unexpected comes from a system proxy settings.
Probably some verification/filtering is needed.

@Slivo-fr can you access a windows registry editor and look at section `Software\Microsoft\Windows\CurrentVersion\Internet Settings` for keys values `ProxyEnable`, `ProxyServer` ? (according to https://github.com/python/cpython/blob/3.6/Lib/urllib/request.py#L2632)

**Comment by Slivo-fr** [comment]
ProxyEnable is set to 0
ProxyServer does not exist

**Comment by minlexx** [comment]
And environment variable is called `http_proxy` ? or `https_proxy` ?

**Comment by Slivo-fr** [comment]
Both http_proxy and https_proxy use the value above

**Comment by minlexx** [comment]
so, `proxyline` var has a value `user:password@string-string.string-string.string.string.domain:8080`, that's why `proxAddr, proxPort = proxyline.split(":")` produces 3 parts
- `user`
- `password@string-string.string-string.string.string.domain`
- `8080`

**Comment by minlexx** [comment]
Quick fix probably would be a #1710 , but then authorization part (user:password) is lost and a proxy setting will need to be adjusted manually. But then it should not crash...

**Comment by Slivo-fr** [comment]
Removing the user:password@ fixe the crash, but I do think this will cause issues in some command line usage. Could this proxy string format be handled ?

**Comment by Slivo-fr** [comment]
I still get somme issue on manual (I changed the proxy string to allow me switching mode) but that's not exactly related

**Comment by minlexx** [comment]
autodetect() is still called in preferences dialog regardless of chosen proxy setting type (even in Manual mode) so you will still get a crash without #1710

**Comment by Slivo-fr** [comment]
Understood ! Thanks, I'll watch the fate of #1710 :)

**Comment by minlexx** [comment]
I guess so

**Comment by blitzmann** [comment]
lol, kk

@Slivo-fr are you able to run pyfa from source? Can you verify that `master` now works?

**Comment by Slivo-fr** [comment]
No problem about checking out the master branche, I have however now idea how to run this. 
I'm gonna try.

**Comment by blitzmann** [comment]
@Slivo-fr sorry for the delay.

All you should need is python 3.6, and then running `requirements.txt` through pip, to get you up and running. Unless you're on Linux, in which case there may be special instructions for installing wxpython :)

**Comment by minlexx** [comment]
I don't have windows right now, by memory:
In the directory where your python is installed, in `Tools subdir` (I think) you can find `pip3.exe`, or, better, just directly use `python3.exe -m pip`

So, in pyfa sources directory, run:

`c:\path\to\python3.exe -m pip install -r requirements.txt`

Then run pyfa from source

`c:\path\to\python3.exe .\pyfa.py`

**Comment by Slivo-fr** [comment]
I'm getting several errors with the first command, fixed some of them.

I'm now stuck with a `msvc: Impossible to find a valid architecture for building (in setup_msvc)` I'm not able to fix yet.

**Comment by blitzmann** [comment]
Sounds like it's trying to build something...

@Slivo-fr  Can you post the entire output?

**Comment by Slivo-fr** [comment]
Yeah I can but it's a bit verbose. Also, I'll do it monday, it's weekend o'clock!

**Comment by minlexx** [comment]
It looks like it tries to compile from source (which module by the way? guess wxPython), and that is happening because there are no prebuilt binaries for wxPython-4.0.0 for Python 3.7 yet  ( see https://pypi.org/project/wxPython/4.0.0/#files )

Either install python 3.6 or continue with 3.7, but install wxPython manually by `python3 -m pip install wxPython` without specifying version (requirements.txt has it specified)

**Comment by Slivo-fr** [comment]
It started ! (with python 3.6)

In app crash seems gone, thank you !

**Comment by blitzmann** [comment]
Reopening until a release is made with the fix
