### ISSUE TITLE
2.5.0b1 Deleting fits generates error

### ISSUE THREAD

**Issue by Kalaratiri** [pyfa-org/Pyfa#1713]
## Bug Report
Deleting a fit generates the following error message:
OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

### Expected behavior:
The fit should delete immediately, with no error

### Actual behavior:
The fit remains visible until pyfa is restarted, after which it is gone.

### Detailed steps to reproduce:
Clicking the "delete" icon on any fit

### Fits involved in EFT format (Edit > To Clipboard > EFT):
Any fit

### Release or development git branch? Please note the release version or commit hash:
2.5.0b1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by blitzmann** [comment]
Thanks for the report, this issue has been fixed in the feature branch :D
