### ISSUE TITLE
2.5.0b1 Ammo from cargo can't be equipped/throws error

### ISSUE THREAD

**Issue by feyyd** [pyfa-org/Pyfa#1714]
## Bug Report
Dragging ammo from cargo to guns causes throws error.

### Expected behavior:
Equip the ammo dragged onto guns.

### Actual behavior:
Error message thrown, ammo not equipped.

### Detailed steps to reproduce:
Load fit with ammo in cargo hold.
Drag ammo from cargo hold onto guns.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Vindicator, Vindi fleet]

Corpii A-Type Adaptive Nano Plating
Corpum A-Type Energized Thermal Membrane
Corpum A-Type Energized Kinetic Membrane
Corpus A-Type Armor Explosive Hardener
Imperial Navy 1600mm Steel Plates
Imperial Navy 1600mm Steel Plates
Magnetic Field Stabilizer II

500MN Microwarpdrive II
Heavy Capacitor Booster II
Federation Navy Stasis Webifier
Warp Scrambler II
Sensor Booster II

Neutron Blaster Cannon II, Null L
Neutron Blaster Cannon II, Null L
Neutron Blaster Cannon II, Null L
Neutron Blaster Cannon II, Null L
Neutron Blaster Cannon II, Null L
Neutron Blaster Cannon II, Null L
Neutron Blaster Cannon II, Null L
Neutron Blaster Cannon II, Void L

Large Anti-EM Pump II
Large Trimark Armor Pump I
Large Trimark Armor Pump I

Berserker II x5

Cap Booster 800 x19
Null L x1500
Void L x2000
Caldari Navy Antimatter Charge L x2000

### Release or development git branch? Please note the release version or commit hash:
v2.5.0b

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Error message
OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 23, in Do
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in __setAmmo
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in <dictcomp>
TypeError: list indices must be integers or slices, not Module

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 23, in Do
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in __setAmmo
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in <dictcomp>
TypeError: list indices must be integers or slices, not Module

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 23, in Do
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in __setAmmo
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in <dictcomp>
TypeError: list indices must be integers or slices, not Module

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 23, in Do
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in __setAmmo
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in <dictcomp>
TypeError: list indices must be integers or slices, not Module

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 23, in Do
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in __setAmmo
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in <dictcomp>
TypeError: list indices must be integers or slices, not Module

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 23, in Do
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in __setAmmo
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitSetCharge.py", line 32, in <dictcomp>
TypeError: list indices must be integers or slices, not Module

**Comment by feyyd** [comment]
I'll leave this open til new release
