### ISSUE TITLE
Crash on startup after update

### ISSUE THREAD

**Issue by BlueThrowaway37** [pyfa-org/Pyfa#1721]
Unable to open updated install after 2.3.0 release. Program crashes at startup and gives the following logfile as an error. Program was installed from .exe rather than source. Problem was encountered starting with 2.3.1 stable release .exe

Release: 2.3.1 stable to 2.5.0b1 
```
### Other relevant information:

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlite3.OperationalError: no such column: invtypes.graphicID

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 131, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 45, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainMenuBar.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\graphFrame.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\display.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\viewColumn.py", line 70, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViewColumns\baseName.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\whProjector.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\contextMenu.py", line 182, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\commandFits.py", line 12, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\commandFits.py", line 14, in CommandFits
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\market.py", line 348, in getInstance
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\market.py", line 221, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\market.py", line 221, in <genexpr>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\market.py", line 373, in getItem
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\gamedata\queries.py", line 60, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\gamedata\queries.py", line 94, in getItem
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2755, in first
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2547, in __getitem__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2855, in __iter__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2878, in _execute_and_instances
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: invtypes.graphicID [SQL: 'SELECT invtypes."typeID" AS "invtypes_typeID", invtypes."typeName" AS "invtypes_typeName", invtypes."raceID" AS "invtypes_raceID", invtypes."factionID" AS "invtypes_factionID", invtypes.volume AS invtypes_volume, invtypes.mass AS invtypes_mass, invtypes.capacity AS invtypes_capacity, invtypes.published AS invtypes_published, invtypes."marketGroupID" AS "invtypes_marketGroupID", invtypes."iconID" AS "invtypes_iconID", invtypes."graphicID" AS "invtypes_graphicID", invtypes."groupID" AS "invtypes_groupID" \nFROM invtypes \nWHERE invtypes."typeName" = ?\n LIMIT ? OFFSET ?'] [parameters: ('Virtuoso', 1, 0)]
```

**Comment by BlueThrowaway37** [comment]
The error triggers before the main screen comes up.

**Comment by blitzmann** [comment]
@BlueThrowaway37 Hrm... can you check if you have a pyfa directory at this location:

`%userprofile%\AppData\Local\VirtualStore\Program Files (x86)\`

If so, does it have an eve.db file in it? If so, can you zip that up and upload to this thread?

Additionally, navigate to where pyfa was installed with the exe and find the eve.db file and zip/upload that one as well please

I just tested the virtual store issue, and recent installers still remove the VirtualStore directory. The only other way I could think this may happen is if you installed using exe, and then unzipped another version on top of that (in which case, the installer isn't run which is what cleans up the virtual store directories). But even then, I thought we fixed that within the packaging process itself. :/

Anyway, would be helpful to get those additional files.

**Comment by BlueThrowaway37** [comment]
eve-AppData is the eve.db file from the AppData VirtualStore directory
eve-pyfa is from the install directory for Pyfa
[eve-pyfa.zip](https://github.com/pyfa-org/Pyfa/files/2326462/eve-pyfa.zip)
[eve-appdata.zip](https://github.com/pyfa-org/Pyfa/files/2326463/eve-appdata.zip)

**Comment by blitzmann** [comment]
Are you sure you used the installer? Could you uninstall and then reinstall using the .exe file and see if that helps?

Indeed, the VirtualStore is keeping a copy of an old `eve.db` - one with TQ build 1279361 (generated back in March). I'm hoping the uninstall/reinstall fixes the issue.

Did you come back after a bit of a break by chance? One where you didn't update pyfa regularly?

**Comment by BlueThrowaway37** [comment]
I just tried uninstall/reinstall, both with 2.5.0 beta and then first with the 2.3.0 stable then 2.5.0 beta.

I did come back form a break, but not recently. I've been successfully using pyfa since the 2.0.0 update and keeping it fairly regularly updated to stable.

**Comment by BlueThrowaway37** [comment]
Will try removing the appdata store again and see if 2.3.0 to 2.4.0 or 2.5.0b1 has issues.

**Comment by blitzmann** [comment]
Oh damn... think I figured it out

kk, 2.1.1 is the version in which the installer should remove the virtual store. However, that was supposed to be more of a cleanup, not an actual fix. The actual fix was to tweak the exe in a way that Windows wouldn't use the virtual store. I think for that release it was a manual process, with the intension of making it automated. Don't think I ever got it to be automated... 

I'll take another dive into that issue. Still not sure why your installer isn't removing old files from the VirtualStore, but that's besides the point. I'll keep this issue updated as to progress :)
