### ISSUE TITLE
Bug Repport

### ISSUE THREAD

**Issue by byFantom** [pyfa-org/Pyfa#1739]
When I delete the Asset, an error occurs!
_________________________________________________________________-
OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 333, in OnLeftUp
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\sfBrowserItem.py", line 50, in DoCallback
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 369, in deleteBtnCB
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinShipBrowser\fitItem.py", line 387, in deleteFit
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 220, in deleteFit
AttributeError: type object 'type' has no attribute 'processors'

**Comment by blitzmann** [comment]
Which version of pyfa is this for? AFAIK, this was a bug affecting the recent beta release, and has already been fixed :)

**Comment by blitzmann** [comment]
Going to close this as a duplicate :)
