### ISSUE TITLE
Item Compare error when sorting None values

### ISSUE THREAD

**Issue by Lightsongg** [pyfa-org/Pyfa#1750]
## Bug Report

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemCompare.py", line 88, in SortCompareCols
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemCompare.py", line 134, in PopulateList
TypeError: '<' not supported between instances of 'NoneType' and 'float'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemCompare.py", line 88, in SortCompareCols
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemCompare.py", line 134, in PopulateList
TypeError: '<' not supported between instances of 'NoneType' and 'float'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemCompare.py", line 88, in SortCompareCols
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemCompare.py", line 134, in PopulateList
TypeError: '<' not supported between instances of 'NoneType' and 'float'

### Expected behavior:

Tried to sort tab in compare in module stat window

### Actual behavior:

Didn't happen and error popped up

### Detailed steps to reproduce:

fit cloak item
click show stats
compare tab
sort by scan resolution

### Fits involved in EFT format (Edit > To Clipboard > EFT):

[Nidhoggur, Small gang]

Nanofiber Internal Structure II
Nanofiber Internal Structure II
Drone Damage Amplifier II
Drone Damage Amplifier II
Drone Damage Amplifier II

10000MN Monopropellant Enduring Afterburner
50000MN Quad LiF Restrained Microwarpdrive
500MN Quad LiF Restrained Microwarpdrive
Omnidirectional Tracking Link II, Tracking Speed Script
Drone Navigation Computer II
Heavy Capacitor Booster II, Navy Cap Booster 3200

Heavy Energy Neutralizer II
Fighter Support Unit I
Heavy Energy Neutralizer II
Networked Sensor Array
Dread Guristas Cloaking Device

Capital Hyperspatial Velocity Optimizer I
Capital Hyperspatial Velocity Optimizer I
Capital Hyperspatial Velocity Optimizer I

Templar I x9
Templar I x9
Templar I x9
Siren I x3

Navy Cap Booster 3200 x10

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by blitzmann** [comment]
Hrm, nice find, it's because there are two modules that don't have a scan resolution bonus. Should be an easy fix.
