### ISSUE TITLE
pyfa error when close application

### ISSUE THREAD

**Issue by uronil** [pyfa-org/Pyfa#1753]
OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 361, in OnClose
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 109, in saveAll
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 128, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\.pyfa\\settings\\pyfaEOSSettings'

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 361, in OnClose
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 109, in saveAll
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\settings.py", line 128, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Administrator\\.pyfa\\settings\\pyfaEOSSettings'

**Comment by blitzmann** [comment]
@uronil sorry for the delay in responding, I guess I missed this issue!

It's saying it can't write to the file noted, usually due to file permission issues. I see you're using the admin account on the computer - this may cause issues as I'm sure there's more constraints on it than normal, though it's odd because you should still be able to write to the admin user's home directory when logged in as them. If you wish to keep using that user, I would ensure that the /.pyfa folder has total read/write access.

**Comment by blitzmann** [comment]
@uronil going to close this issue due to lack of activity. If you're still having this issue, please open a new issue and we can dig deeper. The only advise that I can give would be to not use pyfa with the Admin account, or make sure that the pyfa directory has read / write access for everything

**Comment by uronil** [comment]
Thanks!
