### ISSUE TITLE
Can't open Pyfa since latest windows update

### ISSUE THREAD

**Issue by sh1ny** [pyfa-org/Pyfa#1757]
## Bug Report

Starting pyfa fails after upgrading to the latest feature release of windows as of today.
I did try to reinstall and to delete the .pyfa folder in under my home folder.

### Expected behavior:

I expect it to open ;)

### Actual behavior:

Crashes with the following error:
```
OS version: Windows-10-10.0.17763-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\pyfa.py", line 131, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 45, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainMenuBar.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\graphFrame.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\display.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\viewColumn.py", line 70, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinViewColumns\baseName.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\whProjector.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\contextMenu.py", line 182, in <module>
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\commandFits.py", line 12, in <module>
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\commandFits.py", line 14, in CommandFits
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\market.py", line 348, in getInstance
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\market.py", line 174, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\market.py", line 410, in getCategory
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\gamedata\queries.py", line 60, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\gamedata\queries.py", line 226, in getCategory
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2755, in first
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2547, in __getitem__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2855, in __iter__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\orm\query.py", line 2878, in _execute_and_instances
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'SELECT invcategories."categoryID" AS "invcategories_categoryID", invcategories."categoryName" AS "invcategories_categoryName", invcategories.published AS invcategories_published, invcategories."iconID" AS "invcategories_iconID" \nFROM invcategories \nWHERE invcategories."categoryName" = ?\n LIMIT ? OFFSET ?'] [parameters: ('Ship', 1, 0)]

```
### Detailed steps to reproduce:

Starting pyfa fails.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by blitzmann** [comment]
It's saying the database file is locked, which can happen if you have multiple pyfa processes going at the same time.

Can try to uninstall pyfa and reinstall, restart windows, and try again.

**Comment by blitzmann** [comment]
@sh1ny any update?

I also just release 2.5.0, please let me know if it's working for you or not

**Comment by sh1ny** [comment]
Hey,

Sorry i wasn't checking github too much. It seems the 2.5.0 release fixed stuff, i haven't gotten that error anymore.

**Comment by blitzmann** [comment]
👍 excellent, thanks for the update!
