### ISSUE TITLE
Error when deleting fit.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1758]
### Expected behavior:
No error when deleting a fit.

### Actual behavior:
The error in "Other relevant information" is thrown. The fit does get deleted.

### Detailed steps to reproduce:
1. Import the fit below.
2. Select Character Implants in implants tab.
3. Copy the fit.
4. Select Fit_specific Implants in implants tab of the copy.
5. Deleted the copy.
6. Error is thrown

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Retribution, test B]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

Ocular Filter - Standard

### Other relevant information:
```
OS version: Windows-10-10.0.17763-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinAdditionPanes\implantView.py", line 79, in OnRadioSelect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1012, in toggleImplantSource
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 57, in setCache
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 216, in getFit
TypeError: Need integer as argument

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinAdditionPanes\implantView.py", line 79, in OnRadioSelect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1012, in toggleImplantSource
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 57, in setCache
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 216, in getFit
TypeError: Need integer as argument

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinAdditionPanes\implantView.py", line 79, in OnRadioSelect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1012, in toggleImplantSource
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 57, in setCache
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 216, in getFit
TypeError: Need integer as argument

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinAdditionPanes\implantView.py", line 79, in OnRadioSelect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1012, in toggleImplantSource
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 57, in setCache
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 216, in getFit
TypeError: Need integer as argument

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinAdditionPanes\implantView.py", line 79, in OnRadioSelect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1012, in toggleImplantSource
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 57, in setCache
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 216, in getFit
TypeError: Need integer as argument

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinAdditionPanes\implantView.py", line 79, in OnRadioSelect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1012, in toggleImplantSource
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 57, in setCache
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 216, in getFit
TypeError: Need integer as argument

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinAdditionPanes\implantView.py", line 79, in OnRadioSelect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1012, in toggleImplantSource
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 57, in setCache
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 216, in getFit
TypeError: Need integer as argument

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinAdditionPanes\implantView.py", line 79, in OnRadioSelect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1012, in toggleImplantSource
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 57, in setCache
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 216, in getFit
TypeError: Need integer as argument

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinAdditionPanes\implantView.py", line 79, in OnRadioSelect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1012, in toggleImplantSource
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 57, in setCache
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\eos\db\saveddata\queries.py", line 216, in getFit
TypeError: Need integer as argument
```

**Comment by blitzmann** [comment]
Could not reproduce the issue. But, it seems to me it could be a simple issue of fitID being None instead of an int in `OnRadioSelect`... will take a look tomorrow before release. If you're able to reproduce consistently, can you delve into that area to see what might be happening?

**Comment by DeddMazay** [comment]
++ i have errors too

**Comment by blitzmann** [comment]
@DeddMazay what errors? Can you post them? Not all errors are alike :P

**Comment by blitzmann** [comment]
Also, @DeddMazay @Neugeniko which version of pyfa is this?

**Comment by blitzmann** [comment]
Ah, got it to reproduce! The problem that I had before is that I had other fits open, and so it switched pages to the other fit, and didn't error out because it was able to get a activeFitID.

Will fix this before tonights release :)
