### ISSUE TITLE
Issues fetching and errors deleting eve fits

### ISSUE THREAD

**Issue by beokill** [pyfa-org/Pyfa#1780]
## Bug Report
Fetching eve fits and deleting them does not appear to work

### Expected behavior:
It should fetch Eve fits and allow to delete them.

### Actual behavior:
Fetch 1 fit that is not in the selected character eve fittings.
On attempting deletion it gives an error window.

### Detailed steps to reproduce:
Open the menu -> Browse EVE Fittings
Attempt to fetch fits (Does not always fetch)
Either get no fits or 1 fit
Attempt to delete the 1 fit
Get error window

### Release or development git branch? Please note the release version or commit hash:
2.5.1 release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Win 10

### Other relevant information:
https://i.imgur.com/pjnNJOx.png <- picture of the fit window, the Char has a lot more fits in eve.
Here's the log from the error windows, appears to rely on hardcoded paths.

    pyfa vv2.5.1
    EVE Data Version: 1400958 (2018-10-15 21:11:58)
    
    OS version: Windows-10-10.0.17134-SP0
    Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
    wxPython version: 4.0.3 (wxWidgets 3.0.5)
    SQLAlchemy version: 1.1.10
    Logbook version: 1.0.0
    Requests version: 2.18.4
    Dateutil version: 2.6.0

    ####################

    Traceback (most recent call last):
      File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\esiFittings.py", line 150, in deleteFitting
      File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 103, in delFitting
      File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esiAccess.py", line 126, in delFitting
      File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esiAccess.py", line 284, in delete
      File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esiAccess.py", line 266, in _after_request
    service.esiAccess.APIException: HTTP Error 500: Unhandled internal error encountered!

**Comment by blitzmann** [comment]
> Note that I'm fairly confident I had deleted this exact fit not 1min ago in pyfa so this bug may be a simple issue where the fit was already gone when it attempted deletion.

That very well could be. Can you post the .log files found at `~/.pyfa`? I'm hoping it can give me the fitting ID that was deleted, and see if it was deleted previously. Currently, if you delete a fit, the cached list is not updated. Been a todo item for a while now, but it's low in priority.

fyi, the paths in the error dialog are just how the application sets up it' environment. It's never going to look like your folder structure.

**Comment by beokill** [comment]
[pyfa-2018-10-20.log](https://github.com/pyfa-org/Pyfa/files/2498787/pyfa-2018-10-20.log)
