### ISSUE TITLE
Character Skill Not Recognized

### ISSUE THREAD

**Issue by brightvalley** [pyfa-org/Pyfa#1783]
I am working a fit with Dual Heavy Modulated Pulse Energy Beam I on it. The skillbook is red, claiming I need the skill Large Energy Turret 1. I have confirmed in-game that this is true.

This particular character has Large Energy Turret 3, and has had level 3 for a while now.

The refresh button is also not active so I cannot freshen my skillset.

I tried revoking that character and adding it back again, and got the same result.

**Comment by blitzmann** [comment]
> The refresh button is also not active so I cannot freshen my skillset.

This leads me to believe you have not linked your pyfa character to your eve character, even though you may have "logged in" with that character.

Check the character editor > EVE SSO tab. This should show any characters that you have logged into via EVE Single Sign-On. From that drop down, select the character that matches whatever character is represented in pyfa. If you don't see the correct EVE character in the list, click the button at the bottom to go through the process of logging into the character.

Once you do this, you should be able to refresh your skills

If this does not work, I'll have you send over some files via email so that I can debug :)

**Comment by brightvalley** [comment]
Yes, I have. What files do you need?

**Comment by brightvalley** [comment]
Sent.

**Comment by Kazei** [comment]
I'm having a similar problem. When I try to log in to EVE SSO, I get jumped to a web page that indicates it's "processing" the login, but nothing seems to happen. It's a localhost address. This may be working as intended, I don't know, but since I never get an updated character in pyfa, I'd say *something's* not right. :-(

**Comment by blitzmann** [comment]
@Kazei @dupreesdiamond  Do you see this message:

![image](https://user-images.githubusercontent.com/3904767/52423735-b7f9bf80-2ac6-11e9-8264-77bdf86aa5eb.png)

and do you see the character pop up in the SSO Character Manager:
![image](https://user-images.githubusercontent.com/3904767/52423759-c2b45480-2ac6-11e9-88a0-1ac5b6cc46a8.png)

If that's the case, the sso link worked.

BUT that does not mean that skills are automatically updated. This just means that pyfa now knows about your EVE character and is able to login to the API to fetch information about that character.

You must still link your pyfa character to your EVE Online character via the pyfa Character Editor (Window > Character Editor > Select or create new character > EVE SSO tab). Once you do this, you'll be able to refresh the pyfa characters skills

If you DONT see the character added, then there may be something happening with firewalls that prevents the local server pyfa spins up to receive info. in that case, you can go to Preferences > SSO > switch from Local server to manual. This will give you a box that you can paste the login information into that pyfa.io will supply after successfully logging in

**Comment by blitzmann** [comment]
Also, sorry about the late replies. We just had a baby so things are all over the place and getting backed up.

This character confusion thing (people expecting skills to refresh when linking a character) has popped up before. I'm planning on eventually making a little text snippet on the window to explain that it's simply for pyfa to be aware of the eve character, and you must still link the character to a pyfa character. Could also give the ability to automatically create and link a character when signing in.

**Comment by Kazei** [comment]
Congrats on your new pilot. :-)

I see the pyfa message. Also there's a quick message that flashes on and then goes away. I think it says something about connecting to something. :-)

The character does not pop up in the character manager. Opening the firewall to all connections doesn't make any difference.

Tried the manual route. Got this:

OS version: Darwin-18.2.0-x86_64-i386-64bit
Python version: 3.6.3 (default, Oct 22 2017, 22:24:50) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.72)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.1

####################

Traceback (most recent call last):
  File "/Users/ryan/pyfa/gui/mainFrame.py", line 254, in ShowSsoLogin
  File "/Users/ryan/pyfa/service/esi.py", line 156, in handleLogin
  File "/Users/ryan/pyfa-bitbucket/venv/lib/python3.6/site-packages/requests/models.py", line 892, in json
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by blitzmann** [comment]
Your using mac, hrm...

Can you post any log files found in `~/.pyfa`

I may have to test the manual stuff on mac at some point. Also, please make sure you have latest version

**Comment by Kazei** [comment]
I just re-downloaded the latest pyfa, and now the manual stuff is working, at least. I'll try going back to automatic SSO and see if that works.

**Comment by Kazei** [comment]
Okay, local server mode is working too. Got this message on the generated web page: "If you see this message then it means you should be logged into EVE SSO. You may close this window and return to the application."

That's what was flashing and then disappearing before.

My conclusion is that either the previous download of pyfa got corrupted somehow how, or I'm an idiot and was working off an old version. :-)

**Comment by dupreesdiamond** [comment]
Congrats!

Yeah my character was logged in and everything is as you described other
than the skills updating.  I even removed the character and went back in an
readded to no avail.  I will try re-installing this evening and see if that
resolves the issue.

**Comment by blitzmann** [comment]
@dupreesdiamond make sure that the pyfa character was linked to the EVE SSO character. if that still doesn't update the skills correctly, let me know. May have to get a few files from you to analyze if it doesn't work.
