### ISSUE TITLE
Removing drones from drone bay caused an error

### ISSUE THREAD

**Issue by brightvalley** [pyfa-org/Pyfa#1788]
First noticed an issue when I decreased the number of drones on a Gila from 5 to 4, and the bandwidth didn't drop. Then I removed all the drones from the fit and this happened (edited):

pyfa vv2.5.1
EVE Data Version: 1400958 (2018-10-15 20:11:58)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.3 (wxWidgets 3.0.5)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "...\Pyfa\gui\fitCommands\calc\fitRemoveDrone.py", line 24, in Do
  File "...\Pyfa\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 224, in __set__
  File "...\Pyfa\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 702, in set
  File "...\Pyfa\venv\lib\site-packages\sqlalchemy\orm\attributes.py", line 711, in fire_replace_event
  File "...\Pyfa\venv\lib\site-packages\sqlalchemy\orm\util.py", line 118, in set_
  File "...\Pyfa\eos\saveddata\drone.py", line 206, in validator
ValueError: 1 is not a valid value for amountActive

**Comment by DarkFenX** [comment]
This part of the app has been massively reworked in 2.9.0, reopen if you still have this issue.
