### ISSUE TITLE
Applying muta to BCS not working.

### ISSUE THREAD

**Issue by Neugeniko** [pyfa-org/Pyfa#1800]
### Expected behavior:
When you rightclick>module stats a abyssal bcs you get to change its attributes.

### Actual behavior:
The following error and nothing happens.

pyfa vv2.6.0
EVE Data Version: 1420430 (2018-11-14 12:35:30)

OS version: Windows-10-10.0.17763-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.3 (wxWidgets 3.0.5)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\contextMenu.py", line 138, in handler
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinContextMenus\itemStats.py", line 69, in activate
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 99, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\itemStats.py", line 168, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\itemMutator.py", line 80, in __init__
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\builtinItemStatsViews\attributeSlider.py", line 75, in __init__
TypeError: SpinCtrlDouble(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 'min' has unexpected type 'str'

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Vengeance, Vengeance fit]

Ballistic Control System II
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

Rocket Launcher I, Mjolnir Rocket
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]

### Release or development git branch? Please note the release version or commit hash:
onslaught 1.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
win10

**Comment by Neugeniko** [comment]
The culprit is in gamedata.py line 584 -

lambda v: ("%+.2f" if ((v - 1) * 100) % 1 else "%+d") % ((v - 1) * 100),



should it just be? 

lambda v: (v - 1) * 100,

or is the module info bugged somehow and inappropriately calling this?

**Comment by DarkFenX** [comment]
Found it myself as well and already fixed in f664a1cad3e21f1217df17a1c6e1700863b1d988
