### ISSUE TITLE
Crash when dragging non-charge into fitting window with a module highlighted that doesn't take a charge

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1814]
### Detailed steps to reproduce:

1) Fit Entropic Radiation Sink I to fit
2) Click to select it
3) Drag Entropic Radiation Sink II to a  empty slot
4) This bug happens, and 2 Entropic Radiation Sink II's get added

```
pyfa vv2.6.1
EVE Data Version: 1422751 (2018-11-20 21:53:58)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.3 (wxWidgets 3.0.5)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitReplaceModule.py", line 33, in Do
    return self.change_module(self.fitID, self.position, self.itemID)
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\fitCommands\calc\fitReplaceModule.py", line 81, in change_module
    if self.old_module.charge and self.module.isValidCharge(self.old_module.charge):
AttributeError: 'NoneType' object has no attribute 'charge'
```

**Comment by blitzmann** [comment]
Seems to be an issue with the fix for #1806
