### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by KaZaK007** [pyfa-org/Pyfa#1824]
pyfa vv2.6.1
EVE Data Version: 1425015 (2018-11-22 15:28:54)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.3 (wxWidgets 3.0.5)
SQLAlchemy version: 1.1.10
Logbook version: 1.0.0
Requests version: 2.18.4
Dateutil version: 2.6.0

####################

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connection.py", line 326, in connect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
  File "C:\Python36\lib\ssl.py", line 401, in wrap_socket
  File "C:\Python36\lib\ssl.py", line 808, in __init__
  File "C:\Python36\lib\ssl.py", line 1061, in do_handshake
  File "C:\Python36\lib\ssl.py", line 683, in do_handshake
ConnectionResetError: [WinError 10054] Удаленный хост принудительно разорвал существующее подключение

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\adapters.py", line 440, in send
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\retry.py", line 357, in increment
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 346, in _make_request
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connectionpool.py", line 850, in _validate_conn
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\connection.py", line 326, in connect
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\urllib3\util\ssl_.py", line 329, in ssl_wrap_socket
  File "C:\Python36\lib\ssl.py", line 401, in wrap_socket
  File "C:\Python36\lib\ssl.py", line 808, in __init__
  File "C:\Python36\lib\ssl.py", line 1061, in do_handshake
  File "C:\Python36\lib\ssl.py", line 683, in do_handshake
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\gui\mainFrame.py", line 245, in ShowSsoLogin
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\service\esi.py", line 150, in handleLogin
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\sessions.py", line 521, in get
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\sessions.py", line 508, in request
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\sessions.py", line 618, in send
  File "C:\Users\holme\Documents\Sync\Git\blitzmann\Pyfa\venv\lib\site-packages\requests\adapters.py", line 490, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'Удаленный хост принудительно разорвал существующее подключение', None, 10054, None))

**Comment by blitzmann** [comment]
Duplicate #1823

Also, when writing a bug report, please follow the layout provided with a description of what you were trying to do when you ran into this issue. Just helps me better understand where this may have happened :)
