### ISSUE TITLE
Error while browsing fits

### ISSUE THREAD

**Issue by brightvalley** [pyfa-org/Pyfa#1837]
I received the following while attempting to browse fits:

pyfa vv2.7.0
EVE Data Version: 1435052 (2018-12-12 03:48:30)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]
wxPython version: 4.0.0b2 (wxWidgets 3.0.4)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.1
Requests version: 2.21.0
Dateutil version: 2.7.5

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\esiFittings.py", line 126, in fetchFittings
  File "C:\projects\pyfa\gui\esiFittings.py", line 110, in fetchFittings
  File "C:\projects\pyfa\service\esi.py", line 92, in getFittings
  File "C:\projects\pyfa\service\esiAccess.py", line 119, in getFittings
  File "C:\projects\pyfa\service\esiAccess.py", line 274, in get
  File "C:\projects\pyfa\service\esiAccess.py", line 266, in _after_request
  File "C:\Python36\lib\site-packages\requests\models.py", line 897, in json
  File "C:\Python36\lib\json\__init__.py", line 354, in loads
  File "C:\Python36\lib\json\decoder.py", line 339, in decode
  File "C:\Python36\lib\json\decoder.py", line 357, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by blitzmann** [comment]
I'm hoping this is fixed with latest release. Please open new issue if it's not
