### ISSUE TITLE
Opening stats window is painfully slow for some items

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1850]
1. Use fresh saveddata.db
2. Open stats window for "Adaptive Nano Plating II"

It takes 1.5+ seconds to open it. It happends due to compare tab which contains multiple items, for which we're fetching the price. Price fetching happens in separate thread, but initialization of price objects happens locally. Gamedata.py, Item class

```
    @property
    def price(self):
        # todo: use `from sqlalchemy import inspect` instead (mac-deprecated doesn't have inspect(), was imp[lemented in 0.8)
        if self.__priceObj is not None and getattr(self.__priceObj, '_sa_instance_state', None) and self.__priceObj._sa_instance_state.deleted:
            pyfalog.debug("Price data for {} was deleted (probably from a cache reset), resetting object".format(self.ID))
            self.__priceObj = None

        if self.__priceObj is None:
            db_price = eos.db.getPrice(self.ID)
            # do not yet have a price in the database for this item, create one
            if db_price is None:
                pyfalog.debug("Creating a price for {}".format(self.ID))
                self.__priceObj = types_Price(self.ID)
                eos.db.add(self.__priceObj)
                eos.db.commit()
            else:
                self.__priceObj = db_price

        return self.__priceObj
```
Each commit() takes approximately 50 ms on my work machine, with 30+ items process takes 1.5 seconds or longer, so opening such windows is painfully slow.

**Comment by DarkFenX** [comment]
Commenting out commit() results in SQLAlchemy concurrency issues. For example, when you have fit with 2 large abyssal batteries, and it's opened when you have prices table purged of data - pyfa crashes:

```
pyfa v2.7.0 (git)
EVE Data Version: 1435052 (2018-12-12 12:48:30)

OS version: Linux-4.19.0-1-amd64-x86_64-with-debian-buster-sid
Python version: 3.7.2+ (default, Feb  2 2019, 14:31:48) 
[GCC 8.2.0]
wxPython version: 4.0.4 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.15
Logbook version: 1.4.0
Requests version: 2.20.0
Dateutil version: 2.7.3

####################

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 506, in do_executemany
    cursor.executemany(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: prices.typeID

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/av/Workspace/eve/pyfa/eos/db/saveddata/queries.py", line 544, in commit
    saveddata_session.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 954, in commit
    self.transaction.commit()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2313, in flush
    self._flush(objects)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 249, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/session.py", line 2404, in _flush
    flush_context.execute()
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 395, in execute
    rec.execute(self)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/unitofwork.py", line 560, in execute
    uow
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "/usr/lib/python3/dist-packages/sqlalchemy/orm/persistence.py", line 836, in _emit_insert_statements
    execute(statement, multiparams)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 506, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: prices.typeID [SQL: 'INSERT INTO prices ("typeID", price, time, status) VALUES (?, ?, ?, ?)'] [parameters: ((49773, 37877797.98, 1550142061.3560367, <PriceStatus.notFetched: 0>), (20565, 38399174.92, 1550142061.3559656, <PriceStatus.notFetched: 0>), (23864, 14679998.99, 1550142061.3558595, <PriceStatus.notFetched: 0>), (14202, 24000000.0, 1550142061.3561966, <PriceStatus.notFetched: 0>), (19321, 217749959.99, 1550142061.3561788, <PriceStatus.notFetched: 0>), (48439, 0.0, 0, <PriceStatus.notSupported: 3>), (48439, 0.0, 0, <PriceStatus.notFetched: 0>), (18666, 133998774.01, 1550142061.3560193, <PriceStatus.notFetched: 0>)  ... displaying 10 of 40 total bound parameter sets ...  (49713, 424694159.22, 1550142061.3557875, <PriceStatus.notFetched: 0>), (46006, 4798999.99, 1550142061.3558416, <PriceStatus.notFetched: 0>))] (Background on this error at: http://sqlalche.me/e/gkpj)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/av/Workspace/eve/pyfa/service/price.py", line 192, in cb
    db.commit()
  File "/home/av/Workspace/eve/pyfa/eos/db/saveddata/queries.py", line 549, in commit
    raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
TypeError: __init__() missing 2 required positional arguments: 'params' and 'orig'
```

Why it happens - I am yet to find out.

**Comment by DarkFenX** [comment]
Actually, i think i fixed it by replacing commit() with flush() which takes much less time, see 3ed949395e421c7e2ace12fcf2395f47dcbddbf3

If prices are flushed into DB - then querying DB returns previously generated price objects for the same typeID, thus pyfa does not generate duplicate price objects and no constraints are broken during commit()
