### ISSUE TITLE
Attempt to switch to raw attribute view leads to crash

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1867]
This issue still happens on latest master. I reported something similar after trying out attribute grouping branch, but I think @blitzmann mentioned that it was fixed.

1. Create curse fit
2. Add IN cap rech to it
3. Open attributes of said cap rech
4. Attempt to switch to raw view

### Expected behavior:
View is switched to raw attribute view

### Actual behavior:
Crash window pops up, view is not switched

```
pyfa v2.7.5
EVE Data Version: 1464839 (2019-03-01 02:50:17)

OS version: Linux-4.19.0-2-amd64-x86_64-with-debian-buster-sid
Python version: 3.7.2+ (default, Feb  2 2019, 14:31:48) 
[GCC 8.2.0]
wxPython version: 4.0.4 (wxWidgets 3.0.4)
SQLAlchemy version: 1.2.18
Logbook version: 1.4.0
Requests version: 2.21.0
Dateutil version: 2.7.3

####################

Traceback (most recent call last):
  File "/home/av/Workspace/eve/pyfa/gui/builtinItemStatsViews/itemAttributes.py", line 105, in ToggleViewMode
    self.UpdateList()
  File "/home/av/Workspace/eve/pyfa/gui/builtinItemStatsViews/itemAttributes.py", line 93, in UpdateList
    self.PopulateList()
  File "/home/av/Workspace/eve/pyfa/gui/builtinItemStatsViews/itemAttributes.py", line 244, in PopulateList
    self.AddAttribute(root, name)
  File "/home/av/Workspace/eve/pyfa/gui/builtinItemStatsViews/itemAttributes.py", line 180, in AddAttribute
    self.paramList.SetItemImage(attr_item, attrIcon, which=wx.TreeItemIcon_Normal)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/hypertreelist.py", line 5000, in delegate
    return getattr(self._main_win, method)(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/hypertreelist.py", line 2226, in SetItemImage
    self.CalculateSize(item, dc)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/hypertreelist.py", line 3898, in CalculateSize
    image_w, image_h = self._imageListNormal.GetSize(image)
wx._core.wxAssertionError: C++ assertion "node" failed at ../src/generic/imaglist.cpp(247) in GetSize(): wrong index in image list

####################

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/wx/lib/agw/customtreectrl.py", line 8199, in OnInternalIdle
    self.CalculatePositions()
  File "/usr/lib/python3/dist-packages/wx/lib/agw/hypertreelist.py", line 4014, in CalculatePositions
    self.CalculateLevel(self._anchor, dc, 0, y, x_colstart) # start recursion
  File "/usr/lib/python3/dist-packages/wx/lib/agw/hypertreelist.py", line 3955, in CalculateLevel
    y = self.CalculateLevel(children[n], dc, level, y, x_colstart)  # recurse
  File "/usr/lib/python3/dist-packages/wx/lib/agw/hypertreelist.py", line 3959, in CalculateLevel
    self.CalculateSize(item, dc)
  File "/usr/lib/python3/dist-packages/wx/lib/agw/hypertreelist.py", line 3898, in CalculateSize
    image_w, image_h = self._imageListNormal.GetSize(image)
wx._core.wxAssertionError: C++ assertion "node" failed at ../src/generic/imaglist.cpp(247) in GetSize(): wrong index in image list
```

```
[Curse, Curse fit]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Imperial Navy Cap Recharger
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

[Empty Rig slot]
[Empty Rig slot]
```

**Comment by blitzmann** [comment]
Hrm I might have only fixed it in the other view. Will check later today

**Comment by blitzmann** [comment]
Doesn't look like this is the same issue.

Commenting this bit of code prevents it fro crashing:
```        if self.toggleView == AttributeView.NORMAL and ((attr not in GroupedAttributes and not value) or info is None or not info.published or attr in RequiredSkillAttrs):
            return None```

But, at the same time, that's our check for not displaying attributes that don't matter. Still digging

**Comment by blitzmann** [comment]
Got a fix out...

This is dumb. GTK yells if you assign the mage list before there are images loaded (previous issue). GTK also yells apparently if you try to set images when no image list is assigned (this issue). I haven't completely narrowed down exactly why this happens, but this at least fixes it.

Eventually need to refactor this to generate the image list on load - the attributes aren't going to change, only the display of the attributes, so no reason we should be redoing the images if the view changes. But that should be for another time.

**Comment by blitzmann** [comment]
Closing this as it was a bug for an unreleased feature. :)
