### ISSUE TITLE
Backup All Fittings error

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#1908]
```Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\gitRoot\Pyfa\service\port\port.py", line 80, in backupFitsWorkerFunc
    *svcFit.getInstance().getAllFits())
TypeError: exportXml() takes from 1 to 3 positional arguments but 11 were given```

**Comment by DarkFenX** [comment]
Fixed in 768c1d37b19429bc9f92080d3f789e387c75739e
