### ISSUE TITLE
Crash when adding items with max group fitted restriction

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1927]
Reportedly, does not always crash.

Might be occur only to modules with restrictions - like NSA and hyperspatial accelerator. 
```
####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\fitCommands\calc\module\localClone.py", line 30, in Do
  File "C:\projects\pyfa\eos\saveddata\module.py", line 544, in fits
  File "C:\projects\pyfa\eos\saveddata\module.py", line 580, in __fitRestrictions
  File "C:\projects\pyfa\eos\saveddata\module.py", line 249, in getModPosition
ValueError: Module(ID=33985, name=Prototype Hyperspatial Accelerator) at 0xd7755b0 is not in list

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\fitCommands\calc\module\localClone.py", line 30, in Do
  File "C:\projects\pyfa\eos\saveddata\module.py", line 544, in fits
  File "C:\projects\pyfa\eos\saveddata\module.py", line 580, in __fitRestrictions
  File "C:\projects\pyfa\eos\saveddata\module.py", line 249, in getModPosition
ValueError: Module(ID=33985, name=Prototype Hyperspatial Accelerator) at 0xf8a1d30 is not in list

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\fitCommands\calc\module\localClone.py", line 30, in Do
  File "C:\projects\pyfa\eos\saveddata\module.py", line 544, in fits
  File "C:\projects\pyfa\eos\saveddata\module.py", line 580, in __fitRestrictions
  File "C:\projects\pyfa\eos\saveddata\module.py", line 249, in getModPosition
ValueError: Module(ID=33985, name=Prototype Hyperspatial Accelerator) at 0xfc185f0 is not in list
```

**Comment by DarkFenX** [comment]
Fixed in 4c04fd93aeb9e70a1679a4974eebbfb69ae4f365
