### ISSUE TITLE
Pyfa Launch Issue

### ISSUE THREAD

**Issue by sidthekid100** [pyfa-org/Pyfa#1956]
Getting this error after installing Pyfa and attempting to run the first time:

> pyfa v2.9.1
EVE Data Version: 1492195 (2019-04-16 06:50:22)

> OS version: Windows-10-10.0.17763-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.4 (wxWidgets 3.0.5)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.8.0

####################

> Traceback (most recent call last):
  File "C:\projects\pyfa\pyfa.py", line 132, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\gui\mainFrame.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\gui\graphFrame.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\gui\display.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\gui\viewColumn.py", line 70, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\gui\builtinViewColumns\baseName.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\gui\builtinContextMenus\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\gui\builtinContextMenus\commandFitAdd.py", line 104, in <module>
  File "C:\projects\pyfa\gui\builtinContextMenus\commandFitAdd.py", line 38, in populateFits
  File "C:\projects\pyfa\service\fit.py", line 141, in getFitsWithModules
  File "C:\projects\pyfa\eos\db\saveddata\queries.py", line 276, in getFitsWithModules
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2398, in all
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\loading.py", line 84, in instances
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 188, in raise_from_cause
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 182, in reraise
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\loading.py", line 65, in instances
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\result.py", line 955, in fetchall
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 188, in raise_from_cause
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 181, in reraise
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\result.py", line 949, in fetchall
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\result.py", line 900, in _fetchall_impl
sqlalchemy.exc.DatabaseError: (sqlite3.DatabaseError) database disk image is malformed

**Comment by DarkFenX** [comment]
Just tried 2.9.1 on my win10 machine and it loads fine. So, some additional questions/suggestions:
1) Remove <user folder>\.pyfa and try again, see if anything changes
2) Do you have C:\Python36 actually on your storage? Is this folder in your PATH? See https://docs.alfresco.com/4.2/tasks/fot-addpath.html if you do not know where to look
3) Do you have any kind of AV software which might somehow screw it over? If yes try temporarily disabling it and see if it works.

**Comment by sidthekid100** [comment]
Issue resolved with deleting .pyfa folder
