### ISSUE TITLE
Opening a new fitting or old fitting leads to error [linux]

### ISSUE THREAD

**Issue by ForlornWongraven** [pyfa-org/Pyfa#1960]
Installed all dependencies with pip. When I open any old fitting or start to make a new fitting pyfa shows an error message (below) and stops working.

pyfa v2.9.1
EVE Data Version: 1492195 (2019-04-16 15:50:22)

OS version: Linux-5.0.9-200.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine
Python version: 3.7.3 (default, Mar 27 2019, 13:41:07) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)]
wxPython version: 4.0.4 (wxWidgets 3.0.5)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "/opt/pyfa/eos/gamedata.py", line 165, in __generateHandler
    self.__effectDef = effectDef = getattr(eos.effects, effectDefName)
AttributeError: module 'eos.effects' has no attribute 'Effect132'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyfa/gui/builtinViews/fittingView.py", line 88, in fitSelected
    view.fitSelected(event)
  File "/opt/pyfa/gui/builtinViews/fittingView.py", line 331, in fitSelected
    self.slotsChanged()
  File "/opt/pyfa/gui/builtinViews/fittingView.py", line 517, in slotsChanged
    self.generateMods()
  File "/opt/pyfa/gui/builtinViews/fittingView.py", line 468, in generateMods
    fit = sFit.getFit(self.activeFitID)
  File "/opt/pyfa/service/fit.py", line 309, in getFit
    self.recalc(fit)
  File "/opt/pyfa/service/fit.py", line 526, in recalc
    fit.calculateModifiedAttributes()
  File "/opt/pyfa/eos/saveddata/fit.py", line 862, in calculateModifiedAttributes
    item.calculateModifiedAttributes(self, runTime, False)
  File "/opt/pyfa/eos/saveddata/character.py", line 276, in calculateModifiedAttributes
    skill.calculateModifiedAttributes(fit, runTime)
  File "/opt/pyfa/eos/saveddata/character.py", line 420, in calculateModifiedAttributes
    if effect.runTime == runTime and \
  File "/opt/pyfa/eos/gamedata.py", line 81, in runTime
    self.__generateHandler()
  File "/opt/pyfa/eos/gamedata.py", line 181, in __generateHandler
    self.__handler = eos.effects.DummyEffect.handler
AttributeError: module 'eos.effects' has no attribute 'DummyEffect'

####################

Traceback (most recent call last):
  File "/opt/pyfa/eos/gamedata.py", line 165, in __generateHandler
    self.__effectDef = effectDef = getattr(eos.effects, effectDefName)
AttributeError: module 'eos.effects' has no attribute 'Effect132'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyfa/gui/builtinShipBrowser/sfBrowserItem.py", line 369, in OnLeaveWindow
    self.Refresh()
  File "/opt/pyfa/gui/builtinShipBrowser/fitItem.py", line 569, in Refresh
    fit = sFit.getFit(activeFit)
  File "/opt/pyfa/service/fit.py", line 309, in getFit
    self.recalc(fit)
  File "/opt/pyfa/service/fit.py", line 526, in recalc
    fit.calculateModifiedAttributes()
  File "/opt/pyfa/eos/saveddata/fit.py", line 862, in calculateModifiedAttributes
    item.calculateModifiedAttributes(self, runTime, False)
  File "/opt/pyfa/eos/saveddata/character.py", line 276, in calculateModifiedAttributes
    skill.calculateModifiedAttributes(fit, runTime)
  File "/opt/pyfa/eos/saveddata/character.py", line 420, in calculateModifiedAttributes
    if effect.runTime == runTime and \
  File "/opt/pyfa/eos/gamedata.py", line 81, in runTime
    self.__generateHandler()
  File "/opt/pyfa/eos/gamedata.py", line 181, in __generateHandler
    self.__handler = eos.effects.DummyEffect.handler
AttributeError: module 'eos.effects' has no attribute 'DummyEffect'

####################

Traceback (most recent call last):
  File "/opt/pyfa/eos/gamedata.py", line 165, in __generateHandler
    self.__effectDef = effectDef = getattr(eos.effects, effectDefName)
AttributeError: module 'eos.effects' has no attribute 'Effect132'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyfa/gui/builtinShipBrowser/sfBrowserItem.py", line 363, in OnEnterWindow
    self.Refresh()
  File "/opt/pyfa/gui/builtinShipBrowser/fitItem.py", line 569, in Refresh
    fit = sFit.getFit(activeFit)
  File "/opt/pyfa/service/fit.py", line 309, in getFit
    self.recalc(fit)
  File "/opt/pyfa/service/fit.py", line 526, in recalc
    fit.calculateModifiedAttributes()
  File "/opt/pyfa/eos/saveddata/fit.py", line 862, in calculateModifiedAttributes
    item.calculateModifiedAttributes(self, runTime, False)
  File "/opt/pyfa/eos/saveddata/character.py", line 276, in calculateModifiedAttributes
    skill.calculateModifiedAttributes(fit, runTime)
  File "/opt/pyfa/eos/saveddata/character.py", line 420, in calculateModifiedAttributes
    if effect.runTime == runTime and \
  File "/opt/pyfa/eos/gamedata.py", line 81, in runTime
    self.__generateHandler()
  File "/opt/pyfa/eos/gamedata.py", line 181, in __generateHandler
    self.__handler = eos.effects.DummyEffect.handler
AttributeError: module 'eos.effects' has no attribute 'DummyEffect'

####################

Traceback (most recent call last):
  File "/opt/pyfa/eos/gamedata.py", line 165, in __generateHandler
    self.__effectDef = effectDef = getattr(eos.effects, effectDefName)
AttributeError: module 'eos.effects' has no attribute 'Effect132'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pyfa/gui/builtinShipBrowser/sfBrowserItem.py", line 369, in OnLeaveWindow
    self.Refresh()
  File "/opt/pyfa/gui/builtinShipBrowser/fitItem.py", line 569, in Refresh
    fit = sFit.getFit(activeFit)
  File "/opt/pyfa/service/fit.py", line 309, in getFit
    self.recalc(fit)
  File "/opt/pyfa/service/fit.py", line 526, in recalc
    fit.calculateModifiedAttributes()
  File "/opt/pyfa/eos/saveddata/fit.py", line 862, in calculateModifiedAttributes
    item.calculateModifiedAttributes(self, runTime, False)
  File "/opt/pyfa/eos/saveddata/character.py", line 276, in calculateModifiedAttributes
    skill.calculateModifiedAttributes(fit, runTime)
  File "/opt/pyfa/eos/saveddata/character.py", line 420, in calculateModifiedAttributes
    if effect.runTime == runTime and \
  File "/opt/pyfa/eos/gamedata.py", line 81, in runTime
    self.__generateHandler()
  File "/opt/pyfa/eos/gamedata.py", line 181, in __generateHandler
    self.__handler = eos.effects.DummyEffect.handler
AttributeError: module 'eos.effects' has no attribute 'DummyEffect'

**Comment by DarkFenX** [comment]
We've combined all the effect definitions into a single file, `eos/effects.py`. Said file has definition of class `DummyEffect`. My guess is that you still have old folder `eos/effects/*` for whatever reason and it gets imported instead. Please check if it's there and if yes - remove. If you do not have any files you might need in pyfa folder it might make sense to run `git clean -fdx` which will clean everything for you.

**Comment by ForlornWongraven** [comment]
That was indeed the case. Fixed it!

**Comment by DarkFenX** [comment]
Nice, glad that 1st guess worked.
