### ISSUE TITLE
OperationalError on opening fits

### ISSUE THREAD

**Issue by cbz** [pyfa-org/Pyfa#1967]
## Bug Report

On opening a fit - either via import or via selecting a fit in the left hand column, I get variants of the following error, this is the case for all fits -- I assume there was a migration stanza to add this column that needed to be added.

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\statsPane.py", line 75, in fitChanged
  File "C:\projects\pyfa\gui\builtinStatsViews\priceViewFull.py", line 83, in refreshPanel
  File "C:\projects\pyfa\service\price.py", line 160, in getPrices
  File "C:\projects\pyfa\eos\gamedata.py", line 468, in price
  File "C:\projects\pyfa\eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "C:\projects\pyfa\eos\db\saveddata\queries.py", line 58, in setCache
  File "C:\projects\pyfa\eos\db\saveddata\queries.py", line 333, in getPrice
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 959, in get
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 1069, in _get_impl
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\loading.py", line 282, in load_on_pk_identity
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 3275, in one
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 3244, in one_or_none
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 3317, in __iter__
  File "C:\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 3342, in _execute_and_instances
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\elements.py", line 287, in _execute_on_connection
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1107, in _execute_clauseelement
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (25861,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10
pyfa 2.91/2.93

**Comment by DarkFenX** [comment]
yes, looks like it. It's upgrade30:
```
def upgrade(saveddata_engine):
    try:
        saveddata_engine.execute("SELECT status FROM prices LIMIT 1")
    except sqlalchemy.exc.DatabaseError:
        # Just drop table, table will be re-created by sqlalchemy and
        # data will be re-fetched
        saveddata_engine.execute("DROP TABLE prices;")
```

Which was first added in 2.8.0 as part of price optimization feature: https://github.com/pyfa-org/Pyfa/releases/tag/v2.8.0

As upgrade path suggests - just open database in SQLite DB browser and drop prices, it should fix your issue.

**Comment by DarkFenX** [comment]
@cbz did your issue get resolved by dropping the prices table?

**Comment by cbz** [comment]
Seems to work fine now, yes. Thanks.

**Comment by DarkFenX** [comment]
Ok, cool. I will look into database upgrade issues if I receive more reports like this.
