### ISSUE TITLE
Issue Opening Pyfa

### ISSUE THREAD

**Issue by razva00** [pyfa-org/Pyfa#1980]
## Bug Report

pyfa v2.9.3
EVE Data Version: 1492195 (2019-04-16 16:50:22)

OS version: Windows-10-10.0.17763-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.4 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.3
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
sqlite3.OperationalError: attempt to write a readonly database

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\projects\pyfa\pyfa.py", line 124, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\service\prefetch.py", line 39, in <module>
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\schema.py", line 4287, in create_all
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2033, in _run_visitor
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1607, in _run_visitor
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\visitors.py", line 131, in traverse_single
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\ddl.py", line 781, in visit_metadata
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\visitors.py", line 131, in traverse_single
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\ddl.py", line 826, in visit_table
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 988, in execute
  File "C:\Python36\lib\site-packages\sqlalchemy\sql\ddl.py", line 72, in _execute_on_connection
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1050, in _execute_ddl
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1466, in _handle_dbapi_exception
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 383, in raise_from_cause
  File "C:\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 128, in reraise
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
  File "C:\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) attempt to write a readonly database
[SQL: 
CREATE TABLE "boosterSideEffects" (
	"boosterID" INTEGER NOT NULL, 
	"effectID" INTEGER NOT NULL, 
	active BOOLEAN, 
	PRIMARY KEY ("boosterID", "effectID"), 
	FOREIGN KEY("boosterID") REFERENCES boosters ("ID"), 
	CHECK (active IN (0, 1))
)

]
(Background on this error at: http://sqlalche.me/e/e3q8)

### Detailed steps to reproduce:

Every time i try to open up Pyfa it gets me the bugg report posted above. I tried downloading from the exe...from the zip file... tried older versions..but everytime i get that report. Please help.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by DarkFenX** [comment]
Reboot and try again. Most likely something is locking your DB file (use folder\.pyfa\saveddata.db) and it's the easiest way to get rid of it.

**Comment by razva00** [comment]
DarkFenX - deleting the savedata.db in the user folder solved my issue.

Thank you so very much. It's sooo good to be using pyfa again after 2 years afg time. The ingame simulator felt so cold to me.

Thank you again.

**Comment by DarkFenX** [comment]
Hey, glad it helped! :D
