### ISSUE TITLE
Graphs are grayed out on winzip build

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#1998]
Reproduced on 2.9.4, win 8.1.

**Comment by Zap0** [comment]
can confirm - was confused. 2.9.4 on w7

**Comment by Stickerpants** [comment]
2.9.4 on w10, same bug. Previous build 2.9.3 worked fine for graphs.

**Comment by DarkFenX** [comment]
```
Traceback (most recent call last):
  File "C:\projects\pyfa\pyfa.py", line 132, in <module>
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\gui\mainFrame.py", line 41, in <module>
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\projects\pyfa\gui\graphFrame.py", line 40, in <module>
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Python36\lib\site-packages\matplotlib\__init__.py", line 138, in <module>
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Python36\lib\site-packages\matplotlib\cbook\__init__.py", line 31, in <module>
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Python36\lib\site-packages\numpy\__init__.py", line 150, in <module>
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
  File "C:\Python36\lib\site-packages\numpy\random\__init__.py", line 180, in <module>
  File "C:\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
  File "mtrand.pyx", line 1, in init numpy.random.mtrand
ModuleNotFoundError: No module named 'numpy.random.common'
```
Seems like more recent matplotlib versions have extra dependencies

**Comment by jasconius** [comment]
was NOT getting this in 2.9.4 but am now in 2.9.5

does a re-install fix it?

**Comment by DarkFenX** [comment]
No. It's an issue with packaging of updated plotting library.

**Comment by pilotchute** [comment]
Also appears on mac.

**Comment by DarkFenX** [comment]
FYI debugging of the issue is taking longer than expected. This is mostly because I cannot setup the same build environment as on appveyor - builds generated on my local machine import matplotlib successfully, and debugging via appveyor is very time-consuming.

**Comment by DarkFenX** [comment]
Did bisecting on zip builds today. 

good: https://ci.appveyor.com/project/blitzmann/pyfa/builds/24637171/artifacts
bad: https://ci.appveyor.com/project/blitzmann/pyfa/builds/24643433/artifacts

Logs show that between these two, matplotlib was updated from 3.0.3 to 3.1.0. This update did not affect exe build however, something broke it later.

**Comment by DarkFenX** [comment]
Done with exes.

good: https://ci.appveyor.com/project/blitzmann/pyfa/builds/26270676
bad: https://ci.appveyor.com/project/blitzmann/pyfa/builds/26277511

This one was broken by numpy update from 1.16.4 to 1.17.0 (which makes sense, as it's numpy packaging which gets broken according to traceback posted above),

**Comment by DarkFenX** [comment]
Fixed by forcing both matplotlib and numpy versions

**Comment by Stickerpants** [comment]
@DarkFenX Thank you for your work on this one - much appreciated!
