### ISSUE TITLE
Error Naming Fits

### ISSUE THREAD

**Issue by Brixer** [pyfa-org/Pyfa#2018]

**Comment by Brixer** [comment]
I received the following error message when naming a fit. The name I was using included the $ symbol:

pyfa v2.9.6
EVE Data Version: 1541099 (2019-07-27 01:32:22)

OS version: Windows-10-10.0.17134-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.6
Logbook version: 1.4.3
Requests version: 2.22.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 2508, in parse
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1939, in parseString
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1929, in parseString
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1669, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 4430, in parseImpl
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1669, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 4037, in parseImpl
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1673, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 3783, in parseImpl
pyparsing.ParseException: Expected end of text, found '$'  (at char 5), (line:1, col:6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\graphFrame.py", line 246, in OnFitChanged
  File "C:\projects\pyfa\gui\graphFrame.py", line 459, in draw
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 29, in draw
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\figure.py", line 1649, in draw
  File "C:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2628, in draw
  File "C:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\legend.py", line 636, in draw
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 250, in get_window_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 818, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\text.py", line 313, in _get_layout
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 214, in get_text_width_height_descent
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 3269, in parse
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 2513, in parse
ValueError: 
L4H Z$$ (Sacrilege)
     ^
Expected end of text, found '$'  (at char 5), (line:1, col:6)

####################

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 2508, in parse
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1939, in parseString
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1929, in parseString
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1669, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 4430, in parseImpl
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1669, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 4037, in parseImpl
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1673, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 3783, in parseImpl
pyparsing.ParseException: Expected end of text, found '$'  (at char 5), (line:1, col:6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\graphFrame.py", line 246, in OnFitChanged
  File "C:\projects\pyfa\gui\graphFrame.py", line 459, in draw
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 29, in draw
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\figure.py", line 1649, in draw
  File "C:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2628, in draw
  File "C:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\legend.py", line 636, in draw
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 250, in get_window_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 818, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\text.py", line 313, in _get_layout
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 214, in get_text_width_height_descent
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 3269, in parse
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 2513, in parse
ValueError: 
L4H Z$$ (Sacrilege)
     ^
Expected end of text, found '$'  (at char 5), (line:1, col:6)

####################

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 2508, in parse
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1939, in parseString
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1929, in parseString
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1669, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 4430, in parseImpl
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1669, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 4037, in parseImpl
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1673, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 3783, in parseImpl
pyparsing.ParseException: Expected end of text, found '$'  (at char 5), (line:1, col:6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\graphFrame.py", line 246, in OnFitChanged
  File "C:\projects\pyfa\gui\graphFrame.py", line 459, in draw
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 29, in draw
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\figure.py", line 1649, in draw
  File "C:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2628, in draw
  File "C:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\legend.py", line 636, in draw
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 250, in get_window_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 818, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\text.py", line 313, in _get_layout
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 214, in get_text_width_height_descent
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 3269, in parse
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 2513, in parse
ValueError: 
L4H Z$$ (Cerberus)
     ^
Expected end of text, found '$'  (at char 5), (line:1, col:6)

####################

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 2508, in parse
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1939, in parseString
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1929, in parseString
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1669, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 4430, in parseImpl
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1669, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 4037, in parseImpl
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1830, in _parseCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 1673, in _parseNoCache
  File "C:\Python36\lib\site-packages\pyparsing.py", line 3783, in parseImpl
pyparsing.ParseException: Expected end of text, found '$'  (at char 5), (line:1, col:6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\graphFrame.py", line 246, in OnFitChanged
  File "C:\projects\pyfa\gui\graphFrame.py", line 459, in draw
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_wxagg.py", line 29, in draw
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 402, in draw
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\figure.py", line 1649, in draw
  File "C:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\axes\_base.py", line 2628, in draw
  File "C:\Python36\lib\site-packages\matplotlib\image.py", line 138, in _draw_list_compositing_images
  File "C:\Python36\lib\site-packages\matplotlib\artist.py", line 50, in draw_wrapper
  File "C:\Python36\lib\site-packages\matplotlib\legend.py", line 636, in draw
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 250, in get_window_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 370, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 243, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in get_extent_offsets
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 439, in <listcomp>
  File "C:\Python36\lib\site-packages\matplotlib\offsetbox.py", line 818, in get_extent
  File "C:\Python36\lib\site-packages\matplotlib\text.py", line 313, in _get_layout
  File "C:\Python36\lib\site-packages\matplotlib\backends\backend_agg.py", line 214, in get_text_width_height_descent
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 3269, in parse
  File "C:\Python36\lib\site-packages\matplotlib\mathtext.py", line 2513, in parse
ValueError: 
L4H Z$$ (Cerberus)
     ^
Expected end of text, found '$'  (at char 5), (line:1, col:6)

**Comment by DarkFenX** [comment]
Does it happen when you open graph window, or everywhere?

**Comment by Brixer** [comment]
Just when a graph window is opened.

**Comment by DarkFenX** [comment]
Fixed in 663623dec6e1dcd25f3359d49dd634b37fd286fd
