### ISSUE TITLE
ESI Export: Unhandled exception when attempting to export a blank fitting

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#2027]
## Bug Report
Exception thrown when exporting blank fit to ESI

```pyfa v2.10.0
EVE Data Version: 1553210 (2019-08-20 12:26:35)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.7
Logbook version: 1.5.2
Requests version: 2.22.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\esiFittings.py", line 276, in exportFitting
  File "C:\projects\pyfa\service\port\port.py", line 305, in exportESI
  File "C:\projects\pyfa\service\port\esi.py", line 137, in exportESI
service.port.esi.ESIExportException: Cannot export fitting: module list cannot be empty.
```

### Detailed steps to reproduce:
Open a new fitting (any ship)
Attempt to export to ESI

### Release or development git branch? Please note the release version or commit hash:
v2.10.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by DarkFenX** [comment]
Fixed in 67462c32787963d6e7eb2a1aecba39f23205bf61
