### ISSUE TITLE
IndexError: index out of range

### ISSUE THREAD

**Issue by json-m** [pyfa-org/Pyfa#2032]
### Expected behavior:

pyfa shows cap change

### Actual behavior:

pyfa shows no cap change, and gives error popup

### Detailed steps to reproduce:

click anything after adding the cap injector/booster, get error popup

### Fits involved in EFT format (Edit > To Clipboard > EFT):

```
[Maelstrom, wormhololol]

[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]
[Empty Low slot]

Pith C-Type X-Large Shield Booster
X-Large Ancillary Shield Booster
Shield Boost Amplifier II
Heavy Electrochemical Capacitor Booster I, Navy Cap Booster 800
[Empty Med slot]
[Empty Med slot]

[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Large Core Defense Operational Solidifier II
[Empty Rig slot]
[Empty Rig slot]
```

### Release or development git branch? Please note the release version or commit hash:
release pyfa v2.10.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

latest windows 10 at date of opening this issue

### Other relevant information:

trace
```
pyfa v2.10.0
EVE Data Version: 1553210 (2019-08-20 10:26:35)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.7
Logbook version: 1.5.2
Requests version: 2.22.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\statsPane.py", line 79, in fitChanged
  File "C:\projects\pyfa\gui\builtinStatsViews\rechargeViewFull.py", line 114, in refreshPanel
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1396, in effectiveSustainableTank
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1386, in sustainableTank
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1409, in calculateSustainableTank
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1168, in capStable
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1278, in simulateCap
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1310, in __runCapSim
  File "C:\projects\pyfa\eos\capSim.py", line 165, in run
IndexError: index out of range

```

**Comment by DarkFenX** [comment]
> click anything after adding the cap injector/booster, get error popup

Not exactly like that. It happens when you have no active modules besides cap boosters in fit (i.e. you have to deactivate both shield boosters). Regression which appeared with fix of #2006.

Fixed in b469fa520e45a1e983f8bf3e96e6db098ce39a74.
