### ISSUE TITLE
Random error while editing a fit

### ISSUE THREAD

**Issue by Altarus94** [pyfa-org/Pyfa#2038]
Every time I made a change to the fit (new module, or swap slot, I got the error message)

Hope that can help you fix the issue :)

---

pyfa v2.11.0dev1
EVE Data Version: 1554178 (2019-08-22 14:27:48)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.7
Logbook version: 1.5.2
Requests version: 2.22.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\statsPane.py", line 79, in fitChanged
  File "C:\projects\pyfa\gui\builtinStatsViews\rechargeViewFull.py", line 114, in refreshPanel
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1396, in effectiveSustainableTank
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1386, in sustainableTank
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1409, in calculateSustainableTank
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1168, in capStable
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1278, in simulateCap
  File "C:\projects\pyfa\eos\saveddata\fit.py", line 1310, in __runCapSim
  File "C:\projects\pyfa\eos\capSim.py", line 165, in run
IndexError: index out of range

---

I was working on this fit:

[Redeemer, bridge]

Expanded Cargohold II
Expanded Cargohold II
Expanded Cargohold II
Expanded Cargohold II
Expanded Cargohold II
Expanded Cargohold II
Expanded Cargohold II

Large Micro Jump Drive
[Empty Med slot]
Heavy Electrochemical Capacitor Booster I, Navy Cap Booster 3200
Heavy Electrochemical Capacitor Booster I, Navy Cap Booster 3200

Improved Cloaking Device II
Covert Jump Portal Generator I
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]
[Empty High slot]

Large Cargohold Optimization II
Large Cargohold Optimization II

Ogre II x5

Navy Cap Booster 800 x35
Nanite Repair Paste x400

---

Release : 
V2.11.0dev1

Windows 10

**Comment by DarkFenX** [comment]
This is probably duplicate of #2032. Please check latest "main" build, 2.10.1, if issue is still there.

**Comment by Altarus94** [comment]
Seems to be the same issue yes.

And I got a mail every time a new release is up, but not for the last one, maybe du to the name. I'll update right away sir!

I confirm, I got the notification for the false dev release after updating for the last one

"pyfa v2.11.0dev1
August 22, 2019

This is a pre-release, be prepared for unstable features"

**Comment by DarkFenX** [comment]
Well, my bad then, but I cannot fix it now until the next major release (which is gonna happen alongside next EVE update).

**Comment by Altarus94** [comment]
No prob sir. I juste ignored it.

Problem solved!
