### ISSUE TITLE
Crash on startup after version update

### ISSUE THREAD

**Issue by Nacrana** [pyfa-org/Pyfa#2107]
After the recent update, the application wont start. Window does not appear.
Windows Logs:
Name der fehlerhaften Anwendung: pyfa.exe, Version: 0.0.0.0, Zeitstempel: 0x597f4ad5
Name des fehlerhaften Moduls: wxmsw30u_core_vc140.dll, Version: 3.0.5.0, Zeitstempel: 0x5ce4d80d
Ausnahmecode: 0xc0000005
Fehleroffset: 0x0009faca
ID des fehlerhaften Prozesses: 0x2eac
Startzeit der fehlerhaften Anwendung: 0x01d5b43fb27e65dd
Pfad der fehlerhaften Anwendung: C:\Users\xxx\xxx\Eve\pyfa\pyfa.exe
Pfad des fehlerhaften Moduls: C:\Users\xxx\xxx\Eve\pyfa\wxmsw30u_core_vc140.dll
Berichtskennung: 0a48308f-d7f4-477a-b7e5-e5378643d42a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

I did install Python 3.8 lately.
another instance of Pyfa has the same error.

**Comment by DarkFenX** [comment]
From which to which version you updated pyfa? Could you try older version? Could you try uninstalling python 3.8 and seeing if it works (not a solution, but a diagnostic measure)?

**Comment by Nacrana** [comment]
I did an update from 2.15.0 to 2.15.1.
I also did try a rollback. 
After that i tried an total new installation in a new folder. Same results sadly.
I did uninstall python 3.8, and tried the same from above again, error still persists.

**Comment by DarkFenX** [comment]
Looks like something changed on your environment. By the looks of it, it doesn't even get to python code. To confirm or deny that, please check `<your user>\.pyfa` folder for logs and see if anything is written in there on startup.

**Comment by Nacrana** [comment]
[2019-12-17 14:18:40.993847] INFO: __main__: Starting Pyfa
[2019-12-17 14:18:40.993847] INFO: __main__: 
[2019-12-17 14:18:40.993847] INFO: __main__: Writing log file to: C:\Users\Nacrana\.pyfa\pyfa.log
[2019-12-17 14:18:40.993847] INFO: __main__: Running in a frozen state.
[2019-12-17 14:18:41.038716] INFO: eos.db: Initializing database
[2019-12-17 14:18:41.038716] INFO: eos.db: Gamedata connection: sqlite:///C:\Users\Nacrana\Desktop\Eve\pyfa\eve.db?check_same_thread=False
[2019-12-17 14:18:41.038716] INFO: eos.db: Saveddata connection: sqlite:///C:\Users\Nacrana\.pyfa\saveddata.db?check_same_thread=False
[2019-12-17 14:18:41.038716] DEBUG: eos.db: Initializing gamedata
[2019-12-17 14:18:41.042709] DEBUG: eos.db: Getting gamedata version
[2019-12-17 14:18:41.048689] DEBUG: eos.db: Initializing saveddata
[2019-12-17 14:18:41.049686] DEBUG: eos.db: Importing gamedata DB scheme
[2019-12-17 14:18:41.101553] DEBUG: eos.db: Importing saveddata DB scheme
[2019-12-17 14:18:41.142446] DEBUG: eos.db: Importing gamedata queries
[2019-12-17 14:18:41.143440] DEBUG: eos.db: Importing saveddata queries
[2019-12-17 14:18:41.143440] DEBUG: service.prefetch: Run database migration.
[2019-12-17 14:18:41.152417] DEBUG: service.prefetch: Import Required Database Values.
[2019-12-17 14:18:41.218244] DEBUG: service.prefetch: Starting database validation.
[2019-12-17 14:18:41.218244] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for character skills.
[2019-12-17 14:18:41.219237] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned characters attached to fits.
[2019-12-17 14:18:41.220236] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned damage patterns attached to fits.
[2019-12-17 14:18:41.221233] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for missing damage pattern names.
[2019-12-17 14:18:41.222205] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for missing target resist names.
[2019-12-17 14:18:41.223230] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned drones items.
[2019-12-17 14:18:41.224224] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned cargo items.
[2019-12-17 14:18:41.225222] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned fighters items.
[2019-12-17 14:18:41.225222] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for orphaned modules items.
[2019-12-17 14:18:41.227216] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (em)
[2019-12-17 14:18:41.227216] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (thermal)
[2019-12-17 14:18:41.228215] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (kinetic)
[2019-12-17 14:18:41.229186] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null damagePatterns values. (explosive)
[2019-12-17 14:18:41.230183] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (em)
[2019-12-17 14:18:41.231180] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (thermal)
[2019-12-17 14:18:41.232205] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (kinetic)
[2019-12-17 14:18:41.233201] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for null targetResists values. (explosive)
[2019-12-17 14:18:41.234195] DEBUG: eos.db.saveddata.databaseRepair: Running database cleanup for duplicated selected ammo profiles.
[2019-12-17 14:18:41.235191] DEBUG: service.prefetch: Completed database validation.
[2019-12-17 14:18:43.775501] INFO: gui.bitmap_loader: Using zipped image files.
[2019-12-17 14:18:43.778468] DEBUG: gui.contextMenu: registering context menu class OpenFitInNewTab
[2019-12-17 14:18:43.778468] DEBUG: gui.contextMenu: registering context menu class AddBrowsedFits
[2019-12-17 14:18:43.781484] DEBUG: gui.contextMenu: registering context menu class AddCurrentlyOpenFit
[2019-12-17 14:18:43.781484] DEBUG: gui.contextMenu: registering context menu class AddEnvironmentEffect
[2019-12-17 14:18:43.915127] DEBUG: service.market: Initialize ShipBrowserWorkerThread.
[2019-12-17 14:18:43.986191] DEBUG: service.fit: Initialize Fit class
[2019-12-17 14:18:44.019909] DEBUG: service.fit: Getting fits with modules
[2019-12-17 14:18:44.065787] DEBUG: gui.contextMenu: registering context menu class AddCommandFit
[2019-12-17 14:18:44.066784] DEBUG: gui.contextMenu: registering context menu class TargetProfileAdder
[2019-12-17 14:18:44.066784] DEBUG: gui.contextMenu: registering context menu class ChangeShipTacticalMode
[2019-12-17 14:18:44.066784] DEBUG: gui.contextMenu: registering context menu class ChangeModuleAmmo
[2019-12-17 14:18:44.067781] DEBUG: gui.contextMenu: registering context menu class ChangeModuleSpool
[2019-12-17 14:18:44.067781] DEBUG: gui.contextMenu: registering context menu class BoosterSideEffects
[2019-12-17 14:18:44.067781] DEBUG: gui.contextMenu: registering context menu class FighterAbilities
[2019-12-17 14:18:44.068779] DEBUG: gui.contextMenu: registering context menu class TargetWrapperResists
[2019-12-17 14:18:44.069776] DEBUG: gui.contextMenu: registering context menu class TargetProfileEditorMenu
[2019-12-17 14:18:44.125514] DEBUG: gui.contextMenu: registering context menu class ItemStats
[2019-12-17 14:18:44.126511] DEBUG: gui.contextMenu: registering context menu class JumpToMarketItem
[2019-12-17 14:18:44.126511] DEBUG: gui.contextMenu: registering context menu class FitSystemSecurityMenu
[2019-12-17 14:18:44.126511] DEBUG: gui.contextMenu: registering context menu class JumpToShip
[2019-12-17 14:18:44.126511] DEBUG: gui.contextMenu: registering context menu class RemoveItem
[2019-12-17 14:18:44.127509] DEBUG: gui.contextMenu: registering context menu class ChangeItemAmount
[2019-12-17 14:18:44.127509] DEBUG: gui.contextMenu: registering context menu class ChangeItemProjectionRange
[2019-12-17 14:18:44.127509] DEBUG: gui.contextMenu: registering context menu class DroneSplitStack
[2019-12-17 14:18:44.128506] DEBUG: gui.contextMenu: registering context menu class ChangeItemToVariation
[2019-12-17 14:18:44.128506] DEBUG: gui.contextMenu: registering context menu class ChangeModuleMutation
[2019-12-17 14:18:44.128506] DEBUG: gui.contextMenu: registering context menu class FillWithModule
[2019-12-17 14:18:44.141472] DEBUG: gui.contextMenu: registering context menu class ExportMutatedModule
[2019-12-17 14:18:44.142469] DEBUG: gui.contextMenu: registering context menu class ChangeAffectingSkills
[2019-12-17 14:18:44.142469] DEBUG: gui.contextMenu: registering context menu class FillWithItem
[2019-12-17 14:18:44.142469] DEBUG: gui.contextMenu: registering context menu class DroneAddStack
[2019-12-17 14:18:44.142469] DEBUG: gui.contextMenu: registering context menu class AddToCargo
[2019-12-17 14:18:44.143467] DEBUG: gui.contextMenu: registering context menu class AddToCargoAmmo
[2019-12-17 14:18:44.143467] DEBUG: gui.contextMenu: registering context menu class ProjectItem
[2019-12-17 14:18:44.143467] DEBUG: gui.contextMenu: registering context menu class AmmoToDmgPattern
[2019-12-17 14:18:44.144463] DEBUG: gui.contextMenu: registering context menu class AddImplantSet
[2019-12-17 14:18:44.144463] DEBUG: gui.contextMenu: registering context menu class DronesPrice
[2019-12-17 14:18:44.144463] DEBUG: gui.contextMenu: registering context menu class CargoPrice
[2019-12-17 14:18:44.144463] DEBUG: gui.contextMenu: registering context menu class ImplantBoosterPrice
[2019-12-17 14:18:44.145461] DEBUG: gui.contextMenu: registering context menu class ChangeDamagePattern
[2019-12-17 14:18:44.145461] DEBUG: gui.contextMenu: registering context menu class FactorReload
[2019-12-17 14:18:44.145461] DEBUG: gui.contextMenu: registering context menu class TargetProfileSwitcher
[2019-12-17 14:18:44.146458] DEBUG: gui.contextMenu: registering context menu class GraphDmgApplyProjectedMenu
[2019-12-17 14:18:44.146458] DEBUG: gui.contextMenu: registering context menu class GraphDmgIgnoreResistsMenu
[2019-12-17 14:18:44.146458] DEBUG: gui.contextMenu: registering context menu class GraphIgnoreLockRangeMenu
[2019-12-17 14:18:44.146458] DEBUG: gui.contextMenu: registering context menu class GraphIgnoreDcrMenu
[2019-12-17 14:18:44.147455] DEBUG: gui.contextMenu: registering context menu class GraphDmgDroneModeMenu
[2019-12-17 14:18:44.147455] DEBUG: gui.contextMenu: registering context menu class AdditionsExportAll
[2019-12-17 14:18:44.147455] DEBUG: gui.contextMenu: registering context menu class AdditionsExportAll
[2019-12-17 14:18:44.147455] DEBUG: gui.contextMenu: registering context menu class AdditionsImport
[2019-12-17 14:18:44.235751] DEBUG: gui.statsPane: Setting full view for: resources
[2019-12-17 14:18:44.235751] DEBUG: gui.statsPane: Setting full view for: resistances
[2019-12-17 14:18:44.235751] DEBUG: gui.statsPane: Setting full view for: recharge
[2019-12-17 14:18:44.235751] DEBUG: gui.statsPane: Setting full view for: firepower
[2019-12-17 14:18:44.235751] DEBUG: gui.statsPane: Setting full view for: outgoing
[2019-12-17 14:18:44.235751] DEBUG: gui.statsPane: Setting full view for: capacitor
[2019-12-17 14:18:44.235751] DEBUG: gui.statsPane: Setting minimal view for: targetingMisc
[2019-12-17 14:18:44.235751] DEBUG: gui.statsPane: Setting full view for: price
[2019-12-17 14:18:44.363724] DEBUG: gui.mainFrame: Done loading mainframe imports
[2019-12-17 14:18:44.382673] DEBUG: gui.mainFrame: Initialize MainFrame
[2019-12-17 14:18:44.393644] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/pyfa@1x.png
[2019-12-17 14:18:44.401651] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/ctabadd@1x.png
[2019-12-17 14:18:44.416636] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/drone_small@1x.png
[2019-12-17 14:18:44.416636] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/fighter_small@1x.png
[2019-12-17 14:18:44.417633] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/implant_small@1x.png
[2019-12-17 14:18:44.418630] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/booster_small@1x.png
[2019-12-17 14:18:44.418630] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/projected_small@1x.png
[2019-12-17 14:18:44.418630] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/fleet_fc_small@1x.png
[2019-12-17 14:18:44.418630] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/cargo_small@1x.png
[2019-12-17 14:18:44.419628] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/skill_small@1x.png
[2019-12-17 14:18:44.438592] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1391@1x.png
[2019-12-17 14:18:44.438592] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1391.png
[2019-12-17 14:18:44.438592] WARNING: gui.bitmap_loader: Missing icon file: icons/1391.png
[2019-12-17 14:18:44.439574] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/column_misc@1x.png
[2019-12-17 14:18:44.441597] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1389@1x.png
[2019-12-17 14:18:44.441597] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1389.png
[2019-12-17 14:18:44.441597] WARNING: gui.bitmap_loader: Missing icon file: icons/1389.png
[2019-12-17 14:18:44.441597] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/totalPrice_small@1x.png
[2019-12-17 14:18:44.472051] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/ctableft@1x.png
[2019-12-17 14:18:44.473073] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/ctabmiddle@1x.png
[2019-12-17 14:18:44.473073] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/ctabright@1x.png
[2019-12-17 14:18:44.473073] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/ctabclose@1x.png
[2019-12-17 14:18:44.513964] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/ship_small@1x.png
[2019-12-17 14:18:44.516955] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/67@1x.png
[2019-12-17 14:18:44.516955] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/67.png
[2019-12-17 14:18:44.516955] WARNING: gui.bitmap_loader: Missing icon file: icons/67.png
[2019-12-17 14:18:44.532913] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/2224@1x.png
[2019-12-17 14:18:44.533910] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/2224.png
[2019-12-17 14:18:44.533910] WARNING: gui.bitmap_loader: Missing icon file: icons/2224.png
[2019-12-17 14:18:44.573150] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/damagePattern_small@1x.png
[2019-12-17 14:18:44.634148] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/market_small@1x.png
[2019-12-17 14:18:44.635145] DEBUG: gui.marketBrowser: Initialize marketBrowser
[2019-12-17 14:18:44.636142] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/fit_delete_small@1x.png
[2019-12-17 14:18:44.637118] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/fsearch_small@1x.png
[2019-12-17 14:18:44.640110] DEBUG: gui.builtinMarketBrowser.marketTree: Initialize marketTree
[2019-12-17 14:18:44.644133] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/16@1x.png
[2019-12-17 14:18:44.645122] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/16.png
[2019-12-17 14:18:44.645122] WARNING: gui.bitmap_loader: Missing icon file: icons/16.png
[2019-12-17 14:18:44.646094] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/3203@1x.png
[2019-12-17 14:18:44.646094] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/3203.png
[2019-12-17 14:18:44.646094] WARNING: gui.bitmap_loader: Missing icon file: icons/3203.png
[2019-12-17 14:18:44.646094] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/3641@1x.png
[2019-12-17 14:18:44.646094] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/3641.png
[2019-12-17 14:18:44.646094] WARNING: gui.bitmap_loader: Missing icon file: icons/3641.png
[2019-12-17 14:18:44.647092] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/2563@1x.png
[2019-12-17 14:18:44.647092] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/2563.png
[2019-12-17 14:18:44.647092] WARNING: gui.bitmap_loader: Missing icon file: icons/2563.png
[2019-12-17 14:18:44.647092] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/21561@1x.png
[2019-12-17 14:18:44.647092] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/21561.png
[2019-12-17 14:18:44.647092] WARNING: gui.bitmap_loader: Missing icon file: icons/21561.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/2887@1x.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/2887.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file: icons/2887.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1084@1x.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1084.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file: icons/1084.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1432@1x.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1432.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file: icons/1432.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1299@1x.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1299.png
[2019-12-17 14:18:44.648113] WARNING: gui.bitmap_loader: Missing icon file: icons/1299.png
[2019-12-17 14:18:44.658087] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/pg_small@1x.png
[2019-12-17 14:18:44.661121] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1405@1x.png
[2019-12-17 14:18:44.661121] WARNING: gui.bitmap_loader: Missing icon file from zip: icons/1405.png
[2019-12-17 14:18:44.661121] WARNING: gui.bitmap_loader: Missing icon file: icons/1405.png
[2019-12-17 14:18:44.662111] DEBUG: gui.builtinMarketBrowser.itemView: Initialize ItemView
[2019-12-17 14:18:44.674110] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/frewind_small@1x.png
[2019-12-17 14:18:44.674110] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/fforward_small@1x.png
[2019-12-17 14:18:44.674110] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/fit_add_small@1x.png
[2019-12-17 14:18:44.675103] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/freset_small@1x.png
[2019-12-17 14:18:44.675103] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/fit_switch_view_mode_small@1x.png
[2019-12-17 14:18:44.675103] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/frecent_small@1x.png
[2019-12-17 14:18:44.681061] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/up-arrow2@1x.png
[2019-12-17 14:18:44.681061] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_amarr_small@1x.png
[2019-12-17 14:18:44.681061] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_caldari_small@1x.png
[2019-12-17 14:18:44.682058] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_gallente_small@1x.png
[2019-12-17 14:18:44.682058] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_minmatar_small@1x.png
[2019-12-17 14:18:44.682058] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_sisters_small@1x.png
[2019-12-17 14:18:44.682058] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_ore_small@1x.png
[2019-12-17 14:18:44.682058] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_serpentis_small@1x.png
[2019-12-17 14:18:44.683056] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_angel_small@1x.png
[2019-12-17 14:18:44.683056] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_blood_small@1x.png
[2019-12-17 14:18:44.683056] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_sansha_small@1x.png
[2019-12-17 14:18:44.683056] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_guristas_small@1x.png
[2019-12-17 14:18:44.683056] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_mordu_small@1x.png
[2019-12-17 14:18:44.683056] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_jove_small@1x.png
[2019-12-17 14:18:44.684053] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_upwell_small@1x.png
[2019-12-17 14:18:44.684053] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_triglavian_small@1x.png
[2019-12-17 14:18:44.684053] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_triglavian_small.png
[2019-12-17 14:18:44.684053] WARNING: gui.bitmap_loader: Missing icon file: gui/race_triglavian_small.png
[2019-12-17 14:18:44.684053] CRITICAL: gui.errorDialog: 

Traceback (most recent call last):
  File "C:\projects\pyfa\pyfa.py", line 143, in <module>
  File "C:\projects\pyfa\gui\mainFrame.py", line 176, in __init__
  File "C:\projects\pyfa\gui\shipBrowser.py", line 62, in __init__
  File "C:\projects\pyfa\gui\builtinShipBrowser\raceSelector.py", line 75, in __init__
  File "C:\projects\pyfa\gui\builtinShipBrowser\raceSelector.py", line 162, in RebuildRaces
  File "C:\projects\pyfa\gui\builtinShipBrowser\raceSelector.py", line 116, in CalcButtonsBarPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

**Comment by DarkFenX** [comment]
> [2019-12-17 14:18:43.775501] INFO: gui.bitmap_loader: Using zipped image files.

Uhhh. Unsure why it does that. What kind of Windows pyfa package did you use, exe or zip?

**Comment by Nacrana** [comment]
I did both in the end. I used before those crashed always the .zip.

**Comment by DarkFenX** [comment]
https://github.com/pyfa-org/Pyfa/releases/tag/v2.11.1 try this version. If it works, check if https://github.com/pyfa-org/Pyfa/releases/tag/v2.12.0 breaks.

**Comment by Nacrana** [comment]
i renamed the .pyfa folder, unpacked 2.11.1, works. 
i patched it to 2.12.0, works.
i patched it to 2.15.1, still works.
Okay, i do i get my old saved fitting in it? The toons i don't really care.
Thanks for your fast help.

**Comment by DarkFenX** [comment]
huh... magic. Glad that it helped. No idea what was the cause, though. Maybe some files which were in your old `.pyfa` folder.
