### ISSUE TITLE
Sirens generate errors after 2.16.0 update

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#2118]
A super with sirens which had MWD ability active before the db update:
```
pyfa v2.16.0
EVE Data Version: 1646988 (2020-01-16 14:39:23)

OS version: Linux-5.4.0-2-amd64-x86_64-with-debian-bullseye-sid
Python version: 3.7.6 (default, Dec 19 2019, 09:25:23) 
[GCC 9.2.1 20191130]
wxPython version: 4.0.7 (wxWidgets 3.0.4)
SQLAlchemy version: 1.3.7
Logbook version: 1.4.0
Requests version: 2.22.0
Dateutil version: 2.7.3

####################

Traceback (most recent call last):
  File "/home/av/Workspace/eve/pyfa/gui/statsPane.py", line 79, in fitChanged
    view.refreshPanel(fit)
  File "/home/av/Workspace/eve/pyfa/gui/builtinStatsViews/firepowerViewFull.py", line 211, in refreshPanel
    val = val() if fit is not None else None
  File "/home/av/Workspace/eve/pyfa/gui/builtinStatsViews/firepowerViewFull.py", line 191, in <lambda>
    lambda: fit.getDroneDps(),
  File "/home/av/Workspace/eve/pyfa/eos/saveddata/fit.py", line 347, in getDroneDps
    self.calculateDroneDmgStats()
  File "/home/av/Workspace/eve/pyfa/eos/saveddata/fit.py", line 1601, in calculateDroneDmgStats
    droneVolley += fighter.getVolley(targetProfile=self.targetProfile)
  File "/home/av/Workspace/eve/pyfa/eos/saveddata/fighter.py", line 219, in getVolley
    volleyParams = self.getVolleyParametersPerEffect(targetProfile=targetProfile)
  File "/home/av/Workspace/eve/pyfa/eos/saveddata/fighter.py", line 199, in getVolleyParametersPerEffect
    self.__baseVolley[ability.effectID] = {0: ability.getVolley()}
  File "/home/av/Workspace/eve/pyfa/eos/saveddata/fighterAbility.py", line 118, in getVolley
    if not self.dealsDamage or not self.active:
  File "/home/av/Workspace/eve/pyfa/eos/saveddata/fighterAbility.py", line 84, in dealsDamage
    attr = "{}DamageMultiplier".format(self.attrPrefix)
  File "/home/av/Workspace/eve/pyfa/eos/saveddata/fighterAbility.py", line 80, in attrPrefix
    return self.__effect.getattr('prefix')
AttributeError: 'NoneType' object has no attribute 'getattr'
```

**Comment by DarkFenX** [comment]
Fixed in f6d33a2ac145366be3e6b0420f31c3682687d965
