### ISSUE TITLE
Fatal error! Failed to execute script pyfa - right after launch

### ISSUE THREAD

**Issue by maullerz** [pyfa-org/Pyfa#2120]
log:
----
```
...
[2020-01-19 14:24:09.170000] WARNING: gui.bitmap_loader: Missing icon file from zip: gui/race_triglavian_small.png
[2020-01-19 14:24:09.170000] WARNING: gui.bitmap_loader: Missing icon file: gui/race_triglavian_small.png
[2020-01-19 14:24:09.170000] CRITICAL: gui.errorDialog: 

Traceback (most recent call last):
  File "C:\projects\pyfa\pyfa.py", line 143, in <module>
  File "C:\projects\pyfa\gui\mainFrame.py", line 176, in __init__
  File "C:\projects\pyfa\gui\shipBrowser.py", line 62, in __init__
  File "C:\projects\pyfa\gui\builtinShipBrowser\raceSelector.py", line 75, in __init__
  File "C:\projects\pyfa\gui\builtinShipBrowser\raceSelector.py", line 162, in RebuildRaces
  File "C:\projects\pyfa\gui\builtinShipBrowser\raceSelector.py", line 116, in CalcButtonsBarPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'
```
----

Windows 7
tried versions of pyfa: v2.16.0 / v2.15.1

**Comment by DarkFenX** [comment]
https://github.com/pyfa-org/Pyfa/blob/master/imgs/gui/race_triglavian_small.png

Icon is there, so it's kinda weird. Please upload pyfa log somewhere (written to your `<user>\.pyfa\` folder. Most likely it tries to use zipped images for some reason which normally should not happen.

**Comment by DarkFenX** [comment]
https://github.com/pyfa-org/Pyfa/issues/2107 read through this issue. Might have the same solution.

**Comment by maullerz** [comment]
renamed '.pyfa' directory and installed v2.16 again
log file:
[pyfa-2020-01-20.log](https://github.com/pyfa-org/Pyfa/files/4087728/pyfa-2020-01-20.log)

**Comment by maullerz** [comment]
oh, i finally found the issue after checking the diff between files for my pyfa main folder and *.zip bundle.
i had imgs.zip file in my pyfa main folder, after renaming it, the pyfa was started successfully.

**Comment by DarkFenX** [comment]
What distribution did you use? Exe or zip?

**Comment by maullerz** [comment]
It was exe distr i have used always.

вт, 21 янв. 2020 г. в 11:29, Anton Vorobyov <notifications@github.com>:

**Comment by DarkFenX** [comment]
Could you tell where did you have imgs.zip? Just in `C:\Program Files (x86)\pyfa\imgs.zip`?

**Comment by maullerz** [comment]
Yes, exactly

вт, 21 янв. 2020 г. в 12:36, Anton Vorobyov <notifications@github.com>:

**Comment by DarkFenX** [comment]
Might be left-over from previous installations. Which is pretty weird, considering uninstaller should've handled its installation.

Anyway modern releases do not have this file, and loading images from zip is disabled in `config.py` by setting `imgsZIP` to None. So your installation somehow overrode the setting (which is possible if you have `configforced.py` somewhere) and had the file in place. Should not be an issue with fresh installations, so I am closing this issue.
