### ISSUE TITLE
Main window stays white after opening a fit and getting an error

### ISSUE THREAD

**Issue by Alfaksan** [pyfa-org/Pyfa#2158]
## Bug Report

When opening any fit, I'm getting this error message

--------

pyfa v2.19.0
EVE Data Version: 1701385 (2020-04-06 13:49:36)

OS version: Windows-10-10.0.14393-SP0
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.15
Logbook version: 1.5.3
Requests version: 2.23.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 623, in fitChanged
  File "gui\builtinViews\fittingView.py", line 754, in refresh
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 465, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1119, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 284, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3358, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3327, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3403, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3428, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (24427,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\statsPane.py", line 79, in fitChanged
  File "gui\builtinStatsViews\priceViewFull.py", line 83, in refreshPanel
  File "service\price.py", line 176, in getPrices
  File "eos\gamedata.py", line 465, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1119, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 284, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3358, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3327, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3403, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3428, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (3049,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\cargoView.py", line 170, in fitChanged
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 465, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1119, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 284, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3358, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3327, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3403, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3428, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (12824,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\droneView.py", line 234, in fitChanged
  File "gui\display.py", line 263, in update
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 465, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1119, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 284, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3358, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3327, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3403, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3428, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 588, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (2173,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

-------

It looks like the fit opens - stats are displayed, I even can delete by drawing a selection box over white fit space and hitting delete button

I've tried reinstalling pyfa and I'm still getting this error

I found similar issue (https://github.com/pyfa-org/Pyfa/issues/1967), but the proposed solution doesn't work - I don't even have the prices table

**Comment by DarkFenX** [comment]
Seems like one of DB migrations did not work for you.

If you do not have any valuable fits, just delete `<user folder>\.pyfa\saveddata.db`. Otherwise, send it to `phoenix@mail.ru` and i will repair it manually.

**Comment by Alfaksan** [comment]
Now i'm feeling stupid - turns out eve.db is not the file that I had to check. Dropped prices table from saveddata.db and everything works now. Thanks!
