### ISSUE TITLE
Error launching pyfa

### ISSUE THREAD

**Issue by versoth** [pyfa-org/Pyfa#2187]
pyfa v2.20.3
EVE Data Version: 1706308 (2020-04-15 04:32:35)

OS version: Windows-7-6.1.7601-SP1
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.16
Logbook version: 1.5.3
Requests version: 2.23.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 623, in fitChanged
  File "gui\builtinViews\fittingView.py", line 754, in refresh
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (2420,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\statsPane.py", line 79, in fitChanged
  File "gui\builtinStatsViews\priceViewFull.py", line 83, in refreshPanel
  File "service\price.py", line 176, in getPrices
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (19550,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\boosterView.py", line 133, in fitChanged
  File "gui\display.py", line 263, in update
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (36912,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\implantView.py", line 207, in fitChanged
  File "gui\display.py", line 263, in update
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (20499,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\cargoView.py", line 170, in fitChanged
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (28668,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 623, in fitChanged
  File "gui\builtinViews\fittingView.py", line 754, in refresh
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (2420,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\statsPane.py", line 79, in fitChanged
  File "gui\builtinStatsViews\priceViewFull.py", line 83, in refreshPanel
  File "service\price.py", line 176, in getPrices
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (19550,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\boosterView.py", line 133, in fitChanged
  File "gui\display.py", line 263, in update
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (36912,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\implantView.py", line 207, in fitChanged
  File "gui\display.py", line 263, in update
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (20499,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\cargoView.py", line 170, in fitChanged
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 435, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1004, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1121, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 287, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3360, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3329, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3405, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3430, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 984, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 293, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1103, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1288, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1482, in _handle_dbapi_exception

let me know what else you need
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1248, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 590, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (28668,)]
(Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by DarkFenX** [comment]
either delete `<user folder>\.pyfa\saveddata.db` (but this destroys all the data you had), or give this file to me (`phoenix@mail.ru`) and i will repair it.
