### ISSUE TITLE
Pyfa crashing when trying to open this one fit

### ISSUE THREAD

**Issue by muleooo** [pyfa-org/Pyfa#2205]
## Bug Report
I have one raven fit that crashes pyfa when I try to open or delete it. Also when I try to backup all fits, it hangs on a raven

### Expected behavior:
Normal interaction with a fit

### Actual behavior:
Error!

### Release or development git branch? Please note the release version or commit hash:
2.22.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

### Other relevant information:
```
pyfa v2.22.1
EVE Data Version: 1751741 (2020-06-18 12:35:35)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.17
Logbook version: 1.5.3
Requests version: 2.24.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 91, in fitSelected
  File "gui\builtinViews\fittingView.py", line 346, in fitSelected
  File "gui\builtinViews\fittingView.py", line 591, in slotsChanged
  File "gui\builtinViews\fittingView.py", line 542, in generateMods
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 509, in clear
  File "eos\saveddata\fit.py", line 298, in modules
  File "site-packages\sqlalchemy\orm\attributes.py", line 287, in __get__
  File "site-packages\sqlalchemy\orm\attributes.py", line 723, in get
  File "site-packages\sqlalchemy\orm\strategies.py", line 750, in _load_for_state
  File "<string>", line 1, in <lambda>
  File "site-packages\sqlalchemy\orm\strategies.py", line 892, in _emit_lazyload
  File "site-packages\sqlalchemy\ext\baked.py", line 545, in all
  File "site-packages\sqlalchemy\orm\loading.py", line 101, in instances
  File "site-packages\sqlalchemy\util\langhelpers.py", line 69, in __exit__
  File "site-packages\sqlalchemy\util\compat.py", line 178, in raise_
  File "site-packages\sqlalchemy\orm\loading.py", line 81, in instances
  File "site-packages\sqlalchemy\orm\loading.py", line 81, in <listcomp>
  File "site-packages\sqlalchemy\orm\loading.py", line 602, in _instance
  File "site-packages\sqlalchemy\event\attr.py", line 322, in __call__
  File "site-packages\sqlalchemy\orm\mapper.py", line 3378, in _event_on_load
  File "eos\saveddata\module.py", line 119, in init
  File "eos\db\gamedata\queries.py", line 133, in getItemWithBaseItemAttribute
AttributeError: 'NoneType' object has no attribute 'attributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 363, in OnEnterWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 363, in OnEnterWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 363, in OnEnterWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 363, in OnEnterWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 363, in OnEnterWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 363, in OnEnterWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 363, in OnEnterWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 363, in OnEnterWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'

####################

Traceback (most recent call last):
  File "gui\builtinShipBrowser\sfBrowserItem.py", line 369, in OnLeaveWindow
  File "gui\builtinShipBrowser\fitItem.py", line 559, in Refresh
  File "service\fit.py", line 348, in getFit
  File "service\fit.py", line 529, in recalc
  File "eos\saveddata\fit.py", line 522, in clear
  File "eos\saveddata\module.py", line 891, in clear
  File "eos\saveddata\module.py", line 400, in itemModifiedAttributes
AttributeError: 'Module' object has no attribute '_Module__itemModifiedAttributes'
```

**Comment by blitzmann** [comment]
It's been a while since I delved into the database code here, but it looks like there's a module that's failing to load for whatever reason. Various properties aren't being set.

Actually, looks like it's a mutaplasmid. Perhaps the attributes for it never got saved correctly... Would you mind sending a copy of your database to my email: holmes.ryan.90+pyfa@gmail.com

**Comment by muleooo** [comment]
Sent you a mail, that would be great

**Comment by blitzmann** [comment]
So, here's what I've found so far:

**Comment by blitzmann** [comment]
So here's what I've found so far:

![image](https://user-images.githubusercontent.com/3904767/85606538-4372e280-b621-11ea-9696-d531a65a46d1.png)

That fit has an abyssal module on it (XL Abyssal Shield Booster). The Abyssal module is coming back fine, but the base module that it's based on (the normal shield booster) is not. It looks like item ID 10886 doesn't exist in the database, but your fitting database thinks it should. Since we can't find the base item, we can't g et the base attributes, and things  just blow up

@DarkFenX do you know of recent-ish changes that removed / converted some modules from the game? I'm still trying to get a bit back up to speed with things here, and haven't been keeping track at all. I downloaded an old (~April) release and looked in the eve.db and can't find this ID.

It's either that, or something somewhere got crossed and the wrong value got stored. This is a bit concerning, but if no one else is reporting an issue, maybe just a fluke that we don't need to investigate further.

**Comment by muleooo** [comment]
Yeah that should be an XL ASB, and 10886 is apparently a "X-Large Converse Deflection Catalyzer" which I've never heard of :S
https://everef.net/type/10886

**Comment by blitzmann** [comment]
Aha

https://github.com/pyfa-org/Pyfa/blob/master/eos/db/migrations/upgrade36.py#L27

Yep, looks like it was a converted module. That script should migrate user databases to the proper conversion, but it looks like it doesn't consider `baseItemID`, only `itemID`

We should do a one-time conversion for baseItem wherever we've done these other conversions, and then moving forward keep baseItemID in mind
