### ISSUE TITLE
SQLAlchemy: Unable to open database file

### ISSUE THREAD

**Issue by palmettos** [pyfa-org/Pyfa#2257]
### Expected behavior:
Per [this wiki page on using eos,](https://github.com/pyfa-org/Pyfa/wiki/Using-pyfa's-engine) the following simple code should return an initialized Ship object:
```python
from eos.db.gamedata import queries
from eos.saveddata.ship import Ship

rifter = queries.getItem('Rifter')
s_rifter = Ship(rifter)
```

### Actual behavior:
The following exception is thrown:
```
Traceback (most recent call last):
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 239, in _do_get
    return self._create_connection()
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_eos.py", line 5, in <module>
    s_rifter = Ship(rifter)
  File "/home/palmettos/Documents/Code/Pyfa/eos/saveddata/ship.py", line 55, in __init__
    self.__itemModifiedAttributes.overrides = self.item.overrides
  File "/home/palmettos/Documents/Code/Pyfa/eos/gamedata.py", line 280, in overrides
    overrides = eos.db.getOverrides(self.ID)
  File "/home/palmettos/Documents/Code/Pyfa/eos/db/saveddata/queries.py", line 515, in getOverrides
    return saveddata_session.query(Override).filter(Override.itemID == itemID).all()
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3341, in all
    return list(self)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3503, in __iter__
    return self._execute_and_instances(context)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3524, in _execute_and_instances
    conn = self._get_bind_args(
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3539, in _get_bind_args
    return fn(
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3518, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1138, in connection
    return self._connection_for_bind(
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 1146, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2305, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2342, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    return fn()
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/impl.py", line 239, in _do_get
    return self._create_connection()
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 178, in raise_
    raise exception
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/palmettos/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

### Detailed steps to reproduce:
Setup environment following [these steps](https://github.com/Gochim/Pyfa/blob/master/CONTRIBUTING.md), run `db_update.py`, then run the above code

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
Current master

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Ubuntu 20.04

### Other relevant information:
N/A

**Comment by palmettos** [comment]
Well, here's the issue:
Somehow this path is showing up in the logs: `sqlite:////home/palmettos/.pyfa/saveddata.db`. However, after debugging the application, the actual value of `eos.config.saveddata_connectionstring` is `sqlite:////home/palmettos/Documents/Code/Pyfa/saveddata/saveddata.db`. Moving the db file to this location fixes the problem.

**Comment by DarkFenX** [comment]
Is it code modified by maintainer?

Pyfa has following code:
```
def getPyfaRoot():
    if hasattr(sys, '_MEIPASS'):
        return sys._MEIPASS
    base = getattr(sys.modules['__main__'], "__file__", sys.executable) if isFrozen() else __file__
    root = os.path.dirname(os.path.realpath(os.path.abspath(base)))
    root = root
    return root
...
    pyfaPath = getattr(configforced, "pyfaPath", pyfaPath)
    if pyfaPath is None:
        pyfaPath = getPyfaRoot()
    ...
    gameDB = getattr(configforced, "gameDB", gameDB)
    if not gameDB:
        gameDB = os.path.join(pyfaPath, "eve.db")
    ...
    eos.config.gamedata_connectionstring = "sqlite:///" + gameDB + "?check_same_thread=False"
```

**Comment by palmettos** [comment]
Now that I've had more time to digest this: the wiki page _does_ say something about the path to the db file being different when eos is imported directly, though it doesn't say anything about manually setting up files there. The instructions are just not very detailed, and as someone who never looked at Pyfa's source at all before this, I pretty much skimmed right over that part without knowing it would be a point of failure. I don't mind updating the docs when I have a chance.

**Comment by blitzmann** [comment]
@palmettos that wiki page is based on a comment I wrote in this thread: #1212. That was a couple years ago, and things have probably changed (not only that, I created that sample script ad hoc, and I may have some path settings that allowed it to work for me but might not be set up correctly for others).

We technically don't officially support running `eos` by itself. We try our best to make sure it can be, since there are a bunch of folks that do use it to hook into fitting calculations for their own projects, but it's supplied in a sort of `as-is` state and thus things like the wiki page on this just don't get updated.

One thing I'm noticed in your example is that you don't 
```python

import eos
import eos.db

```
at the very beginning. IIRC, this are required for certain things to be set correctly (like config). I haven't tried in a long while running eos by itself, so I'm unsure. If you find a good solution tho, please feel free to update the wiki 😁
