### ISSUE TITLE
Wanted to plan a Raitaru and failed

### ISSUE THREAD

**Issue by SKYMEMiC** [pyfa-org/Pyfa#2274]
pyfa v2.28.2
EVE Data Version: 1805757 (2020-09-16 09:08:55)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.19
Logbook version: 1.5.3
Requests version: 2.24.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 91, in fitSelected
  File "gui\builtinViews\fittingView.py", line 346, in fitSelected
  File "gui\builtinViews\fittingView.py", line 594, in slotsChanged
  File "gui\builtinViews\fittingView.py", line 555, in generateMods
  File "gui\builtinViews\fittingView.py", line 555, in <lambda>
ValueError: None is not in list

####################

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 195, in OnMouseMove
IndexError: list index out of range

####################

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 195, in OnMouseMove
IndexError: list index out of range

####################

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 195, in OnMouseMove
IndexError: list index out of range

####################

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 195, in OnMouseMove
IndexError: list index out of range

####################

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 195, in OnMouseMove
IndexError: list index out of range

####################

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 195, in OnMouseMove
IndexError: list index out of range

**Comment by DarkFenX** [comment]
Please tell me what you were trying to do. I am unable to reproduce when creating blank raitaru fit. And looking at the code, it is also unclear what could be an issue.

**Comment by SKYMEMiC** [comment]
new fit, Market "Raitaru Upwell Quantum Core" double click

**Comment by DarkFenX** [comment]
Ok, reproduced it, thanks.

**Comment by DarkFenX** [comment]
Fixed in 20e605c30fbdaa7913e6d8fd02dd624581b8c2a9 by invalidating quantum cores, since they change only services which are not visible in pyfa.

I guess the only downside is being unable to see total fit cost with the core, but adding core support just for that seems to be an overkill. @SKYMEMiC what do you think?

**Comment by SKYMEMiC** [comment]
I'd be okay with it to have it in cargo for using multibuy later. Also Pyfa then could calculate the price then. Make sure just to have one and the right one in the cargo.

**Comment by DarkFenX** [comment]
Ok, cool

**Comment by SKYMEMiC** [comment]
Note: Cargo space is not really used in this case. Maybe skip that one when summing up the m³ for the cargo space bar and display.
