### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by meyerlasse** [pyfa-org/Pyfa#2283]
## Bug Report

pyfa v2.30.0
EVE Data Version: 1832008 (2020-10-27 09:28:42)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.24.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "pyfa.py", line 150, in <module>
  File "gui\mainFrame.py", line 183, in __init__
  File "gui\shipBrowser.py", line 62, in __init__
  File "gui\builtinShipBrowser\raceSelector.py", line 75, in __init__
  File "gui\builtinShipBrowser\raceSelector.py", line 162, in RebuildRaces
  File "gui\builtinShipBrowser\raceSelector.py", line 116, in CalcButtonsBarPos
AttributeError: 'NoneType' object has no attribute 'GetWidth'

### Detailed steps to reproduce:
Started pyfa from the installer after it finished installing

### Release or development git branch? Please note the release version or commit hash:
Latest Windows-Setup exe

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by meyerlasse** [comment]
I got this error when starting Pyfa normally, too. However after deleting the pyfa folder and reinstalling it it works. **Previously I installed the newest version into the already existing folder!**
