### ISSUE TITLE
Graphs Window not accessible

### ISSUE THREAD

**Issue by BobbyPins** [pyfa-org/Pyfa#2286]
## Bug Report
The 'Graphs' Menu Item under 'Fit' is greyed out. Pressing CTRL+G doesn't open the Graphs Window either.

### Expected behavior:
The Graphs Window should open when selecting the corresponding menu entry or pressing CTRL+G.

### Actual behavior:
The Graphs Window doesn't open when selecting the corresponding menu entry or pressing CTRL+G.

### Detailed steps to reproduce:
n/a

### Fits involved in EFT format (Edit > To Clipboard > EFT):
n/a

### Release or development git branch? Please note the release version or commit hash:
pyfa 2.31.0 (a692b1f)

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Pro
Version 2004
Build 19041.572

### Other relevant information:
This happend after updating from 2.30.0 to 2.31.0. I also tried a clean reinstall, deleting the %USERPROFILEE%\\.pyfa folder before reinstalling 2.31.0.

**Comment by starobots** [comment]
I have the same problem. I can't open the graph by press ctrl+G. 
pyfa ver 2.31.0, os win 10. 
Thanks.

**Comment by DarkFenX** [comment]
Most likely some dependency has changed. Will try to fix it by fiddling with their versions.

Meanwhile, please specify, if you are using exe or zip build.

**Comment by DarkFenX** [comment]
2.31.0:
pip-20.2.4
cryptography-3.2.1-cp37-cp37m-win_amd64.whl
markdown2-2.3.10-py2.py3-none-any.whl
numpy-1.19.4-cp37-cp37m-win_amd64.whl
Pillow-8.0.1-cp37-cp37m-win_amd64.whl
kiwisolver-1.3.1-cp37-cp37m-win_amd64.whl
certifi-2020.11.8-py2.py3-none-any.whl
urllib3-1.25.11-py2.py3-none-any.whl

2.30.0:
pip-20.2.4
cryptography-3.2-cp37-cp37m-win_amd64.whl
markdown2-2.3.10-py2.py3-none-any.whl
numpy-1.19.2-cp37-cp37m-win_amd64.whl
Pillow-8.0.1-cp37-cp37m-win_amd64.whl
kiwisolver-1.2.0-cp37-none-win_amd64.whl
certifi-2020.6.20-py2.py3-none-any.whl
urllib3-1.25.11-py2.py3-none-any.whl

2.29.0:
pip-20.2.3
cryptography-3.1.1-cp37-cp37m-win_amd64.whl
markdown2-2.3.9-py2.py3-none-any.whl
numpy-1.19.2-cp37-cp37m-win_amd64.whl
Pillow-7.2.0-cp37-cp37m-win_amd64.whl
kiwisolver-1.2.0-cp37-none-win_amd64.whl
certifi-2020.6.20-py2.py3-none-any.whl
urllib3-1.25.10-py2.py3-none-any.whl

**Comment by DarkFenX** [comment]
I am going to assume that it is numpy version to blame

**Comment by DarkFenX** [comment]
Well, I actually tested it myself before reverting numpy version. 2.31.0, both exe and zip (unpacked to downloads folder) work - graphs are available and show there up.

If they do not work for you, please provide logs (from `<user>\.pyfa` folder.

**Comment by hpineapples** [comment]
Here's mine from Pyfa EXE version 2.31.0 on Win10 2004
Process was open Pyfa, load a Retri fit, confirm graph button still grayed out, press CTRL+G, quit Pyfa. 
[pyfa-2020-11-20.log](https://github.com/pyfa-org/Pyfa/files/5570730/pyfa-2020-11-20.log)

Cheers,

**Comment by c0pp3r** [comment]
Same issue.
[pyfa-2020-11-19.log](https://github.com/pyfa-org/Pyfa/files/5570905/pyfa-2020-11-19.log)

**Comment by DarkFenX** [comment]
```
[2020-11-20 01:40:36.056193] CRITICAL: graphs.gui.canvasPanel: Traceback (most recent call last):
  File "graphs\gui\canvasPanel.py", line 41, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Python37-x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\matplotlib\__init__.py", line 139, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Python37-x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\matplotlib\cbook\__init__.py", line 32, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Python37-x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "site-packages\numpy\__init__.py", line 305, in <module>
  File "site-packages\numpy\__init__.py", line 302, in _win_os_check
RuntimeError: The current Numpy installation ('C:\\Program Files\\pyfa\\numpy\\__init__.pyc') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```
Please try [latest singularity release](https://github.com/pyfa-org/Pyfa/releases/tag/v2.31.1dev1), i reverted `numpy` version there, so it might help.

**Comment by hpineapples** [comment]
Yeah that worked for me. Attached the log again in case there's anything else of worth for you there. 

[pyfa-2020-11-20.log](https://github.com/pyfa-org/Pyfa/files/5571994/pyfa-2020-11-20.log)

**Comment by c0pp3r** [comment]
This fixed it for me as well!

**Comment by BobbyPins** [comment]
This (v2.31.1dev1 690e5ca) fixed it for me too. Using the installer version. System same as above.

**Comment by DarkFenX** [comment]
Closing as fixed then
