### ISSUE TITLE
Error after creating custom damage profile

### ISSUE THREAD

**Issue by Artimus-Albosa** [pyfa-org/Pyfa#2311]
### Actual behavior: Right Click Damage Type UI -> Receive following error:
pyfa v2.33.0
EVE Data Version: 1860847 (2020-12-08 03:34:44)

OS version: Windows-10-10.0.18362-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.25.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\statsPane.py", line 139, in handler
  File "gui\contextMenu.py", line 116, in getMenu
  File "gui\contextMenu.py", line 265, in _baseGetSubMenu
  File "gui\builtinContextMenus\damagePatternChange.py", line 111, in getSubMenu
  File "gui\builtinContextMenus\damagePatternChange.py", line 104, in makeMenu
  File "gui\builtinContextMenus\damagePatternChange.py", line 58, in _addPattern
wx._core.wxAssertionError: C++ assertion "Assert failure" failed at ..\..\src\common\stockitem.cpp(213) in wxGetStockLabel(): invalid stock item ID

### Detailed steps to reproduce:
1. Select Editors Menue
2. Select Damage Type Editor
3. Create Damage Profile for ElectroPunch [T2]
4. Close Damage Profile Editor
5. Right Click Damage Profile UI
6. Receive error message

### Fits involved in EFT format (Edit > To Clipboard > EFT):
[Skybreaker, test]

Vorton Tuning System II
Vorton Tuning System II
Vorton Tuning System II

Coreli A-Type 1MN Afterburner
Republic Fleet Small Cap Battery
Republic Fleet Small Cap Battery
Pithi A-Type Small Shield Booster

Small Vorton Projector II, ElectroPunch Ultra S

Small Capacitor Control Circuit II
Small Capacitor Control Circuit I
Small Core Defense Operational Solidifier II

Mid-grade Crystal Alpha
Mid-grade Crystal Beta
Mid-grade Crystal Gamma
Mid-grade Crystal Delta
Mid-grade Crystal Epsilon
Mid-grade Crystal Omega
Zor's Custom Navigation Hyper-Link

EDENCOM Vorton Booster DA-5

ElectroPunch Ultra S x5000

### Release or development git branch? Please note the release version or commit hash: 
v2.33.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10

**Comment by Artimus-Albosa** [comment]
Error persists after restart. Deleting the newly created custom ElectroPunch [T2] damage profile resolves the error with the need to restart.
