### ISSUE TITLE
New Install unable to add character

### ISSUE THREAD

**Issue by elvenwrath** [pyfa-org/Pyfa#2315]
▶

## Bug Report
Unable to add character

### Expected behavior:
Add character though intended method

### Actual behavior:
Unable to add character through any method

### Detailed steps to reproduce:
Install program
Open program
Character entry box in the top right is greyed out and will not accept input
Also if I go to the character tab and import character file it will not use the .xml file
if I go to the Editors tab and then Character Editor it gives me the same error message as below

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
Newest latest release installed from pyfa-v2.33.0-win.exe

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10, 64 bit

### Other relevant information:
When I go to the Character tab and then Manage ESI Characters it gives me the following error message

pyfa v2.33.0
EVE Data Version: 1860847 (2020-12-08 01:34:44)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.25.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 677, in ssoHandler
  File "gui\auxWindow.py", line 63, in openOne
  File "gui\esiFittings.py", line 378, in __init__
  File "gui\esiFittings.py", line 430, in popCharList
  File "service\esi.py", line 33, in getInstance
  File "service\esi.py", line 40, in __init__
  File "service\esiAccess.py", line 77, in __init__
  File "service\settings.py", line 271, in getProxySettingsInRequestsFormat
  File "service\settings.py", line 245, in getProxySettings
  File "service\settings.py", line 233, in autodetect
ValueError: not enough values to unpack (expected 2, got 1)

the attached is an image of the greyed out character input box
![pyfa_screenshot](https://user-images.githubusercontent.com/42586373/104835649-42c3c700-5865-11eb-9d9e-f85bf421f0f3.png)

**Comment by elvenwrath** [comment]
The above occurred when using the Windows 10 exe installer. [pyfa-v2.33.0-win.exe]

The error code below is what I get when I try to run the 64 bit ver [Pyfa_Windows_x64.zip]

OS version: 	Windows-10-10.0.19041-SP0
Python: 	2.7.13
wxPython: 	3.0.2.0
SQLAlchemy: 	1.1.10
Logbook: 	1.0.0
pyfa version: 2017.06.08  - YC119.5 1.0
pyfa root: C:\PYFA
save path: C:\Users\Raven\.pyfa
fs encoding: mbcs

EXCEPTION: (sqlite3.OperationalError) no such column: characters.apiID [SQL: u'SELECT characters."alphaCloneID" AS "characters_alphaCloneID", characters."secStatus" AS "characters_secStatus", characters.name AS characters_name, characters."ID" AS "characters_ID", characters."apiID" AS "characters_apiID", characters."apiKey" AS "characters_apiKey", characters."defaultChar" AS "characters_defaultChar", characters.chars AS characters_chars, characters."defaultLevel" AS "characters_defaultLevel", characters."ownerID" AS "characters_ownerID", characters.created AS characters_created, characters.modified AS characters_modified \nFROM characters \nWHERE characters.name = ?\n LIMIT ? OFFSET ?'] [parameters: ('All 5', 1, 0)]

  File "pyfa.py", line 413, in <module>
  File "c:\users\appveyor\appdata\local\temp\1\pip-build-vg23tb\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "gui\mainFrame.py", line 48, in <module>
  File "c:\users\appveyor\appdata\local\temp\1\pip-build-vg23tb\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "gui\additionsPane.py", line 22, in <module>
  File "c:\users\appveyor\appdata\local\temp\1\pip-build-vg23tb\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "gui\boosterView.py", line 25, in <module>
  File "c:\users\appveyor\appdata\local\temp\1\pip-build-vg23tb\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "gui\marketBrowser.py", line 27, in <module>
  File "c:\users\appveyor\appdata\local\temp\1\pip-build-vg23tb\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "gui\contextMenu.py", line 182, in <module>
  File "c:\users\appveyor\appdata\local\temp\1\pip-build-vg23tb\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "gui\builtinContextMenus\commandFits.py", line 108, in <module>
  File "gui\builtinContextMenus\commandFits.py", line 37, in populateFits
  File "service\fit.py", line 50, in getInstance
  File "service\fit.py", line 59, in __init__
  File "eos\saveddata\character.py", line 101, in getAll5
  File "eos\db\saveddata\queries.py", line 83, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 57, in setCache
  File "eos\db\saveddata\queries.py", line 182, in getCharacter
  File "site-packages\sqlalchemy\orm\query.py", line 2755, in first
  File "site-packages\sqlalchemy\orm\query.py", line 2547, in __getitem__
  File "site-packages\sqlalchemy\orm\query.py", line 2855, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 2878, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 945, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
  File "site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
