### ISSUE TITLE
Error when accessing Preferences

### ISSUE THREAD

**Issue by f-i-l-z** [pyfa-org/Pyfa#2316]
## Bug Report

pyfa v2.33.0
EVE Data Version: 1860847 (2020-12-08 08:34:44)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.20
Logbook version: 1.5.3
Requests version: 2.25.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "gui\mainFrame.py", line 486, in OnShowPreferenceDialog
  File "gui\preferenceDialog.py", line 68, in __init__
  File "gui\builtinPreferenceViews\pyfaGeneralPreferences.py", line 59, in populatePanel
ValueError: None is not in list

### Expected behavior:

Access to preferences

### Actual behavior:

Error report above

### Detailed steps to reproduce:

Global>Preferences

### Fits involved in EFT format (Edit > To Clipboard > EFT):

None

### Release or development git branch? Please note the release version or commit hash:

pyfa v2.33.0

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Windows 10

**Comment by zhaoweny** [comment]
I suggest you to delete `localeSettings` from `%USERPROFILE%\.pyfa\settings` and restart pyfa.
