### ISSUE TITLE
Fails to start after update to 2.38.1 

### ISSUE THREAD

**Issue by petrosha** [pyfa-org/Pyfa#2374]
fails to start with this info in the error window:
pyfa v2.38.1
EVE Data Version: 1957858 (2021-10-28 18:15:53)

OS version: Linux-5.4.0-47-generic-x86_64-with-glibc2.29
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
wxPython version: 4.0.7 (wxWidgets 3.0.4)
SQLAlchemy version: 1.4.20
Logbook version: 1.5.3
Requests version: 2.22.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "./pyfa.py", line 148, in <module>
    from gui.mainFrame import MainFrame
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/mainFrame.py", line 36, in <module>
    import gui.fitCommands as cmd
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/fitCommands/__init__.py", line 1, in <module>
    from .gui.booster.add import GuiAddBoosterCommand
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/fitCommands/gui/booster/add.py", line 6, in <module>
    from gui.fitCommands.calc.booster.add import CalcAddBoosterCommand
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/fitCommands/calc/booster/add.py", line 4, in <module>
    from service.fit import Fit
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/fit.py", line 35, in <module>
    from service.character import Character
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/character.py", line 36, in <module>
    from service.esi import Esi
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/esi.py", line 14, in <module>
    from service.esiAccess import APIException, GenericSsoError
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/esiAccess.py", line 12, in <module>
    from jose import jwt
  File "/home/petr/.local/lib/python3.8/site-packages/jose.py", line 546
    print decrypt(deserialize_compact(jwt), {'k':key},
          ^
SyntaxError: invalid syntax

Just this in the command line:
./pyfa.py 
07:38:10 PM: Debug: Adding duplicate image handler for 'Windows bitmap file'

**Comment by blitzmann** [comment]
Looks like you installed `jose` instead of `python-jose`. Please install packages based on `requirements.txt`. That should clear it up for you :) Let me know

**Comment by blitzmann** [comment]
@petrosha if that doesn't work, please reopen issue or start a new one

**Comment by petrosha** [comment]
Have installed python-jose.
It still fails to start but the reason is different:

pyfa v2.38.1
EVE Data Version: None (None)

OS version: Linux-5.4.0-47-generic-x86_64-with-glibc2.29
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
wxPython version: 4.0.7 (wxWidgets 3.0.4)
SQLAlchemy version: 1.4.20
Logbook version: 1.5.3
Requests version: 2.22.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "./pyfa.py", line 148, in <module>
    from gui.mainFrame import MainFrame
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/mainFrame.py", line 36, in <module>
    import gui.fitCommands as cmd
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/fitCommands/__init__.py", line 1, in <module>
    from .gui.booster.add import GuiAddBoosterCommand
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/fitCommands/gui/booster/add.py", line 6, in <module>
    from gui.fitCommands.calc.booster.add import CalcAddBoosterCommand
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/fitCommands/calc/booster/add.py", line 4, in <module>
    from service.fit import Fit
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/fit.py", line 35, in <module>
    from service.character import Character
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/character.py", line 36, in <module>
    from service.esi import Esi
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/esi.py", line 14, in <module>
    from service.esiAccess import APIException, GenericSsoError
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/esiAccess.py", line 20, in <module>
    from requests_cache import CachedSession
ModuleNotFoundError: No module named 'requests_cache'

**Comment by blitzmann** [comment]
@petosorus 

> ModuleNotFoundError: No module named 'requests_cache'

You're missing this package. Again, please refer to `requirements.txt` for required dependancies. `pip install -r requirements.txt` will install the required dependencies (or `pip3` or however you use pip with your install)

**Comment by petrosha** [comment]
Oh thankyou! It helped!

I have one more issue that really annoys and it was in all versions i used through last two years.

![image](https://user-images.githubusercontent.com/25034044/142141435-aac2ad21-3725-46ee-9f38-6f9c507c9967.png)

Some elements of the interface get messy. The easiest way to reproduce is the tab-bar with opened fits. You open 5 fits in different tabs. Then close tabs with fits but the image of tabs still stays in the bar. Like in pic. If you resize the window the bar starts to show some other elements of interface. Sometimes the search bar of fittings stop responding and only redraws when i resize the frame with fittings. I can collect pics representing all of it in a separate issue if you consider it to be more correct. But maybe there is a simple solution like the version of the graphics lib?

**Comment by blitzmann** [comment]
Okay, now that is a proper issue. What I would recommend is the following:
Create new issue with as much detail as possible (including Linux distro version, version of GTK, python package versions, etc). It seems like a drawing issue, but since I'm not primarily a Linux user, I'm not sure. I'm inclined to think this is specific to your set up, otherwise I feel we would have others reporting it as well.
