### ISSUE TITLE
Fails to start after update to 2.38.1

### ISSUE THREAD

**Issue by F0LK0** [pyfa-org/Pyfa#2376]
fails to start with this info in the error window:
pyfa v2.38.1
EVE Data Version: 1957858 (2021-10-28 14:15:53)

OS version: Linux-5.14.16-301.fc35.x86_64-x86_64-with-glibc2.34
Python version: 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
wxPython version: 4.0.7 (wxWidgets 3.0.5)
SQLAlchemy version: 1.4.26
Logbook version: 1.5.3
Requests version: 2.26.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "/home/folko/GitHub/Pyfa/./pyfa.py", line 150, in <module>
    mf = MainFrame(options.title)
  File "/home/folko/GitHub/Pyfa/gui/mainFrame.py", line 172, in __init__
    self.additionsPane = AdditionsPane(self.fitting_additions_split, self)
  File "/home/folko/GitHub/Pyfa/gui/additionsPane.py", line 66, in __init__
    self.notebook.AddPage(self.drone, _t("Drones"), image=droneImg, closeable=False)
  File "/home/folko/GitHub/Pyfa/gui/chrome_tabs.py", line 231, in AddPage
    self.tabs_container.AddTab(title, image, closeable)
  File "/home/folko/GitHub/Pyfa/gui/chrome_tabs.py", line 1266, in AddTab
    tab_renderer = _TabRenderer((200, self.height), title, img, closeable)
  File "/home/folko/GitHub/Pyfa/gui/chrome_tabs.py", line 385, in __init__
    self.InitTab()
  File "/home/folko/GitHub/Pyfa/gui/chrome_tabs.py", line 479, in InitTab
    self.InitColors()
  File "/home/folko/GitHub/Pyfa/gui/chrome_tabs.py", line 563, in InitColors
    self.inactive_color = color_utils.GetSuitable(self.tab_color, 0.25)
  File "/home/folko/GitHub/Pyfa/gui/utils/color.py", line 55, in GetSuitable
    return Darken(color, factor)
  File "/home/folko/GitHub/Pyfa/gui/utils/color.py", line 33, in Darken
    return wx.Colour(r, g, b, a)
TypeError: Colour(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 1 has unexpected type 'float'

full log:
[pyfa-2021-11-13.log](https://github.com/pyfa-org/Pyfa/files/7532201/pyfa-2021-11-13.log)

**Comment by blitzmann** [comment]
pyfa requires wxPython version 4.0.6. Additionally, I don't know if pyfa works with python 3.10, it's developed and built on 3.7.

I would first install the correct version of wxPython and see if that fixes the issue (additionally, ensure that you have the correct versions as directed by requirements.txt.

if that doesn't work, install python 3.7 along with the proper requirements.

Let us know the results so we can close this issue or further investigate

**Comment by blitzmann** [comment]
Going to close this issue, @F0LK0 if the issue continues to persist, please reply
