### ISSUE TITLE
Error on close

### ISSUE THREAD

**Issue by BoredMarketer** [pyfa-org/Pyfa#2377]
pyfa error when closing the application. Application does not close unless closed using the task manager. 

### Expected behavior:
Program closes when using the "X" button on the upper right corener or File>Quit

### Actual behavior:
Program remains open with the following error.

> pyfa v2.38.1
EVE Data Version: 1957858 (2021-10-28 19:15:53)
>
>OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.26.0
Dateutil version: 2.8.2
>
>####################
>
>Traceback (most recent call last):
  File "gui\mainFrame.py", line 396, in OnClose
  File "service\settings.py", line 86, in saveAll
  File "service\settings.py", line 105, in save
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\XXXX\\.pyfa\\settings\\pyfaEOSSettings'

### Detailed steps to reproduce:
Close using the "X" button on the upper right or File>Quit

### Release or development git branch? Please note the release version or commit hash:
v2.38. 1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 Pro

### Other relevant information:
Have the same issue with the last 5 (that I can recall) versions of pyfa

**Comment by BoredMarketer** [comment]
Modified permission settings on hidden folder to R/W.
