### ISSUE TITLE
Fails to start after update to 2.38.1 from 2.37. 

### ISSUE THREAD

**Issue by petrosha** [pyfa-org/Pyfa#2378]
Fails to start after update to 2.38.1 from 2.37. 
(reopened from here:  https://github.com/pyfa-org/Pyfa/issues/2374  )

pyfa v2.38.1
EVE Data Version: None (None)

OS version: Linux-5.4.0-47-generic-x86_64-with-glibc2.29
Python version: 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
wxPython version: 4.0.7 (wxWidgets 3.0.4)
SQLAlchemy version: 1.4.20
Logbook version: 1.5.3
Requests version: 2.22.0
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "./pyfa.py", line 148, in <module>
    from gui.mainFrame import MainFrame
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/mainFrame.py", line 36, in <module>
    import gui.fitCommands as cmd
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/fitCommands/__init__.py", line 1, in <module>
    from .gui.booster.add import GuiAddBoosterCommand
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/fitCommands/gui/booster/add.py", line 6, in <module>
    from gui.fitCommands.calc.booster.add import CalcAddBoosterCommand
  File "/mnt/arc/games/eve/pyfa/Pyfa/gui/fitCommands/calc/booster/add.py", line 4, in <module>
    from service.fit import Fit
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/fit.py", line 35, in <module>
    from service.character import Character
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/character.py", line 36, in <module>
    from service.esi import Esi
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/esi.py", line 14, in <module>
    from service.esiAccess import APIException, GenericSsoError
  File "/mnt/arc/games/eve/pyfa/Pyfa/service/esiAccess.py", line 20, in <module>
    from requests_cache import CachedSession
ModuleNotFoundError: No module named 'requests_cache'

**Comment by blitzmann** [comment]
I left a comment on the other issue, it's the same issue, incorrect dependencies :)
