### ISSUE TITLE
error screen on launch

### ISSUE THREAD

**Issue by Nico0340** [pyfa-org/Pyfa#2390]
## Bug Report

when launching pyfa 2.39.1

### Expected behavior:
launching program

### Actual behavior:
nothing on screen except error message

### Detailed steps to reproduce:
every launch it fail with error message

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
ubuntu 18.04

### Other relevant information:

pyfa v2.39.1
EVE Data Version: None (None)

OS version: Linux-5.4.0-64-generic-x86_64-with-Ubuntu-18.04-bionic
Python version: 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0]
wxPython version: 4.0.1 (wxWidgets 3.0.4)
SQLAlchemy version: 1.4.17
Logbook version: 1.5.3
Requests version: 2.25.1
Dateutil version: 2.8.1

####################

Traceback (most recent call last):
  File "/home/nico/.pyfa/pyfa.py", line 148, in <module>
    from gui.mainFrame import MainFrame
  File "/home/nico/.pyfa/gui/mainFrame.py", line 36, in <module>
    import gui.fitCommands as cmd
  File "/home/nico/.pyfa/gui/fitCommands/__init__.py", line 1, in <module>
    from .gui.booster.add import GuiAddBoosterCommand
  File "/home/nico/.pyfa/gui/fitCommands/gui/booster/add.py", line 6, in <module>
    from gui.fitCommands.calc.booster.add import CalcAddBoosterCommand
  File "/home/nico/.pyfa/gui/fitCommands/calc/booster/add.py", line 4, in <module>
    from service.fit import Fit
  File "/home/nico/.pyfa/service/fit.py", line 35, in <module>
    from service.character import Character
  File "/home/nico/.pyfa/service/character.py", line 36, in <module>
    from service.esi import Esi
  File "/home/nico/.pyfa/service/esi.py", line 14, in <module>
    from service.esiAccess import APIException, GenericSsoError
  File "/home/nico/.pyfa/service/esiAccess.py", line 12, in <module>
    from jose import jwt
ModuleNotFoundError: No module named 'jose'
[pyfa-2021-12-14.log](https://github.com/pyfa-org/Pyfa/files/7713521/pyfa-2021-12-14.log)

**Comment by Nico0340** [comment]
thx man for your assistance it's works like a charm !
