### ISSUE TITLE
Unexpected Error Has Occured

### ISSUE THREAD

**Issue by Firefox43** [pyfa-org/Pyfa#2396]
Whenever I attempt to open a fit, I get this error (Have tried updating versions, using an older version, and reinstalling the same version, issue persists in all

pyfa v2.39.1
EVE Data Version: 1978193 (2021-12-09 11:05:58)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.26.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinViews\fittingView.py", line 611, in fitChanged
  File "gui\builtinViews\fittingView.py", line 742, in refresh
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 457, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1018, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 286, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3490, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3459, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 1011, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 182, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (14234,)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\statsPane.py", line 79, in fitChanged
  File "gui\builtinStatsViews\priceViewFull.py", line 88, in refreshPanel
  File "service\price.py", line 179, in getPrices
  File "eos\gamedata.py", line 457, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1018, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 286, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3490, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3459, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 1011, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 182, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (24521,)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\boosterView.py", line 133, in fitChanged
  File "gui\display.py", line 263, in update
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 457, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1018, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 286, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3490, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3459, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 1011, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 182, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (10156,)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\implantView.py", line 209, in fitChanged
  File "gui\display.py", line 263, in update
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 457, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1018, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 286, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3490, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3459, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 1011, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 182, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (20121,)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

####################

Traceback (most recent call last):
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlite3.OperationalError: no such column: prices.status

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\droneView.py", line 232, in fitChanged
  File "gui\display.py", line 263, in update
  File "gui\display.py", line 219, in refresh
  File "gui\builtinViewColumns\price.py", line 66, in getText
  File "eos\gamedata.py", line 457, in price
  File "eos\db\saveddata\queries.py", line 84, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 58, in setCache
  File "eos\db\saveddata\queries.py", line 344, in getPrice
  File "site-packages\sqlalchemy\orm\query.py", line 1018, in get
  File "site-packages\sqlalchemy\orm\query.py", line 1135, in _get_impl
  File "site-packages\sqlalchemy\orm\loading.py", line 286, in load_on_pk_identity
  File "site-packages\sqlalchemy\orm\query.py", line 3490, in one
  File "site-packages\sqlalchemy\orm\query.py", line 3459, in one_or_none
  File "site-packages\sqlalchemy\orm\query.py", line 3535, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 3560, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 1011, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 298, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1130, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1317, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1511, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 182, in raise_
  File "site-packages\sqlalchemy\engine\base.py", line 1277, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 608, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: prices.status
[SQL: SELECT prices."typeID" AS "prices_typeID", prices.price AS prices_price, prices.time AS prices_time, prices.status AS prices_status 
FROM prices 
WHERE prices."typeID" = ?]
[parameters: (28276,)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by Firefox43** [comment]
Apparently it's my saveddata file that's corrupt. Not sure how to actually fix this, so any help would be appreciated

**Comment by blitzmann** [comment]
Hi @Firefox43, yes it does seem like your database is corrupted.  

> no such column: prices.status

For some reason you don't have this column.

Can you send me you saveddata.db file? The path can be found in Preferences > Database under  Fitting Database. Send to `holmes.ryan.90@gmail.com`, and I ca look at it. At the very least I can add that column and just send it back :)

**Comment by blitzmann** [comment]
I've sent the file back to @Firefox43 , I couldn't really see a reason it would have been corrupted. I'm going to assume it was a fluke since no one else has reported this issue.
