### ISSUE TITLE
Error selecting "Manage ESI Characters": app unusable 2.39.1

### ISSUE THREAD

**Issue by Architekt909** [pyfa-org/Pyfa#2397]
## Bug Report
I've never used this tool before. I installed it on Windows 10 x64 originally via the .exe and went to Character->Manage ESI Characters.  As soon as I do this I get a stack trace with an error telling me to report it. I've tried the zip file, same behavior. The app is unusable in the present state for me as I can't even connect to my account. 

### Expected behavior:
Doesn't crash. I don't know what else is supposed to happen beyond that as I've never used this program before and can't even get past the first step.

### Actual behavior:
App crashes. 100% reproduceable. 

### Detailed steps to reproduce:
Click Character->Manage ESI Characters.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
n/a

### Release or development git branch? Please note the release version or commit hash:
release 2.39.1

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 10 x64 

### Other relevant information:
Here's the full stack trace:

pyfa v2.39.1
EVE Data Version: 1978193 (2021-12-09 12:05:58)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.26.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "site-packages\urllib3\connectionpool.py", line 696, in urlopen
  File "site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "site-packages\urllib3\connection.py", line 364, in connect
  File "site-packages\urllib3\connection.py", line 507, in _connect_tls_proxy
  File "site-packages\urllib3\util\ssl_.py", line 453, in ssl_wrap_socket
  File "site-packages\urllib3\util\ssl_.py", line 495, in _ssl_wrap_socket_impl
  File "ssl.py", line 423, in wrap_socket
  File "ssl.py", line 870, in _create
  File "ssl.py", line 1139, in do_handshake
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 449, in send
  File "site-packages\urllib3\connectionpool.py", line 756, in urlopen
  File "site-packages\urllib3\util\retry.py", line 574, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.eveonline.com', port=443): Max retries exceeded with url: /.well-known/oauth-authorization-server (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\mainFrame.py", line 677, in ssoHandler
  File "gui\auxWindow.py", line 63, in openOne
  File "gui\esiFittings.py", line 418, in __init__
  File "gui\esiFittings.py", line 470, in popCharList
  File "service\esi.py", line 33, in getInstance
  File "service\esi.py", line 40, in __init__
  File "service\esiAccess.py", line 93, in __init__
  File "site-packages\requests\sessions.py", line 555, in get
  File "site-packages\requests_cache\session.py", line 122, in request
  File "site-packages\requests\sessions.py", line 542, in request
  File "site-packages\requests_cache\session.py", line 148, in send
  File "site-packages\requests_cache\session.py", line 178, in _send_and_cache
  File "site-packages\requests\sessions.py", line 655, in send
  File "site-packages\requests\adapters.py", line 514, in send
requests.exceptions.SSLError: HTTPSConnectionPool(host='login.eveonline.com', port=443): Max retries exceeded with url: /.well-known/oauth-authorization-server (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)')))

**Comment by blitzmann** [comment]
pyfa is attempting to access this route: https://login.eveonline.com/.well-known/oauth-authorization-server

And for some reason, the underworkings of the request are failing, looks like an SSL error (the part that encrypts the data). Might be on the servers end and not really a pyfa issue, every now and then their servers can blipout, but can't be sure. Have you tried it since?

**Comment by fubbleskag** [comment]
This is happening for me today v2.39.2. Switching from Local to Manual in settings works, though.
