### ISSUE TITLE
Cant copy fits

### ISSUE THREAD

**Issue by Thelemyte** [pyfa-org/Pyfa#2486]
Can not copy Structure fits to clipboard
pyfa v2.48.0
EVE Data Version: 2154998 (2022-11-09 16:10:09)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\copySelectDialog.py", line 161, in Validate
  File "gui\copySelectDialog.py", line 188, in exportEft
  File "service\port\port.py", line 305, in exportEft
  File "service\port\eft.py", line 90, in exportEft
  File "service\port\eft.py", line 210, in exportFighters
  File "service\port\eft.py", line 207, in fighterSorter
AttributeError: 'Fighter' object has no attribute 'fullName'

**Comment by DarkFenX** [comment]
This issue has been fixed already. Should be available next release (today).
