### ISSUE TITLE
Linux/AppImage: Missing library opening on Fedora 37

### ISSUE THREAD

**Issue by updraft0** [pyfa-org/Pyfa#2488]
### Expected behavior:

The AppImage opens.

### Actual behavior:

Error message:

```
yfa v2.49.0
EVE Data Version: 2178459 (2022-12-11 00:27:31)

OS version: Linux-6.0.15-300.rog.fc37.x86_64-x86_64-with-fedora-37-Thirty_Seven
Python version: 3.7.16 (default, Dec 11 2022, 22:28:19) 
[GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "/run/user/1000/.mount_pyfa-v8mhX2C/opt/pyfa/pyfa.py", line 148, in <module>
    from gui.mainFrame import MainFrame
  File "/run/user/1000/.mount_pyfa-v8mhX2C/opt/pyfa/gui/mainFrame.py", line 62, in <module>
    from gui.updateDialog import UpdateDialog
  File "/run/user/1000/.mount_pyfa-v8mhX2C/opt/pyfa/gui/updateDialog.py", line 25, in <module>
    import wx.html2
  File "/run/user/1000/.mount_pyfa-v8mhX2C/opt/python3.7/lib/python3.7/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory
```

### Detailed steps to reproduce:

1. Install Fedora 37
2. Try to run the AppImage

### Release or development git branch? Please note the release version or commit hash:

Release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

Fedora 37

### Other relevant information:

At first I thought the libwebkit2gtk library might be in the excludelist, but I can't see it in the code either here or in https://github.com/AppImageCommunity/pkg2appimage/blob/master/excludelist . So I guess this must be some packaging issue where it should be including the library but isn't. I am not familiar with AppImage packaging so opening issue.

**Comment by updraft0** [comment]
For anyone else that runs into this (on fedora 37 silverblue or kinoite), you can run the pyfa appimage in a toolbox container. Create a new toolbox, and install `dnf install flatpak-xdg-utils webkit2gtk4.0 libXxf86vm fuse fuse-libs fuse-overlayfs` and use the xdg-open trick from https://github.com/containers/toolbox/issues/291#issuecomment-948975647 to allow ESI character import.
