### ISSUE TITLE
pyfa-v2.52.0-linux.AppImage will not run on Steamdeck

### ISSUE THREAD

**Issue by NomLom** [pyfa-org/Pyfa#2512]
## Bug Report

pyfa-v2.52.0-linux.AppImage will not run on Steamdeck.

ImportError: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

### Expected behavior:

Pyfa runs after being imported to steam.

### Actual behavior:

Error.
### Detailed steps to reproduce:
1.  Right click appimage, add to steam.
2. Run pyfa

### Release or development git branch? Please note the release version or commit hash:
release

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):

SteamOS (arch)

### Other relevant information:

libwebkit2gtk-4.0.so.37 is not included in steam OS and there is not a way to install it.

pyfa v2.52.0
EVE Data Version: 2258955 (2023-04-27 17:42:31)

OS version: Linux-5.13.0-valve36-1-neptune-x86_64-with-arch
Python version: 3.7.16 (default, Apr  9 2023, 15:58:27) 
[GCC 10.2.1 20210130 (Red Hat 10.2.1-11)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.5.3
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "/tmp/.mount_pyfa-vxpYM1k/opt/pyfa/pyfa.py", line 148, in <module>
    from gui.mainFrame import MainFrame
  File "/tmp/.mount_pyfa-vxpYM1k/opt/pyfa/gui/mainFrame.py", line 62, in <module>
    from gui.updateDialog import UpdateDialog
  File "/tmp/.mount_pyfa-vxpYM1k/opt/pyfa/gui/updateDialog.py", line 25, in <module>
    import wx.html2
  File "/tmp/.mount_pyfa-vxpYM1k/opt/python3.7/lib/python3.7/site-packages/wx/html2.py", line 15, in <module>
    from ._html2 import *
ImportError: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

**Comment by NomLom** [comment]
Resolve with : 
If you have not already, use passwd to create a password for the deck user.

Disable read-only mode: sudo btrfs property set -ts / ro false

Initialize the pacman keyring: sudo pacman-key --init

Populate the pacman keyring with the default Arch Linux keys: sudo pacman-key --populate archlinux

install webkit: sudo pacman -S webkit2gtk

**Comment by engineer1109** [comment]
It is your linux package problem.

**Comment by arrowmaster** [comment]
Same issue with Debian Trixie (current testing suite). Resolved by installing package `libwebkit2gtk-4.0-37`.

All required libraries should be included in the AppImage so installing additional packages isn't required.

**Comment by DarkFenX** [comment]
FYI it is *not* you OS issue. Those libraries are supposed to be bundled with appimage.

I am closing this one because we just changed our AppImage build process and library versions. Will make new issues to track dependency issues.
