### ISSUE TITLE
can't access ESI

### ISSUE THREAD

**Issue by xuanranshang** [pyfa-org/Pyfa#2525]
Traceback (most recent call last):
  File "site-packages\requests\adapters.py", line 499, in send
  File "site-packages\urllib3\connectionpool.py", line 799, in urlopen
  File "site-packages\urllib3\util\retry.py", line 592, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='login.eveonline.com', port=443): Max retries exceeded with url: /.well-known/oauth-authorization-server (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\mainFrame.py", line 677, in ssoHandler
  File "gui\auxWindow.py", line 63, in openOne
  File "gui\esiFittings.py", line 418, in __init__
  File "gui\esiFittings.py", line 470, in popCharList
  File "service\esi.py", line 33, in getInstance
  File "service\esi.py", line 40, in __init__
  File "service\esiAccess.py", line 93, in __init__
  File "site-packages\requests\sessions.py", line 600, in get
  File "site-packages\requests_cache\session.py", line 122, in request
  File "site-packages\requests\sessions.py", line 587, in request
  File "site-packages\requests_cache\session.py", line 148, in send
  File "site-packages\requests_cache\session.py", line 178, in _send_and_cache
  File "site-packages\requests\sessions.py", line 701, in send
  File "site-packages\requests\adapters.py", line 559, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='login.eveonline.com', port=443): Max retries exceeded with url: /.well-known/oauth-authorization-server (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

**Comment by skyler811** [comment]
File "service\server.py", line 29, in do_GET
  File "service\esi.py", line 172, in handleServerLogin
  File "service\esi.py", line 138, in handleLogin
  File "service\esiAccess.py", line 175, in auth
  File "service\esiAccess.py", line 203, in token_call
  File "site-packages\requests\sessions.py", line 635, in post
  File "site-packages\requests\sessions.py", line 587, in request
  File "site-packages\requests\sessions.py", line 701, in send
  File "site-packages\requests\adapters.py", line 547, in send
