### ISSUE TITLE
MacOS14 M2 CPU - Pyfa fails to start

### ISSUE THREAD

**Issue by digitalsoul1** [pyfa-org/Pyfa#2533]
## Bug Report
The app fails to start with the following error string.
It was fine before upgrading to MacOS 14.

pyfa v2.54.0
EVE Data Version: 2363654 (2023-09-19 20:48:39)

OS version: Darwin-23.0.0-x86_64-i386-64bit
Python version: 3.7.15 (default, Dec  8 2022, 16:29:15) 
[Clang 12.0.0 (clang-1200.0.32.28)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.6.0
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

wx._core.wxAssertionError: C++ assertion "Assert failure" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py37/Phoenix/ext/wxWidgets/src/common/datetime.cpp(298) in CallStrftime(): strftime() failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyfa.py", line 148, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/mainFrame.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/gui/frame.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/display.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/viewColumn.py", line 71, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinViewColumns/baseName.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/itemStats.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/itemStats.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinItemStatsViews/itemDescription.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "wx/html.py", line 18, in <module>
SystemError: <built-in function __import__> returned a result with an error set

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
MacOS Sonoma 14

**Comment by nissaba** [comment]
pyfa v2.54.0
EVE Data Version: 2363654 (2023-09-19 15:48:39)

OS version: Darwin-23.0.0-x86_64-i386-64bit
Python version: 3.7.15 (default, Dec  8 2022, 16:29:15) 
[Clang 12.0.0 (clang-1200.0.32.28)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.6.0
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

wx._core.wxAssertionError: C++ assertion "Assert failure" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py37/Phoenix/ext/wxWidgets/src/common/datetime.cpp(298) in CallStrftime(): strftime() failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyfa.py", line 148, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/mainFrame.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/gui/frame.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/display.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/viewColumn.py", line 71, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinViewColumns/baseName.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/itemStats.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/itemStats.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinItemStatsViews/itemDescription.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "wx/html.py", line 18, in <module>
SystemError: <built-in function __import__> returned a result with an error set

**Comment by dangarfield** [comment]
Same for me

**Comment by OrthelT** [comment]
Same issue. But, I'm on Intel Mac. Believe the issue began following the latest OSX update to **MacOS Sonoma Version 14.0.**

pyfa v2.53.1
EVE Data Version: 2353888 (2023-09-09 19:11:07)

OS version: Darwin-23.0.0-x86_64-i386-64bit
Python version: 3.7.15 (default, Dec  8 2022, 16:29:15) 
[Clang 12.0.0 (clang-1200.0.32.28)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.6.0
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

wx._core.wxAssertionError: C++ assertion "Assert failure" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py37/Phoenix/ext/wxWidgets/src/common/datetime.cpp(298) in CallStrftime(): strftime() failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyfa.py", line 148, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/mainFrame.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/gui/frame.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/display.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/viewColumn.py", line 71, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinViewColumns/baseName.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/itemStats.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/itemStats.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinItemStatsViews/itemDescription.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "wx/html.py", line 18, in <module>
SystemError: <built-in function __import__> returned a result with an error set

**Comment by tadeasf** [comment]
i provided with a fix here: https://github.com/pyfa-org/Pyfa/issues/2528#issuecomment-1741745109

it's hacky, i don't want to refactor the whole codebase in order to make it in line with up-to-date wxpython. but if somebody here would help and give me the specific parts which would need the refactor, i will gladly do that

**Comment by gscottnelson** [comment]
> i provided with a fix here: [#2528 (comment)](https://github.com/pyfa-org/Pyfa/issues/2528#issuecomment-1741745109)
> 
> it's hacky, i don't want to refactor the whole codebase in order to make it in line with up-to-date wxpython. but if somebody here would help and give me the specific parts which would need the refactor, i will gladly do that

I appears this file has been removed?   I would like to try it out, but its not available..

**Comment by DarkFenX** [comment]
@tadeasf make a pull request please. Realistically I won't have time to debug and fix it myself.

**Comment by tadeasf** [comment]
@DarkFenX did my best to make it happen, as I mentioned, it's my first pull request. if I gotta do more/fix something/did something wrong, let me know, will adjust accordingly

**Comment by tadeasf** [comment]
@gscottnelson no idea why. 
uploaded it to my personal gdrive, will leave it there for a week +-
https://drive.google.com/drive/folders/1x1-SjQD_pR7R05j2yQg5T3kIAU6UQL-w?usp=sharing

**Comment by esperiance** [comment]
@tadeasf new issue
pyfa v2.54.1
EVE Data Version: 2380773 (2023-10-09 21:22:51)

OS version: macOS-14.0-arm64-arm-64bit
Python version: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:56:53) 
[Clang 15.0.7 ]
wxPython version: 4.1.1 (wxWidgets 3.1.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.6.0
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "pyfa.py", line 150, in <module>
  File "gui/mainFrame.py", line 172, in __init__
  File "gui/additionsPane.py", line 65, in __init__
  File "gui/builtinAdditionPanes/droneView.py", line 75, in __init__
  File "gui/display.py", line 44, in __init__
  File "gui/display.py", line 123, in insertColumnBySpec
  File "gui/builtinViewColumns/maxRange.py", line 45, in __init__
  File "gui/cachingImageList.py", line 34, in GetImageIndex
  File "gui/bitmap_loader.py", line 74, in getBitmap
  File "gui/bitmap_loader.py", line 108, in loadBitmap
wx._core.wxAssertionError: C++ assertion "GetHeight() == h" failed at /Users/runner/miniforge3/conda-bld/wxpython_1667572492253/work/ext/wxWidgets/src/osx/core/bitmap.cpp(1412) in SetHeight(): Changing the bitmap height is not supported

**Comment by Wise-Wu** [comment]
pyfa v2.54.1
EVE Data Version: 2380773 (2023-10-10 02:22:51)

OS version: Darwin-23.0.0-x86_64-i386-64bit
Python version: 3.7.15 (default, Dec  8 2022, 16:29:15) 
[Clang 12.0.0 (clang-1200.0.32.28)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.6.0
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

wx._core.wxAssertionError: C++ assertion "Assert failure" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py37/Phoenix/ext/wxWidgets/src/common/datetime.cpp(298) in CallStrftime(): strftime() failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyfa.py", line 148, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/mainFrame.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/gui/frame.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/display.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/viewColumn.py", line 71, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinViewColumns/baseName.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/itemStats.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/itemStats.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinItemStatsViews/itemDescription.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "wx/html.py", line 18, in <module>
SystemError: <built-in function __import__> returned a result with an error set

<img width="477" alt="image" src="https://github.com/pyfa-org/Pyfa/assets/40017345/d97125ad-c7ec-4c46-bce5-708da3fd9cf3">

**Comment by gscottnelson** [comment]
I downloaded what tadeasf posted, but it says the application is damaged and can't be opened...I tried several times to install..

**Comment by tadeasf** [comment]
well, that's in the probably due to binary bindings. i bow to this as i am unable to help at this moment

**Comment by tadeasf** [comment]
> I downloaded what tadeasf posted, but it says the application is damaged and can't be opened...I tried several times to install..

try to build it. that was the primary intention as anaconda has pre-packaged binaries .....

**Comment by davidbeere** [comment]
pyfa v2.54.1
EVE Data Version: 2380773 (2023-10-09 19:22:51)

OS version: Darwin-23.0.0-x86_64-i386-64bit
Python version: 3.7.15 (default, Dec  8 2022, 16:29:15) 
[Clang 12.0.0 (clang-1200.0.32.28)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.6.0
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

wx._core.wxAssertionError: C++ assertion "Assert failure" failed at /Users/robind/projects/buildbots/macosx-vm6/dist-osx-py37/Phoenix/ext/wxWidgets/src/common/datetime.cpp(298) in CallStrftime(): strftime() failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyfa.py", line 148, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/mainFrame.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/__init__.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "graphs/gui/frame.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/display.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/viewColumn.py", line 71, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinViewColumns/baseName.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/__init__.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinContextMenus/itemStats.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/itemStats.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "gui/builtinItemStatsViews/itemDescription.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/appveyor/venv3.7.15/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "wx/html.py", line 18, in <module>
SystemError: <built-in function __import__> returned a result with an error set

**Comment by DarkFenX** [comment]
Try https://github.com/pyfa-org/Pyfa/releases/tag/v2.57.0dev2 or newer releases, report to the linked macOS issue for any hiccups. Closing this one.
