### ISSUE TITLE
Cannot open "Manage ESI Characters" due to traceback involving json

### ISSUE THREAD

**Issue by bhayden53** [pyfa-org/Pyfa#2538]
## Bug Report

Upon attempting to open "Manage ESI Characters", an error window comes up with the following message:

```
pyfa v2.54.1
EVE Data Version: 2380773 (2023-10-09 14:22:51)

OS version: Windows-10-10.0.22621-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.6.0
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "site-packages\requests\models.py", line 971, in json
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\mainFrame.py", line 677, in ssoHandler
  File "gui\auxWindow.py", line 63, in openOne
  File "gui\esiFittings.py", line 418, in __init__
  File "gui\esiFittings.py", line 470, in popCharList
  File "service\esi.py", line 33, in getInstance
  File "service\esi.py", line 40, in __init__
  File "service\esiAccess.py", line 99, in __init__
  File "site-packages\requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Not sure if it's important, but the reported windows version is incorrect. I am on Windows 11, version 22H2

The error also seems to affect the character editor, as attempting to open that results in the same traceback.

### Expected behavior:
The character editor or ESI manager open successfully.

### Actual behavior:
The character editor and ESI manager fail to open due to the above error.

### Detailed steps to reproduce:
I simply came to github, downloaded the latest stable release, and installed it. I have also tried with v2.55.0dev1 and get the same error.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
No fit is required to reproduce

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 11, version 22H2

**Comment by seegge** [comment]
I have windows 10 and I'm getting the exact same error with 2.54.1 and latest 2.55.0dev1

Edition	Windows 10 Pro
Version	22H2
Installed on	‎08/‎06/‎2022
OS build	19045.3570
Experience	Windows Feature Experience Pack 1000.19052.1000.0

Log: 

pyfa v2.54.1
EVE Data Version: 2380773 (2023-10-09 21:22:51)

OS version: Windows-10-10.0.19041-SP0
Python version: 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:58:18) [MSC v.1900 64 bit (AMD64)]
wxPython version: 4.0.6 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.6.0
Requests version: 2.28.1
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "site-packages\requests\models.py", line 971, in json
  File "json\__init__.py", line 348, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gui\mainFrame.py", line 444, in OnShowCharacterEditor
  File "gui\auxWindow.py", line 63, in openOne
  File "gui\characterEditor.py", line 159, in __init__
  File "gui\characterEditor.py", line 807, in __init__
  File "gui\characterEditor.py", line 836, in ssoListChanged
  File "gui\characterEditor.py", line 840, in charChanged
  File "service\esi.py", line 33, in getInstance
  File "service\esi.py", line 40, in __init__
  File "service\esiAccess.py", line 99, in __init__
  File "site-packages\requests\models.py", line 975, in json
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
