### ISSUE TITLE
Dependency update: Windows release tracking issue

### ISSUE THREAD

**Issue by DarkFenX** [pyfa-org/Pyfa#2547]
This issue is for tracking major issues which appeared with release of https://github.com/pyfa-org/Pyfa/releases/tag/v2.57.3

Report inability to launch pyfa, crashes, weird looking UI here.

Changes relatively latest release: just dependencies were updated, but it also included update of pyinstaller, which historically has a significant chance to cause windows-related issues (especially when it comes to anti-virus monitors)

**Comment by Rguz126** [comment]
Bitdefender gives a message of: "disinfection is in progress". 
The file C:\Program Files\pyfa\is-H5KQB.tmp has been detected as infected with Gen:Variant.Tedy.488325 and Bitdefender could not clean this item. A device restart is required to finalize the cleaning process.

**Comment by DarkFenX** [comment]
This seems to be a false positive, see #2550 (and let's keep discussion related to false positive detection there).

Please report this as false positive to bitdefender.

**Comment by liligeng111** [comment]
Cannot launch pyfa.

pyfa v2.57.1
EVE Data Version: 2443636 (2023-12-05 19:37:07)

OS version: Windows-10-10.0.19045-SP0
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\chrome_tabs.py", line 338, in OnSize
  File "gui\chrome_tabs.py", line 800, in UpdateSize
  File "gui\chrome_tabs.py", line 1367, in AdjustTabsSize
  File "gui\chrome_tabs.py", line 423, in SetSize
  File "gui\chrome_tabs.py", line 482, in InitTab
  File "gui\chrome_tabs.py", line 528, in ComposeTabBack
TypeError: Image.Scale(): argument 1 has unexpected type 'float'

**Comment by DarkFenX** [comment]
Fixed in 3593d16bd1b8b00e2f6c799fa6d3272d50ed62b2

**Comment by DarkFenX** [comment]
@liligeng111 please try this build: https://ci.appveyor.com/project/pyfa-org/pyfa/builds/48694338/job/2hhrq3g5st87u78n/artifacts

If there are any more crashes, lmk. If not, I will make another release shortly.

**Comment by liligeng111** [comment]
Thank you for the quick fix. pyfa launches now,  but another error message pops. 
I will be able to help with more testing in 10 hours or so.(heading to bed now)

pyfa v2.57.1+1-g3593d16bd
EVE Data Version: 2443636 (2023-12-05 19:37:07)

OS version: Windows-10-10.0.19045-SP0
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\chrome_tabs.py", line 1216, in OnPaint
TypeError: DC.SetDeviceOrigin(): argument 1 has unexpected type 'float'

**Comment by DarkFenX** [comment]
@liligeng111 try this build: https://ci.appveyor.com/project/pyfa-org/pyfa/builds/48695277/job/wd9e2cyt15ijj1m5/artifacts

**Comment by liligeng111** [comment]
I  just tested, no more error messages. Thank you!

**Comment by DarkFenX** [comment]
No idea how to fix that one, not enough data from the error. But I found a bug which is applicable to all platforms and which broke html export, which is fixed now.

**Comment by DarkFenX** [comment]
https://github.com/pyfa-org/Pyfa/releases/tag/v2.57.2

**Comment by liligeng111** [comment]
Everything is working now, thank you very much!

**Comment by DarkFenX** [comment]
Regarding issue you posted earlier, there is an issue on that apparently, created by me a while ago: https://github.com/wxWidgets/Phoenix/issues/1610

**Comment by chenjie199234** [comment]
@DarkFenX 2.57.2 be deleted by the windows defender,said there is a virous.

**Comment by SebFerraro** [comment]
https://i.imgur.com/1MQ7zzT.png

Same here

**Comment by Hallows** [comment]
I use source code and Python3.8 to run PYFA, the 2.57.3 version can not work correctly but 2.56.0 can work in my environment.
Here is the crash report:
EVE Data Version: None (None)

OS version: Windows-10-10.0.19045-SP0
Python version: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
wxPython version: 4.0.7 (wxWidgets 3.0.5)
SQLAlchemy version: 1.3.23
Logbook version: 1.6.0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "F:\Pyfa\pyfa.py", line 126, in <module>
    update_db()
  File "F:\Pyfa\db_update.py", line 91, in update_db
    import eos.db
  File "F:\Pyfa\eos\db\__init__.py", line 120, in <module>
    from eos.db.saveddata import booster, cargo, character, damagePattern, databaseRepair, drone, fighter, fit, implant, implantSet, \
  File "F:\Pyfa\eos\db\saveddata\fit.py", line 173, in <module>
    "_Fit__modules": relation(
  File "C:\Users\yinxi\.conda\envs\pyfa\lib\site-packages\sqlalchemy\orm\__init__.py", line 106, in relation
    return relationship(*arg, **kw)
TypeError: relationship() got an unexpected keyword argument 'overlaps'
