### ISSUE TITLE
Crash upon first attempt to run

### ISSUE THREAD

**Issue by Griswald6302** [pyfa-org/Pyfa#2579]
Here is the error code upon first run:

pyfa v2.57.3
EVE Data Version: 2443636 (2023-12-05 05:37:07)

OS version: Windows-10-10.0.22631-SP0
Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "sqlalchemy\engine\base.py", line 3371, in _wrap_pool_connect
  File "sqlalchemy\pool\base.py", line 327, in connect
  File "sqlalchemy\pool\base.py", line 894, in _checkout
  File "sqlalchemy\pool\base.py", line 493, in checkout
  File "sqlalchemy\pool\impl.py", line 256, in _do_get
  File "sqlalchemy\pool\base.py", line 273, in _create_connection
  File "sqlalchemy\pool\base.py", line 388, in __init__
  File "sqlalchemy\pool\base.py", line 690, in __connect
  File "sqlalchemy\util\langhelpers.py", line 70, in __exit__
  File "sqlalchemy\util\compat.py", line 211, in raise_
  File "sqlalchemy\pool\base.py", line 686, in __connect
  File "sqlalchemy\engine\create.py", line 574, in connect
  File "sqlalchemy\engine\default.py", line 598, in connect
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyfa.py", line 133, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "service\prefetch.py", line 38, in <module>
  File "sqlalchemy\sql\schema.py", line 4930, in create_all
  File "sqlalchemy\engine\base.py", line 3237, in _run_ddl_visitor
  File "sqlalchemy\engine\base.py", line 3153, in begin
  File "sqlalchemy\engine\base.py", line 3325, in connect
  File "sqlalchemy\engine\base.py", line 96, in __init__
  File "sqlalchemy\engine\base.py", line 3404, in raw_connection
  File "sqlalchemy\engine\base.py", line 3374, in _wrap_pool_connect
  File "sqlalchemy\engine\base.py", line 2208, in _handle_dbapi_exception_noconnection
  File "sqlalchemy\util\compat.py", line 211, in raise_
  File "sqlalchemy\engine\base.py", line 3371, in _wrap_pool_connect
  File "sqlalchemy\pool\base.py", line 327, in connect
  File "sqlalchemy\pool\base.py", line 894, in _checkout
  File "sqlalchemy\pool\base.py", line 493, in checkout
  File "sqlalchemy\pool\impl.py", line 256, in _do_get
  File "sqlalchemy\pool\base.py", line 273, in _create_connection
  File "sqlalchemy\pool\base.py", line 388, in __init__
  File "sqlalchemy\pool\base.py", line 690, in __connect
  File "sqlalchemy\util\langhelpers.py", line 70, in __exit__
  File "sqlalchemy\util\compat.py", line 211, in raise_
  File "sqlalchemy\pool\base.py", line 686, in __connect
  File "sqlalchemy\engine\create.py", line 574, in connect
  File "sqlalchemy\engine\default.py", line 598, in connect
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)

**Comment by DarkFenX** [comment]
Check permissions to write to `<user folder>/.pyfa/saveddata.db` file
