### ISSUE TITLE
Linux Image Symbol Missing wl_proxy_marshal_flags

### ISSUE THREAD

**Issue by engineer1109** [pyfa-org/Pyfa#2600]
## Bug Report
log
```
Traceback (most recent call last):
  File "/tmp/.mount_pyfa-vcf0BPC/opt/pyfa/pyfa.py", line 27, in <module>
    import config
  File "/tmp/.mount_pyfa-vcf0BPC/opt/pyfa/config.py", line 4, in <module>
    import wx
  File "/tmp/.mount_pyfa-vcf0BPC/usr/local/lib/python3.11/dist-packages/wx/__init__.py", line 17, in <module>
    from wx.core import *
  File "/tmp/.mount_pyfa-vcf0BPC/usr/local/lib/python3.11/dist-packages/wx/core.py", line 12, in <module>
    from ._core import *
ImportError: /tmp/.mount_pyfa-vcf0BPC/usr/lib/x86_64-linux-gnu/libgdk-3.so.0: undefined symbol: wl_proxy_marshal_flags

```
missing wl_proxy_marshal_flags
### Release or development git branch? Please note the release version or commit hash:
pyfa-v2.58.1-linux.AppImage

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Ubuntu 20.04.5

**Comment by DarkFenX** [comment]
@engineer1109 give me version of your `libwayland-client0` package.

For the context: we bundle [libgtk-3-0](https://packages.ubuntu.com/jammy/libgtk-3-0) with pyfa. According to [this](https://bbs.archlinux.org/viewtopic.php?id=272846), issue might be related to wayland client library (which might be caused by installer not bundling it for some reason).

**Comment by DarkFenX** [comment]
Bundled this lib, will be in next release. AppImage works locally, but i cannot conduct full-scale compatibility testing
