### ISSUE TITLE
Pyfa v2.59.3 Crashes on Open

### ISSUE THREAD

**Issue by JaredC01** [pyfa-org/Pyfa#2633]
### Expected behavior:
App opens normally.

### Actual behavior:
App crashes when opening after upgrading from previous version.

### Detailed steps to reproduce:
Downloaded and installed latest version over last version.

### Fits involved in EFT format (Edit > To Clipboard > EFT):
N/A

### Release or development git branch? Please note the release version or commit hash:
2.59.3 - Just released 15 minutes ago.

### Operating system and version (eg: Windows 10, OS X 10.9, OS X 10.11, Ubuntu 16.10):
Windows 11 23H2

### Other relevant information:

`pyfa v2.59.3
EVE Data Version: 2672509 (2024-09-09 13:08:17)

OS version: Windows-10-10.0.22631-SP0
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "pyfa.py", line 148, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "gui\mainFrame.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "gui\fitCommands\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "gui\fitCommands\gui\booster\add.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "gui\fitCommands\helpers.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "service\market.py", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "service\jargon\__init__.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "service\jargon\loader.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "service\jargon\resources.py", line 22, in <module>
  File "importlib\resources\_common.py", line 22, in files
  File "importlib\resources\_common.py", line 55, in get_package
TypeError: 'service.jargon.resources' is not a package`

**Comment by JaredC01** [comment]
Worth note, I've tried reinstalling using the same executable, and after downloading the executable again.

**Comment by wereii** [comment]
Also happens on linux appimage, does not seem to happen in native linux one.

**Comment by wereii** [comment]
I see in 65fb468 that you too have been bitten by the new importlib @DarkFenX :) 

I usually do just the `Path(__file__)` trick with static resources instead of having to touch anything importlib

**Comment by DarkFenX** [comment]
This has been fixed on the same day, closing
