### ISSUE TITLE
structure fighter crash V2.60.0

### ISSUE THREAD

**Issue by HigginsDallocort** [pyfa-org/Pyfa#2638]
## Bug Report

**1st error**

pyfa v2.60.0
EVE Data Version: 2682489 (2024-09-18 07:24:32)

OS version: Windows-10-10.0.22631-SP0
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

**2nd error**

pyfa v2.60.0
EVE Data Version: 2682489 (2024-09-18 07:24:32)

OS version: Windows-10-10.0.22631-SP0
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\copySelectDialog.py", line 161, in Validate
  File "gui\copySelectDialog.py", line 188, in exportEft
  File "service\port\port.py", line 304, in exportEft
  File "service\port\eft.py", line 90, in exportEft
  File "service\port\eft.py", line 210, in exportFighters
  File "service\port\eft.py", line 207, in fighterSorter
ValueError: tuple.index(x): x not in tuple

####################

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\fighterView.py", line 292, in fitChanged
  File "gui\builtinAdditionPanes\fighterView.py", line 262, in fighterKey
ValueError: tuple.index(x): x not in tuple

### Expected behavior:

open a saved fortizar fitting

### Actual behavior:

opens the fit but no fighters appear in the fighters tab

### Detailed steps to reproduce:
 
add standup fighters to a citadel fitting

### Fits involved in EFT format (Edit > To Clipboard > EFT):

produces and additional error

**Comment by Wentil** [comment]
### This issue is still present in v2.60.1:

-------------------------------
pyfa v2.60.1
EVE Data Version: 2701110 (2024-10-03 04:18:43)

OS version: Windows-10-10.0.22631-SP0
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\fighterView.py", line 292, in fitChanged
  File "gui\builtinAdditionPanes\fighterView.py", line 262, in fighterKey
ValueError: tuple.index(x): x not in tuple

**Comment by DarkFenX** [comment]
Idk how i missed it for so long, sorry. Will be fixed in today's release.
