### ISSUE TITLE
Critical Error message. 

### ISSUE THREAD

**Issue by viciate** [pyfa-org/Pyfa#2641]
pyfa v2.60.1
EVE Data Version: 2701110 (2024-10-03 06:18:43)

OS version: Windows-10-10.0.22631-SP0
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\builtinAdditionPanes\fighterView.py", line 292, in fitChanged
  File "gui\builtinAdditionPanes\fighterView.py", line 262, in fighterKey
ValueError: tuple.index(x): x not in tuple

Error code shows up when trying to adjust fits for Astrahus structure.

**Comment by viciate** [comment]
reproduction steps:

1. Launch pyfa
2. Create Astrahus fit
3. Load standup fighters to the Astrahus.
