### ISSUE TITLE
New Error Message

### ISSUE THREAD

**Issue by HyperSaRogue** [pyfa-org/Pyfa#2645]
Getting the following error message on opening pyfa after updating to the most recent version.  As far as I can tell all dependencies are met.  Pyfa seems to be functioning as expected.

```
pyfa v2.60.2
EVE Data Version: 2731103 (2024-10-30 07:46:15)

OS version: Linux-5.15.0-125-generic-x86_64-with-glibc2.35
Python version: 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
wxPython version: 4.2.2 (wxWidgets 3.2.6)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "/home/morwen/Pyfa/.env/lib/python3.10/site-packages/wx/core.py", line 3427, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/morwen/Pyfa/gui/mainFrame.py", line 245, in ShowUpdateBox
    with UpdateDialog(self, release, version) as dlg:
  File "/home/morwen/Pyfa/gui/updateDialog.py", line 65, in __init__
    self.browser = wx.html2.WebView.New(self)
NotImplementedError
```

**Comment by DarkFenX** [comment]
I just tried using wxpython 4.2.2. It seems to be causing that.

**Comment by DarkFenX** [comment]
`configure: WARNING: WebKit not available, disabling wxWebView`
Installing `libwebkit2gtk-4.1-dev` fixed it for me

**Comment by HyperSaRogue** [comment]
Confirmed, install libwebkit2gtk-4.1-dev fixed the issue.  Thank you!
