### ISSUE TITLE
Error while copying Mutated Drone to clipboard

### ISSUE THREAD

**Issue by deemerz** [pyfa-org/Pyfa#2649]
## Bug Report
pyfa v2.61.0
EVE Data Version: 2744926 (2024-11-13 14:16:24)

OS version: Windows-10-10.0.19044-SP0
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
wxPython version: 4.2.2 (wxWidgets 3.2.6)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\contextMenu.py", line 174, in handler
  File "gui\contextMenu.py", line 351, in _baseActivate
  File "gui\builtinContextMenus\additionsExportSelection.py", line 42, in activate
  File "service\port\eft.py", line 186, in exportDrones
  File "service\port\eft.py", line 179, in droneSorter
AttributeError: 'NoneType' object has no attribute 'marketGroupName'

### Detailed steps to reproduce:
Choose "Copy Selected Drones" menu item from the context menu.

**Comment by DarkFenX** [comment]
Fixed in da1d42b57875aef659b7afa822ad1df85e2cb932
