### ISSUE TITLE
pyfa error on RMB to civilian charge 

### ISSUE THREAD

**Issue by chewbacca2314** [pyfa-org/Pyfa#2654]
### Other relevant information:
pyfa v2.59.2
EVE Data Version: 2608648 (2024-06-13 16:52:55)

OS version: Windows-10-10.0.19045-SP0
Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
wxPython version: 4.2.1 (wxWidgets 3.2.2.1)
SQLAlchemy version: 1.4.50
Logbook version: 1.7.0.post0
Requests version: 2.31.0
Dateutil version: 2.8.2

####################

Traceback (most recent call last):
  File "gui\builtinMarketBrowser\itemView.py", line 220, in contextMenu
  File "gui\contextMenu.py", line 103, in getMenu
  File "gui\contextMenu.py", line 301, in _baseGetText
  File "gui\builtinContextMenus\cargoAddAmmo.py", line 28, in getText
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by DarkFenX** [comment]
This has been fixed a while ago, please use latest version
