### ISSUE TITLE
Pyfa exit stops responding after silent Crest API issue

### ISSUE THREAD

**Issue by thorr18** [pyfa-org/Pyfa#450]
I could repeatedly use the Crest Login menu option and authorize and get the _"Done. Please close this window"_ browser message, but could not enable the Browse Eve Fit menu option. There was no message from Pyfa for user to know there was an issue. It just silently failed. 
<img width="172" alt="screen shot 2015-11-29 at 3 08 22 am" src="https://cloud.githubusercontent.com/assets/3753521/11456728/24649fcc-9647-11e5-99b1-2da0b052b25c.png">

Running it again on the terminal showed a server issue. 

Later, trying to exit Pyfa caused it to stop responding. Had to force close: 

A few minutes later, the API issue was gone and I was able to browse Eve fits and exit Pyfa gracefully. 
Testing was done with Pyfa pre-release 1.16.3 build on OSX 10.11.1

**Comment by blitzmann** [comment]
Error handling for CREST is unfortunately non-existent, and it's something I want to fix at some point after the OSX build are stabilized (see #383). The message displayed in the browser is simply an acknowledgement that the server got a response, rather than a *successful* response

The response seems to have been a 503, which I guess may happen if the EVE server is down. Unless you can consistently reproduce it, in which case I want you to reproduce with the debug flag and post the output.

The traceback is interesting though... Did you have the Export to eve dialog open at some point before this?

**Comment by thorr18** [comment]
Sorry, looks like a pasted the same traceback twice above. I'm editing it to paste the correct two separate tracebacks from last night.

**Comment by blitzmann** [comment]
I'll look into this, but it seems it's just not handling a response correctly and thus throwing errors everywhere. Let me know if you can reproduce it and post the debug logs - that would help in determining where in the logic this is happening at.

**Comment by thorr18** [comment]
I noticed that I can close Pyfa gracefully each time except if I Crest login first. Here I just opened Pyfa and exited after Crest login without doing anything else and the process stopped responding after closing the GUI. Had to ^Z to get back to terminal prompt and the process was even then still running. 

~~~
BsMBP:tests bem$ ../dloadedBuilds/pyfa-preRelease.app/Contents/MacOS/pyfa -d
Dec  2 04:07:16  pyfa[10582] <Notice>: 2015-12-02 04:07:16,565 root                     INFO     Starting pyfa
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,594 service.fit              DEBUG    ==========recalc==========
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,714 eos.saveddata.fit        DEBUG    Starting fit calculation on: Fit(ID=38, ship=Nightmare, name=NewWorstNightmare) at 0x10f2b6ad0, withBoosters: True
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,775 eos.saveddata.fit        DEBUG    Timer - Fit: 38, NewWorstNightmare - Done with runtime: early - 60.96ms (60.97ms elapsed)
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,848 eos.saveddata.fit        DEBUG    Timer - Fit: 38, NewWorstNightmare - Done with runtime: normal - 72.92ms (133.90ms elapsed)
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,855 eos.saveddata.fit        DEBUG    Timer - Fit: 38, NewWorstNightmare - Done with runtime: late - 7.42ms (141.33ms elapsed)
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,856 eos.saveddata.fit        DEBUG    Timer - Fit: 38, NewWorstNightmare - Done with fit calculation - 0.15ms (141.50ms elapsed)
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,858 service.fit              DEBUG    ==========recalc==========
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,859 eos.saveddata.fit        DEBUG    Starting fit calculation on: Fit(ID=38, ship=Nightmare, name=NewWorstNightmare) at 0x10f2b6ad0, withBoosters: True
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,862 eos.saveddata.fit        DEBUG    Timer - Fit: 38, NewWorstNightmare - Done with runtime: early - 3.45ms (3.45ms elapsed)
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,900 eos.saveddata.fit        DEBUG    Timer - Fit: 38, NewWorstNightmare - Done with runtime: normal - 37.50ms (40.96ms elapsed)
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,902 eos.saveddata.fit        DEBUG    Timer - Fit: 38, NewWorstNightmare - Done with runtime: late - 2.74ms (43.72ms elapsed)
Dec  2 04:07:19  pyfa[10582] <Notice>: 2015-12-02 04:07:19,902 eos.saveddata.fit        DEBUG    Timer - Fit: 38, NewWorstNightmare - Done with fit calculation - 0.23ms (43.96ms elapsed)
Dec  2 04:07:22  pyfa[10582] <Notice>: 2015-12-02 04:07:22,459 root                     DEBUG    Starting server
Dec  2 04:07:26  pyfa[10582] <Notice>: 2015-12-02 04:07:26,084 service.crest            DEBUG    Handling CREST login with: {'access_token': ['MyAccessTokenD2ZNsVXALal3pMETP1xVmSnrMwBCYSWwvesS5gC4D_N522Y-K2aet0EKZ1Ape_yG0lCuUBYw2'], 'token_type': ['Bearer'], 'state': ['52716da9-72eb-411c-8ed8-230cbb5b3fad'], 'expires_in': ['1200']}
Dec  2 04:07:26  pyfa[10582] <Notice>: 2015-12-02 04:07:26,087 pycrest.eve              DEBUG    Getting resource https://crest-tq.eveonline.com/
Dec  2 04:07:26  pyfa[10582] <Notice>: 2015-12-02 04:07:26,087 pycrest.eve              DEBUG    Cache miss for resource https://crest-tq.eveonline.com/ (params={}
Dec  2 04:07:26  pyfa[10582] <Notice>: 2015-12-02 04:07:26,087 pycrest.eve              DEBUG    Getting resource https://crest-tq.eveonline.com/ (params={})
Dec  2 04:07:26  pyfa[10582] <Notice>: 2015-12-02 04:07:26,092 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): crest-tq.eveonline.com
Dec  2 04:07:27  pyfa[10582] <Notice>: 2015-12-02 04:07:27,237 requests.packages.urllib3.connectionpool DEBUG    "GET / HTTP/1.1" 200 None
Dec  2 04:07:27  pyfa[10582] <Notice>: 2015-12-02 04:07:27,238 pycrest.eve              DEBUG    Getting resource https://login.eveonline.com/oauth/verify
Dec  2 04:07:27  pyfa[10582] <Notice>: 2015-12-02 04:07:27,238 pycrest.eve              DEBUG    Cache miss for resource https://login.eveonline.com/oauth/verify (params={}
Dec  2 04:07:27  pyfa[10582] <Notice>: 2015-12-02 04:07:27,238 pycrest.eve              DEBUG    Getting resource https://login.eveonline.com/oauth/verify (params={})
Dec  2 04:07:27  pyfa[10582] <Notice>: 2015-12-02 04:07:27,240 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): login.eveonline.com
Dec  2 04:07:28  pyfa[10582] <Notice>: 2015-12-02 04:07:28,332 requests.packages.urllib3.connectionpool DEBUG    "GET /oauth/verify HTTP/1.1" 200 219
Dec  2 04:07:28  pyfa[10582] <Notice>: 2015-12-02 04:07:28,333 service.crest            DEBUG    Got character info: {u'Scopes': u'characterFittingsRead characterFittingsWrite', u'ExpiresOn': u'2015-12-02T12:27:25', u'TokenType': u'Character', u'CharacterName': u'MyCharacter', u'CharacterOwnerHash': MyHashvEBZgOCzmPtlstNkRwMvodo=', u'CharacterID': 1234567890}
Dec  2 04:07:28  pyfa[10582] <Notice>: 2015-12-02 04:07:28,333 root                     DEBUG    Stopping Server
^Z
[2]+  Stopped                 ../dloadedBuilds/pyfa-preRelease.app/Contents/MacOS/pyfa -d
~~~

That's on preRelease, but I get the same results on 1.16.2

**Comment by thorr18** [comment]
Got a debug log during an API issue period, though it was a different code this time (502 vs 503)
~~~
BsMBP:tests bem$ ../dloadedBuilds/pyfa-preRelease.app/Contents/MacOS/pyfa -d
Dec  3 03:01:57  pyfa[11296] <Notice>: 2015-12-03 03:01:57,371 root                     INFO     Starting pyfa
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,249 service.fit              DEBUG    ==========recalc==========
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,446 eos.saveddata.fit        DEBUG    Starting fit calculation on: Fit(ID=37, ship=Nightmare, name=Jason'sWorstNightmare) at 0x10f1dfc10, withBoosters: True
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,512 eos.saveddata.fit        DEBUG    Timer - Fit: 37, Jason'sWorstNightmare - Done with runtime: early - 65.70ms (65.70ms elapsed)
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,595 eos.saveddata.fit        DEBUG    Timer - Fit: 37, Jason'sWorstNightmare - Done with runtime: normal - 83.36ms (149.07ms elapsed)
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,603 eos.saveddata.fit        DEBUG    Timer - Fit: 37, Jason'sWorstNightmare - Done with runtime: late - 7.92ms (157.00ms elapsed)
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,604 eos.saveddata.fit        DEBUG    Timer - Fit: 37, Jason'sWorstNightmare - Done with fit calculation - 0.18ms (157.18ms elapsed)
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,606 service.fit              DEBUG    ==========recalc==========
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,607 eos.saveddata.fit        DEBUG    Starting fit calculation on: Fit(ID=37, ship=Nightmare, name=Jason'sWorstNightmare) at 0x10f1dfc10, withBoosters: True
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,610 eos.saveddata.fit        DEBUG    Timer - Fit: 37, Jason'sWorstNightmare - Done with runtime: early - 3.25ms (3.25ms elapsed)
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,647 eos.saveddata.fit        DEBUG    Timer - Fit: 37, Jason'sWorstNightmare - Done with runtime: normal - 37.26ms (40.52ms elapsed)
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,650 eos.saveddata.fit        DEBUG    Timer - Fit: 37, Jason'sWorstNightmare - Done with runtime: late - 2.41ms (42.95ms elapsed)
Dec  3 03:02:00  pyfa[11296] <Notice>: 2015-12-03 03:02:00,650 eos.saveddata.fit        DEBUG    Timer - Fit: 37, Jason'sWorstNightmare - Done with fit calculation - 0.12ms (43.07ms elapsed)
Dec  3 03:02:04  pyfa[11296] <Notice>: 2015-12-03 03:02:04,143 root                     DEBUG    Starting server
Dec  3 03:02:07  pyfa[11296] <Notice>: 2015-12-03 03:02:07,503 service.crest            DEBUG    Handling CREST login with: {'access_token': ['AnAccessTolkenU_i_sIoId0Byca9HCODh4TdscAcmsUModQtKgjrv6yL0lehRfanBdyEFrnZE3nB-C2IanOWg2'], 'token_type': ['Bearer'], 'state': ['d3db3bfc-1df5-4f06-bef5-640458434c80'], 'expires_in': ['1200']}
Dec  3 03:02:07  pyfa[11296] <Notice>: 2015-12-03 03:02:07,504 pycrest.eve              DEBUG    Getting resource https://crest-tq.eveonline.com/
Dec  3 03:02:07  pyfa[11296] <Notice>: 2015-12-03 03:02:07,505 pycrest.eve              DEBUG    Cache miss for resource https://crest-tq.eveonline.com/ (params={}
Dec  3 03:02:07  pyfa[11296] <Notice>: 2015-12-03 03:02:07,505 pycrest.eve              DEBUG    Getting resource https://crest-tq.eveonline.com/ (params={})
Dec  3 03:02:07  pyfa[11296] <Notice>: 2015-12-03 03:02:07,510 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): crest-tq.eveonline.com
Dec  3 03:02:08  pyfa[11296] <Notice>: 2015-12-03 03:02:08,569 requests.packages.urllib3.connectionpool DEBUG    "GET / HTTP/1.1" 502 None
Dec  3 03:02:08  pyfa[11296] <Notice>: Traceback (most recent call last):
Dec  3 03:02:08  pyfa[11296] <Notice>:   File "wx/_core.pyc", line 16766, in <lambda>
Dec  3 03:02:08  pyfa[11296] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa-preRelease.app/Contents/Resources/lib/python2.7/site-packages.zip/service/crest.py", line 189, in handleLogin
Dec  3 03:02:08  pyfa[11296] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa-preRelease.app/Contents/Resources/lib/python2.7/site-packages.zip/service/pycrest/eve.py", line 259, in __call__
Dec  3 03:02:08  pyfa[11296] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa-preRelease.app/Contents/Resources/lib/python2.7/site-packages.zip/service/pycrest/eve.py", line 271, in get
Dec  3 03:02:08  pyfa[11296] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa-preRelease.app/Contents/Resources/lib/python2.7/site-packages.zip/service/pycrest/eve.py", line 158, in get
Dec  3 03:02:08  pyfa[11296] <Notice>: service.pycrest.errors.APIException: Got unexpected status code from server: 502
Dec  3 03:02:25  pyfa[11296] <Notice>: 2015-12-03 03:02:25,846 root                     DEBUG    Starting server
Dec  3 03:02:25  pyfa[11296] <Notice>: 2015-12-03 03:02:25,847 root                     DEBUG    Stopping Server
Dec  3 03:02:29  pyfa[11296] <Notice>: 2015-12-03 03:02:29,460 service.crest            DEBUG    Handling CREST login with: {'access_token': ['AnotherAccessTolken2nVs1VN0prqA9Pl2FDE_8lVAy_P37W_Cnjnp28YZbGyfeNyyr9hDgjhUknasK2s7NPA2'], 'token_type': ['Bearer'], 'state': ['308253c8-f9ee-46a7-a6a2-ce5ded017b46'], 'expires_in': ['1200']}
Dec  3 03:02:29  pyfa[11296] <Notice>: 2015-12-03 03:02:29,462 pycrest.eve              DEBUG    Getting resource https://crest-tq.eveonline.com/
Dec  3 03:02:29  pyfa[11296] <Notice>: 2015-12-03 03:02:29,463 pycrest.eve              DEBUG    Cache miss for resource https://crest-tq.eveonline.com/ (params={}
Dec  3 03:02:29  pyfa[11296] <Notice>: 2015-12-03 03:02:29,463 pycrest.eve              DEBUG    Getting resource https://crest-tq.eveonline.com/ (params={})
Dec  3 03:02:29  pyfa[11296] <Notice>: 2015-12-03 03:02:29,465 requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): crest-tq.eveonline.com
Dec  3 03:02:30  pyfa[11296] <Notice>: 2015-12-03 03:02:30,091 requests.packages.urllib3.connectionpool DEBUG    "GET / HTTP/1.1" 502 None
Dec  3 03:02:30  pyfa[11296] <Notice>: Traceback (most recent call last):
Dec  3 03:02:30  pyfa[11296] <Notice>:   File "wx/_core.pyc", line 16766, in <lambda>
Dec  3 03:02:30  pyfa[11296] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa-preRelease.app/Contents/Resources/lib/python2.7/site-packages.zip/service/crest.py", line 189, in handleLogin
Dec  3 03:02:30  pyfa[11296] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa-preRelease.app/Contents/Resources/lib/python2.7/site-packages.zip/service/pycrest/eve.py", line 259, in __call__
Dec  3 03:02:30  pyfa[11296] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa-preRelease.app/Contents/Resources/lib/python2.7/site-packages.zip/service/pycrest/eve.py", line 271, in get
Dec  3 03:02:30  pyfa[11296] <Notice>:   File "/Users/bem/factory/Py/Pyfa/build/dloadedBuilds/pyfa-preRelease.app/Contents/Resources/lib/python2.7/site-packages.zip/service/pycrest/eve.py", line 158, in get
Dec  3 03:02:30  pyfa[11296] <Notice>: service.pycrest.errors.APIException: Got unexpected status code from server: 502
Dec  3 03:03:27  pyfa[11296] <Notice>: 2015-12-03 03:03:27,235 service.server           DEBUG    Server timed out waiting for connection
Terminated: 15
BsMBP:tests bem$ 
~~~
If I wait 60 seconds before trying to exit the app, I get an additional timeout message, then exiting causes stopped responding.

**Comment by blitzmann** [comment]
@thorr18 is this still a thing? I don't remember if I ever got any headway into this. From the logs posted, these all seem like it gets a bad status from the EVE servers. I've tried to test with a known back endpoint (returns 502) and which the traceback happens, it doesn't cause an issue with closing pyfa or anything.

Then again, this is on Windows and I suspect this is a bug that revolved around os x. Let me know if you still have the issue, thx

**Comment by thorr18** [comment]
My apologies. Dropped off the face of the Earth. Life transition.
