### ISSUE TITLE
Target resists editor does not open

### ISSUE THREAD

**Issue by ErikEvenson** [pyfa-org/Pyfa#573]
I'm using the mac 1.20.1 version.  I was able to open the target resists editor once.  Subsequent attempts do nothing when I try to open the editor.

**Comment by blitzmann** [comment]
Take a look at ~/.pyfa/log.txt and let me know whats in there. Alternativly, open pyfa directly through the command line via `pyfa.app/Contents/MacOS/pyfa` and try to reproduce the bug. Hopefully something prints to the terminal

**Comment by ErikEvenson** [comment]
Nothing is logged to `~/.pyfa/log.txt`, but when starting via the command line as suggested I get this:

```
$ pyfa.app/Contents/MacOS/pyfa
May  3 17:43:41  pyfa[30338] <Notice>: Traceback (most recent call last):
May  3 17:43:41  pyfa[30338] <Notice>:   File "/Applications/pyfa.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/mainFrame.py", line 361, in showTargetResistsEditor
May  3 17:43:41  pyfa[30338] <Notice>:   File "/Applications/pyfa.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/resistsEditor.py", line 46, in __init__
May  3 17:43:41  pyfa[30338] <Notice>:   File "wx/_controls.pyc", line 501, in __init__
May  3 17:43:41  pyfa[30338] <Notice>: TypeError: String or Unicode type required
```

**Comment by ErikEvenson** [comment]
The error is slightly different in 1.21.1:

```
$ pyfa.app/Contents/MacOS/pyfa
May  3 17:48:56  pyfa[30362] <Notice>: Traceback (most recent call last):
May  3 17:48:56  pyfa[30362] <Notice>:   File "/Applications/pyfa.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/mainFrame.py", line 362, in showTargetResistsEditor
May  3 17:48:56  pyfa[30362] <Notice>:   File "/Applications/pyfa.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/resistsEditor.py", line 93, in __init__
May  3 17:48:56  pyfa[30362] <Notice>:   File "/Applications/pyfa.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/resistsEditor.py", line 55, in __init__
May  3 17:48:56  pyfa[30362] <Notice>:   File "/Applications/pyfa.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/builtinViews/entityEditor.py", line 68, in __init__
May  3 17:48:56  pyfa[30362] <Notice>:   File "/Applications/pyfa.app/Contents/Resources/lib/python2.7/site-packages.zip/gui/builtinViews/entityEditor.py", line 150, in refreshEntityList
May  3 17:48:56  pyfa[30362] <Notice>:   File "wx/_core.pyc", line 12870, in AppendItems
May  3 17:48:56  pyfa[30362] <Notice>: TypeError: String or Unicode type required
```

**Comment by blitzmann** [comment]
`~/.pyfa/saveddata.db` please send me this file via email (listed on readme). You may have corrupted data in the target resists table.

**Comment by ErikEvenson** [comment]
I deleted the entire `~/.pyfa` directory and it works fine now.  I suspect I used pyfa several years ago and the migration was just too much.  Closing as fixed.

**Comment by blitzmann** [comment]
I could have fixed it so that you wouldn't lose all your fits. =/

But yeah, it is certainly an issue with the database. I remember there was a thing when the target resists first came out that made it possible to save blank values, so that's probably what happened.
