### ISSUE TITLE
Pyfa stable - Citadel Rigs Won't Load

### ISSUE THREAD

**Issue by IFOV** [pyfa-org/Pyfa#743]
Unable to load rigs onto citadels in the stable branch.

**Comment by IFOV** [comment]
I was able to get it to work...once...sorta. I was able to load two rigs, then everything stopped working. Unable to remove them or load a third.

**Comment by Ebag333** [comment]
Also link a fit you're using. :)

**Comment by Ebag333** [comment]
So the issue appears to be specific rigs.  For example `Standup XL-Set Extinction Level Weapons Suite II` (which is possibly the most awesome name of any thing in game).

```
Traceback (most recent call last):
  File ".\gui\builtinViews\fittingView.py", line 320, in appendItem
    populate = sFit.appendModule(fitID, itemID)
  File ".\service\fit.py", line 457, in appendModule
    self.recalc(fit)
  File ".\service\fit.py", line 1132, in recalc
    fit.calculateModifiedAttributes(withBoosters=withBoosters)
  File ".\eos\saveddata\fit.py", line 545, in calculateModifiedAttributes
    item.calculateModifiedAttributes(self, runTime, False)
  File ".\eos\saveddata\module.py", line 614, in calculateModifiedAttributes
    effect.handler(fit, self, context)
  File ".\eos\effects\structurerigmaxtargets.py", line 3, in handler
    fit.ship.filteredItemIncrease("maxLockedTargets", src.getModifiedItemAttr("structureRigMaxTargetBonus"))
AttributeError: 'Citadel' object has no attribute 'filteredItemIncrease'
```

Why are we using `filteredItemIncrease`?

**Comment by Ebag333** [comment]
See #744

**Comment by blitzmann** [comment]
Done #44fb4a558cc
