### ISSUE TITLE
Pyfa stable - can't create new characters

### ISSUE THREAD

**Issue by peldar** [pyfa-org/Pyfa#745]
I cannot create new characters. All of the following methods used to work earlier.
1. File/Import Character File, using a blank character xml file from EVEMon - character doesn't show up in character editor.
2. Window/Character Editor/New character - new character doesn't show up in drop down list, skill list shows only one skill per skill group (e.g. only Mechanics in Armor group, Drones, in Drones group), no levels shown for skills. 
3. Window/Character Editor/Copy character - same result like in #2.

Each time I use one of the above method once I can no longer open the character editor (window/character editor or ctrl-e, and nothing happens).

**Comment by Ebag333** [comment]
Can you provide more information about your setup?  Windows, Mac, or Linux?  Have you looked at the log file to see if there are any errors?

**Comment by peldar** [comment]
windows 10, pyfa 1.23.2 stable, no entries in log file.

**Comment by blitzmann** [comment]
@peldar, thank you very much for providing your database, and thanks for doing that **before** wiping it out.

I am able to reproduce. You have integrity problems. The root cause is unknown as of yet, but a lot of the times it's due to upgrading from an extremely old version to a recent version. I will look into this more closely and try to find a way to prevent this issue in the future. :)

```
Traceback (most recent call last):
  File "C:\gitRoot\Pyfa\gui\builtinViews\entityEditor.py", line 102, in OnNew
    new = self.DoNew(dlg.txtctrl.GetValue().strip())
  File "C:\gitRoot\Pyfa\gui\characterEditor.py", line 80, in DoNew
    return sChar.new(name)
  File "C:\gitRoot\Pyfa\service\character.py", line 254, in new
    eos.db.save(char)
  File "C:\gitRoot\Pyfa\eos\db\saveddata\queries.py", line 499, in save
    commit()
  File "C:\gitRoot\Pyfa\eos\db\saveddata\queries.py", line 510, in commit
    saveddata_session.commit()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 801, in commit
    self.transaction.commit()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 392, in commit
    self._prepare_impl()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 372, in _prepare_impl
    self.session.flush()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 2019, in flush
    self._flush(objects)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 2101, in _flush
    flush_context.execute()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute
    rec.execute(self)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute
    uow
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\persistence.py", line 767, in _emit_insert_statements
    execute(statement, multiparams)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 1116, in _execute_context
    context)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\default.py", line 447, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: characterSkills.characterID, characterSkills.itemID [SQL: u'INSERT INTO "characterSkills" ("characterID", "itemID", "_Skill__level") VALUES (?, ?, ?)'] [parameters: ((18, 2403, None), (18, 2406, None), (18, 2495, None), (18, 2505, None), (18, 3184, None), (18, 3300, None), (18, 3301, None), (18, 3302, None)  ... displaying 10 of 423 total bound parameter sets ...  (18, 41410, None), (18, 41537, None))]
```

**Comment by blitzmann** [comment]
@peldar while the issue still remains for whatever reason, we've come up with a solution that fix this if it should come up again going forward. New release should be out in a couple days. :)
