### ISSUE TITLE
Crash on new fit

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#793]
Due to merging #774

@Ebag333  let me know if you can track this down

```
Traceback (most recent call last):
  File "C:\gitRoot\Pyfa\gui\shipBrowser.py", line 1237, in createNewFit
    fitID = sFit.newFit(self.shipID, self.tcFitName.GetValue())
  File "C:\gitRoot\Pyfa\service\fit.py", line 167, in newFit
    fit = eos.types.Fit(ship)
  File "<string>", line 4, in __init__
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\state.py", line 306, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\state.py", line 303, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "C:\gitRoot\Pyfa\eos\saveddata\fit.py", line 60, in __init__
    self.ID = None
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\attributes.py", line 224, in __set__
    instance_dict(instance), value, None)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\attributes.py", line 701, in set
    value, old, initiator)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\attributes.py", line 710, in fire_replace_event
    self._init_append_or_replace_token())
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\util.py", line 118, in set_
    return validator(state.obj(), key, value)
  File "C:\gitRoot\Pyfa\eos\saveddata\fit.py", line 374, in validator
    raise ValueError(str(val) + " is not a valid value for " + key)
ValueError: None is not a valid value for ID
```

**Comment by blitzmann** [comment]
Also, crash on removing module

```
Traceback (most recent call last):
  File "C:\gitRoot\Pyfa\gui\builtinViews\fittingView.py", line 334, in removeItem
    self.removeModule(self.mods[row])
  File "C:\gitRoot\Pyfa\gui\builtinViews\fittingView.py", line 342, in removeModule
    populate = sFit.removeModule(self.activeFitID, fit.modules.index(module))
  File "C:\gitRoot\Pyfa\service\fit.py", line 479, in removeModule
    eos.db.commit()
  File "C:\gitRoot\Pyfa\eos\db\saveddata\queries.py", line 564, in commit
    saveddata_session.commit()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 801, in commit
    self.transaction.commit()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 392, in commit
    self._prepare_impl()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 372, in _prepare_impl
    self.session.flush()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 2019, in flush
    self._flush(objects)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 2137, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\util\langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\session.py", line 2101, in _flush
    flush_context.execute()
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 373, in execute
    rec.execute(self)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 532, in execute
    uow
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\persistence.py", line 174, in save_obj
    mapper, table, insert)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\orm\persistence.py", line 800, in _emit_insert_statements
    execute(statement, params)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\sql\elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 1146, in _execute_context
    context)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\util\compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\base.py", line 1139, in _execute_context
    context)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\sqlalchemy\engine\default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: modules.fitID [SQL: u'INSERT INTO modules ("fitID", "itemID", "dummySlot", "chargeID", state, projected, position) VALUES (?, ?, ?, ?, ?, ?, ?)'] [parameters: (None, None, 3, None, 0, 0, 12)]

```
