### ISSUE TITLE
Too stupid to use linux 

### ISSUE THREAD

**Issue by master3553** [pyfa-org/Pyfa#802]
If I try to start pyfa on Linux Mint 18 Cinnamon I get this error message:

> arithmos@arithmos ~/Pyfa-master $ ./pyfa.py start
Traceback (most recent call last):
  File "./pyfa.py", line 125, in <module>
    import service.prefetch
  File "/home/arithmos/Pyfa-master/service/__init__.py", line 17, in <module>
    from service.pycrest import EVE
  File "/home/arithmos/Pyfa-master/service/pycrest/__init__.py", line 13, in <module>
    from .eve import EVE
  File "/home/arithmos/Pyfa-master/service/pycrest/eve.py", line 6, in <module>
    import requests
ImportError: No module named request

**Comment by Kyria** [comment]
Look like the package "requests" is missing on your OS. 
You can either install it using `pip install requests` or using your favorite package manager install python-requests. 

This must resolve your import error.

**Comment by master3553** [comment]
Thanks, that fixed it :)
