### ISSUE TITLE
Command Burst Charge > Show Market Group fails

### ISSUE THREAD

**Issue by blitzmann** [pyfa-org/Pyfa#838]
```
Traceback (most recent call last):
  File "C:\gitRoot\Pyfa\gui\contextMenu.py", line 135, in handler
    menuHandler.activate(context, selection, i)
  File "C:\gitRoot\Pyfa\gui\builtinContextMenus\marketJump.py", line 46, in activate
    self.mainFrame.marketBrowser.jump(item)
  File "C:\gitRoot\Pyfa\gui\marketBrowser.py", line 103, in jump
    self.marketView.jump(item)
  File "C:\gitRoot\Pyfa\gui\marketBrowser.py", line 199, in jump
    self.SelectItem(item)
  File "C:\Users\Ryan.Holmes\Python2\lib\site-packages\wx-3.0-msw\wx\_controls.py", line 5516, in SelectItem
    return _controls_.TreeCtrl_SelectItem(*args, **kwargs)
wx._core.PyAssertionError: C++ assertion "!IsHiddenRoot(item)" failed at ..\..\src\msw\treectrl.cpp(1895) in wxTreeCtrl::SelectItem(): can't select hidden root item
```

**Comment by blitzmann** [comment]
Fixed, see #842
