### ISSUE TITLE
Issue with "old" fleet boosts in Fittings

### ISSUE THREAD

**Issue by ppfeufer** [pyfa-org/Pyfa#844]
Fittings where the "old" fleet boosts where set cannot be opened or deleted.
(using current git version)

```
Traceback (most recent call last):
  File "/home/ppfeufer/applications/pyfa/gui/builtinViews/fittingView.py", line 67, in fitSelected
    view.fitSelected(event)
  File "/home/ppfeufer/applications/pyfa/gui/builtinViews/fittingView.py", line 289, in fitSelected
    self.slotsChanged()
  File "/home/ppfeufer/applications/pyfa/gui/builtinViews/fittingView.py", line 455, in slotsChanged
    self.generateMods()
  File "/home/ppfeufer/applications/pyfa/gui/builtinViews/fittingView.py", line 412, in generateMods
    fit = sFit.getFit(self.activeFitID)
  File "/home/ppfeufer/applications/pyfa/service/fit.py", line 266, in getFit
    self.recalc(fit, withBoosters=True)
  File "/home/ppfeufer/applications/pyfa/service/fit.py", line 1189, in recalc
    fit.calculateModifiedAttributes(withBoosters=False)
  File "/home/ppfeufer/applications/pyfa/eos/saveddata/fit.py", line 511, in calculateModifiedAttributes
    if self.commandFits and not withBoosters:
  File "/home/ppfeufer/applications/pyfa/eos/saveddata/fit.py", line 249, in commandFits
    return [fit for fit in self.__commandFits.values() if not fit.isInvalid]
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/ext/associationproxy.py", line 264, in __get__
    proxy = self._new(_lazy_collection(obj, self.target_collection))
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/ext/associationproxy.py", line 309, in _new
    self.collection_class = util.duck_type_collection(lazy_collection())
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/ext/associationproxy.py", line 467, in __call__
    return getattr(obj, self.target)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 583, in get
    value = self.callable_(state, passive)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 544, in _load_for_state
    return self._emit_lazyload(session, state, ident_key, passive)
  File "<string>", line 1, in <lambda>
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/strategies.py", line 614, in _emit_lazyload
    result = q.all()
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2613, in all
    return list(self)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 71, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 432, in _instance
    state.manager.dispatch.load(state, context)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/event/attr.py", line 256, in __call__
    fn(*args, **kw)
  File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 2858, in _event_on_load
    instrumenting_mapper._reconstructor(state.obj())
  File "/home/ppfeufer/applications/pyfa/eos/db/saveddata/fit.py", line 102, in init
    if self.booster_fit.isInvalid:
AttributeError: 'NoneType' object has no attribute 'isInvalid'
Traceback (most recent call last):
  File "/home/ppfeufer/applications/pyfa/gui/implantView.py", line 61, in fitChanged
    fit = sFit.getFit(activeFitID)
  File "/home/ppfeufer/applications/pyfa/service/fit.py", line 266, in getFit
    self.recalc(fit, withBoosters=True)
  File "/home/ppfeufer/applications/pyfa/service/fit.py", line 1189, in recalc
    fit.calculateModifiedAttributes(withBoosters=False)
  File "/home/ppfeufer/applications/pyfa/eos/saveddata/fit.py", line 511, in calculateModifiedAttributes
    if self.commandFits and not withBoosters:
  File "/home/ppfeufer/applications/pyfa/eos/saveddata/fit.py", line 249, in commandFits
    return [fit for fit in self.__commandFits.values() if not fit.isInvalid]
AttributeError: 'NoneType' object has no attribute 'isInvalid'
Traceback (most recent call last):
  File "/home/ppfeufer/applications/pyfa/gui/fighterView.py", line 86, in fitChanged
    fit = sFit.getFit(activeFitID)
  File "/home/ppfeufer/applications/pyfa/service/fit.py", line 266, in getFit
    self.recalc(fit, withBoosters=True)
  File "/home/ppfeufer/applications/pyfa/service/fit.py", line 1189, in recalc
    fit.calculateModifiedAttributes(withBoosters=False)
  File "/home/ppfeufer/applications/pyfa/eos/saveddata/fit.py", line 511, in calculateModifiedAttributes
    if self.commandFits and not withBoosters:
  File "/home/ppfeufer/applications/pyfa/eos/saveddata/fit.py", line 249, in commandFits
    return [fit for fit in self.__commandFits.values() if not fit.isInvalid]
AttributeError: 'NoneType' object has no attribute 'isInvalid'
```

**Comment by blitzmann** [comment]
Can you send me your `saveddata.db` and any migration databases (should be located in same directory). My email can be found in the README. Thanks!

**Comment by ppfeufer** [comment]
you should have a  mail

**Comment by blitzmann** [comment]
Thanks, I'll check it out tomorrow. :)

**Comment by blitzmann** [comment]
@ppfeufer can you tell me which fit you're trying to open that gives you that error?

**Comment by ppfeufer** [comment]
Hugin "Raumwaffe / Heavy Web and Target Painting Support"
Proteus "Raumwaffe / Ehrengarde / AB"
Zealot "Raumwaffe / AB / Beam / Damp"

and more

**Comment by blitzmann** [comment]
Okay, so I believe this has to do with the fact that there is an integrity issue. For some reason, you have a lot of booster fits that no longer exist but the reference to it was never deleted. 

I will try to get a fix out for this tonight, and also double check that command fits are properly deleted on the boosted fit if the booster fit is deleted.

**Comment by blitzmann** [comment]
This has been fixed. You can try out the latest changes in master or wait until we make a release. :)

Thanks a lot for letting us know! This was a very critical bug

**Comment by ppfeufer** [comment]
Yep, it works now. Thank you!
