### ISSUE TITLE
Apostle Fitting Freezes

### ISSUE THREAD

**Issue by Eonan** [pyfa-org/Pyfa#874]
When attempting to either load a blank or saved Apostle fit, the fit window will appear on the right with no information.  The name of the fit will change as you cycle through fits, but will not display any information for the fit itself.

![pyfabug](https://cloud.githubusercontent.com/assets/10729194/20860212/ce6df276-b940-11e6-8c13-01576f085683.png)

Have not found this issue with any other ships yet.

**Comment by blitzmann** [comment]
Confirmed bug

```
Traceback (most recent call last):
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 67, in fitSelected
    view.fitSelected(event)
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 289, in fitSelected
    self.slotsChanged()
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 455, in slotsChanged
    self.generateMods()
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\gui\builtinViews\fittingView.py", line 412, in generateMods
    fit = sFit.getFit(self.activeFitID)
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\service\fit.py", line 266, in getFit
    self.recalc(fit, withBoosters=True)
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\service\fit.py", line 1189, in recalc
    fit.calculateModifiedAttributes(withBoosters=False)
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\eos\saveddata\fit.py", line 603, in calculateModifiedAttributes
    item.calculateModifiedAttributes(self, runTime, False)
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\eos\saveddata\ship.py", line 96, in calculateModifiedAttributes
    effect.handler(fit, self, ("ship",))
  File "C:\Users\Ryan\Sync\Git\blitzmann\Pyfa\eos\effects\shipbonusforceauxiliarya4warfarelinksbonus.py", line 7, in handler
    lvl = src.level
AttributeError: 'Ship' object has no attribute 'level'
```

**Comment by blitzmann** [comment]
I've got a fix for it, but it won't be out on an official release for at least a few days
