### ISSUE TITLE
Alpha Table Missing on Previous DBs

### ISSUE THREAD

**Issue by Ebag333** [pyfa-org/Pyfa#966]
@blitzmann this is the error I got first time I ran a version with the alpha stuff.

Someone else tried it and got the same error.

Just thought I'd post it, since I couldn't replicate it.

```
Traceback (most recent call last):
  File "pyfa.py", line 248, in <module>
  File "gui\mainFrame.py", line 167, in __init__
  File "gui\multiSwitch.py", line 26, in __init__
  File "gui\chromeTabs.py", line 114, in __init__
  File "gui\chromeTabs.py", line 708, in __init__
  File "service\fit.py", line 51, in getInstance
  File "service\fit.py", line 59, in __init__
  File "eos\saveddata\character.py", line 74, in getAll5
  File "eos\db\saveddata\queries.py", line 72, in checkAndReturn
  File "eos\db\saveddata\queries.py", line 47, in setCache
  File "eos\db\saveddata\queries.py", line 171, in getCharacter
  File "site-packages\sqlalchemy\orm\query.py", line 2690, in first
  File "site-packages\sqlalchemy\orm\query.py", line 2482, in __getitem__
  File "site-packages\sqlalchemy\orm\query.py", line 2790, in __iter__
  File "site-packages\sqlalchemy\orm\query.py", line 2813, in _execute_and_instances
  File "site-packages\sqlalchemy\engine\base.py", line 945, in execute
  File "site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
  File "site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
  File "site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
  File "site-packages\sqlalchemy\engine\base.py", line 1393, in _handle_dbapi_exception
  File "site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
  File "site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
  File "site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: characters.alphaCloneID [SQL: u'SELECT characters.name AS characters_name, characters."alphaCloneID" AS "characters_alphaCloneID", characters."ID" AS "characters_ID", characters."apiID" AS "characters_apiID", characters."apiKey" AS "characters_apiKey", characters."defaultChar" AS "characters_defaultChar", characters.chars AS characters_chars, characters."defaultLevel" AS "characters_defaultLevel", characters."ownerID" AS "characters_ownerID" \nFROM characters \nWHERE characters.name = ?\n LIMIT ? OFFSET ?'] [parameters: ('All 5', 1, 0)]
```

**Comment by blitzmann** [comment]
We already have a migration script that adds this column. Get the database from then to check the user version of three database

**Comment by blitzmann** [comment]
This person that had this issue: you didn't happen to give them a build of the pyinstaller one, did you? That one doesn't seem to have the migration script in it.

**Comment by blitzmann** [comment]
This seems to be caused by #968.

In the future, if an issue is going to be reported, make sure it's based off of the currently released version, or at least note that the issue happens on a development / refactor branch and where it is.

If it's determined to not be caused by #968, then please reopen.

**Comment by Ebag333** [comment]
I got this traceback once in Dev after you merged everything. Then I couldn't replicate it. 

So pretty sure it's not caused specifically by #968 and pretty sure #968 forked after all the alpha changes, so it SHOULD work.

**Comment by blitzmann** [comment]
I am not sure what was going on then, unless the migration imports aren't working at all, which I tested again a few days ago. I'll test once more, but if I don't find anything (and the fact that we haven't received any complaints after 1038 downloads of the pre-release), I'm gonna keep this closed.

But I think, as a general rule, both of us should try to note the version (if stable) / git commit hash (if in dev) when reporting issues. Would probably help diagnose things.

**Comment by Ebag333** [comment]
Don't worry about testing it right now. If I can replicate it I'll reopen this.
